### ISSUE TITLE
Code is indented with tabs instead of spaces

### ISSUE THREAD

**Issue by seemethere** [channelcat/sanic#1]
Just wanted to comment on this because I wanted to contribute some documentation for sanic, but I just wanted to let you know all of your indentation right now is being done with tabs.

Instead of submitting a pull request for this though, and overwriting all the hard work you did to get this up and running, I thought I would submit an issue to allow you to fix it yourself.

It's as easy as running `:retab` in vim or if you are using pycharm it's as easy as reformatting.

Or you could use something like sed.

I can still take care of it if you want just let me know.

**Comment by n1ywb** [comment]
it would be nice to fix, pycharm is showing pep8 violations on every line due to this

**Comment by channelcat** [comment]
Ah, I did not know this would cause issues.  I've run a reformat in pycharm and merged it in :).  Let me know if anything still looks funky.

https://github.com/channelcat/sanic/pull/5

**Comment by seemethere** [comment]
awesome! Will do! Thanks for being quick @channelcat
