### ISSUE TITLE
Do not override log configuration

### ISSUE THREAD

**Issue by Stibbons** [channelcat/sanic#1000]
Hello.

Can you optionalize the `logging.config.dictConfig` in `app.py`? My application already have a comprehensive log configuration (and does not use log conf), I don't need to change it.

For the moment, my workaround is to override the `Sanic` class:
```

class UseMyLoggingSanic(Sanic):

    def __init__(self, name=None, router=None, error_handler=None,
                 load_env=True, request_class=None,
                 strict_slashes=False):

        from collections import deque, defaultdict
        from inspect import stack, getmodulename
        from sanic.router import Router
        from sanic.handlers import ErrorHandler
        from sanic.config import Config

        # Get name from previous stack frame
        if name is None:
            frame_records = stack()[1]
            name = getmodulename(frame_records[1])

        # logging
        # logging.config.dictConfig(log_config or LOGGING_CONFIG_DEFAULTS)
        self.log_config = None

        self.name = name
        self.router = router or Router()
        self.request_class = request_class
        self.error_handler = error_handler or ErrorHandler()
        self.config = Config(load_env=load_env)
        self.request_middleware = deque()
        self.response_middleware = deque()
        self.blueprints = {}
        self._blueprint_order = []
        self.debug = None
        self.sock = None
        self.strict_slashes = strict_slashes
        self.listeners = defaultdict(list)
        self.is_running = False
        self.is_request_stream = False
        self.websocket_enabled = False
        self.websocket_tasks = set()

        # Register alternative method names
        self.go_fast = self.run
```

This way, logs are routed correctly in my debug terminal, and not twice

**Comment by yunstanford** [comment]
You can pass in your own configuration. or are you saying you have log in another layer of your architecture ? 

You can disable access_log by `app.run(access_log=False)`.

**Comment by Stibbons** [comment]
Yes, I have a configuration module that handle the logging config on its own. I now simply call ```Sanic(__name__, log_config=None)`` and log are disabled, but I don't have any access log from sanic at all. Can't you just optionialize the call to 
```
logging.config.dictConfig(log_config or LOGGING_CONFIG_DEFAULTS)
```
?

**Comment by joar** [comment]
Currently i re-configure logging after the call to `Sanic()`, but I wish I could tell sanic to not care about the logging configuration, *just keep logging fast*.

I'm using [structlog](http://www.structlog.org/en/stable/), and [Rendering Using structlog-based Formatters Within logging](http://www.structlog.org/en/stable/standard-library.html#rendering-using-structlog-based-formatters-within-logging).

 I think that #1004 looks like an appropriate fix, with an extra wish: https://github.com/channelcat/sanic/pull/1004#issuecomment-341449784

**Comment by Stibbons** [comment]
Thanks for this project, structlog looks much much better of my own cooked colorful&fancy-yet-production-ready cutomized log handler :)
