### ISSUE TITLE
Add Sanic benchmark to TechEmpower

### ISSUE THREAD

**Issue by Dowwie** [channelcat/sanic#1036]
Would you please consider adding Sanic to the TechEmpower benchmarks?  TechEmpower is due for another run.

https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/Python

**Comment by gsakkis** [comment]
Just submitted a [PR](https://github.com/TechEmpower/FrameworkBenchmarks/pull/3127) for Sanic 0.7.0.

**Comment by r0fls** [comment]
Since https://github.com/TechEmpower/FrameworkBenchmarks/pull/3127 has been merged I'll close this. Thanks!
