### ISSUE TITLE
sanic.router.RouteExists: Route already registered: /static<file_uri:/?.+> [GET,HEAD]

### ISSUE THREAD

**Issue by vlad1777d** [channelcat/sanic#1048]
Hello.

I'm trying to add several static directories (one - global, one - for package) under different links, but it tells that 'route already registered'.

I add this static folders in ./main/app.py and ./packages/gatekeeper/views.py

I add here all my project (it's little, on the beginning): [times_new_novel_asyncio.zip](https://github.com/channelcat/sanic/files/1541106/times_new_novel_asyncio.zip)

I would be grateful for help and correcting this =)

_Offtop:
my temporary fix is to have only one static folder_

Best regards,
Vladislav

**Comment by lixxu** [comment]
paste your codes that caused the errors.

**Comment by vlad1777d** [comment]
@lixxu ,

./main/app.py file:
```python
link_to_static = '/static'
app.static(link_to_static, './main/static')
```
./packages/gatekeeper.views.py:
```python
link_to_static_gatekeeper = '/static_gatekeeper'
app.static(link_to_static, './packages/gatekeeper/static')
```
This last causes error.

**Comment by lixxu** [comment]
that maybe because the route (generated by app.py) `/static<file_uri:/?.+>` also covers `/static_gatekeeper` and even the second is OK, the url will never be reached as the first one already matches the url.

**Comment by lixxu** [comment]
use this instead:
```
link_to_static_gatekeeper = '/gatekeeper_static'
app.static(link_to_static, './packages/gatekeeper/static')

**Comment by vlad1777d** [comment]
@lixxu , yes, thanks, all is well =)
