### ISSUE TITLE
[question] How to set 'SameSite' header to 'Strict' in response.cookie ?

### ISSUE THREAD

**Issue by vlad1777d** [channelcat/sanic#1050]
Hello.

Sorry, I had not figured out, how to set cookie, which I wan't to send in response to 'Strict' mode ?

_Offtop:
Is there some IRC channed or something like this dedicated to Sanic ?_

Thank you.
Best regards,
Vladislav

**Comment by Nothing4You** [comment]
_Offtopic: I have created [#sanic](ircs://chat.freenode.net:6697) on freenode, I didn't find anything else either.
chat.freenode.net:6697 / non-SSL: 6667
If someone from this project wants to take over please message me_

**Comment by r0fls** [comment]
Well it needed a PR 🙄  This should do it afterwards though:

```python
from sanic.response import text

@app.route("/cookie")
async def test(request):
    response = text("There's a cookie up in this response")
    response.cookies['hello'] = 'world'
    response.cookies['hello']['samesite'] = 'strict'
    return response
```

**Comment by vlad1777d** [comment]
@r0fls, thank you very much =)

I thought, that, maybe, there is a way to add custom headers. Like by modification request instance, but I'm not familiar with it.
