### ISSUE TITLE
 HTTP header WWW-Authenticate realm should be double-quoted, not single quoted.

### ISSUE THREAD

**Issue by rgacote** [channelcat/sanic#1061]
From all the documentation I can find (and I'm not an expert in HTTP headers), I believe the Unauthorized exception is incorrectly quoting the values. 

For example, Sanic returns this:
    WWW-Authenticate: Basic realm='XML'
and I think it should be:
   WWW-Authenticate: Basic realm="XML"

Recommend the following line in the __init__ be changed
```
-             values = ["{!s}={!r}".format(k, v) for k, v in kwargs.items()]
+            values = ['{!s}="{!s}"'.format(k, v) for k, v in kwargs.items()]

```
Not sure how much of a practical difference this is, but it does seem to be out of spec. 

I also reviewed the rest of the exception code and this seems to be the only place using the !r formatting.

**Comment by rgacote** [comment]
Agree it is a bit terse. 
I interpret  https://stackoverflow.com/q/7886782/1412022 as meaning a quoted string:
* May start and end with a double quote (apparently, if it is a single term the quotes are not necessary).
* The data itself must not contain a double quote (qdtext rule).
* May contain any number of qdtext or quoted-pair values (odd use of '*' before rather than after).
* Text may include Linear White Space (LWS) (space, horizontal tab)
* Backslash may be used as a 'quoting' mechanism 'within' a quoted-string.
   I believe that to indicate you could so something like:
       "abc\"def"

What is clear, is that the 'quoted-string' is defined as either without any quotes (single-word) or with double-quotes. Single quotes are not defined in the specification (though various browsers and libraries may allow them).

**Comment by r0fls** [comment]
Good call
>quoted-string  = DQUOTE *( qdtext / quoted-pair ) DQUOTE

https://tools.ietf.org/html/rfc7230#section-3.2.6

**Comment by rgacote** [comment]
Thanks for the quick turn-around.
