### ISSUE TITLE
Blueprint with a set url_prefix wont allow POST requests

### ISSUE THREAD

**Issue by mattfinnell** [channelcat/sanic#1074]
Considering the following snippet, the GET request works perfectly. But the POST request results in `sanic.exceptions.InvalidUsage: Method POST not allowed for URL /api/failing`. This seems to be specific when `url_prefix` is set. 

```python
from sanic import Sanic, Blueprint
from sanic.response import text, json

app = Sanic()

failing_bp = Blueprint('failing_blueprint', url_prefix='/api/failing')

@failing_bp.get("/")
async def get_data(request):
    return json({
        "hello": "world",
        "I am working if": "you see me",
        "from": "the failing blueprint"
    })

@failing_bp.post("/")
async def post_data(request):
    return text("POST [FAILING] - {}\n\n{}".format(
        request.headers,
        request.body
    ))

if __name__ == "__main__":
    app.blueprint(failing_bp)

    app.run(debug=True, host="0.0.0.0", port=8000)
```

The extra weird part, is that if you were to comment out (or remove) the GET request from the blueprint, the POST request works pefectly fine. 

I've got a super small repository that highlights this if you want to mess with it yourself.

https://github.com/mattfinnell/sanic-blueprints

EDIT : User *mateusz_b* on the python slack channel stated that this had to deal with an issue regarding trailing slashes in the url. Performing the post request with a trailing slash allowed it to work just fine, but there seems to be quite a bit of odd behavior behind this. Especially considering that an endpoint with a non-trailing slash will only work if the POST request is the ONLY route in the blueprint.

**Comment by r0fls** [comment]
I thought I fixed this already. Will have to look again soon. Thanks for reporting.
