### ISSUE TITLE
self.form() is not called when parsing files in Request

### ISSUE THREAD

**Issue by eulhaque** [channelcat/sanic#1075]
Was looking thru the request.py code and realize that, there is a typo here:
https://github.com/channelcat/sanic/blob/master/sanic/request.py#L139

You are missing parenthesis when calling self.form.

**Comment by r0fls** [comment]
Thank you, but that is not necessary because `form` is a property: https://github.com/channelcat/sanic/blob/master/sanic/request.py#L114-L115

That means that you can access the result of the method without the `()`.
