### ISSUE TITLE
How to achieve throttling?

### ISSUE THREAD

**Issue by hustshawn** [channelcat/sanic#1099]
I am using sanic to provide API service. But I need a throttling mechnism to control API access within a predefined limit. How can I achieve it?  I cannot find any related topic in the official document.

**Comment by howie6879** [comment]
Hi, maybe you can try this package [sanic-limiter](https://github.com/bohea/sanic-limiter)

**Comment by c-goosen** [comment]
@howie6879 thats a pretty interesting package. Will give it a look. Although I might advise using something like nginx to rate limit: https://www.nginx.com/blog/rate-limiting-nginx/. Nginx will rate limit by remote_addr and keeps computation of rate limiting out of the application. Also you can reload nginx config without killing the daemon, within limits.

**Comment by seemethere** [comment]
Closing per @howie6879's suggestion

**Comment by dmarkey** [comment]
Just so sanic-limiter users know about this bug i'll reference it here.

https://github.com/bohea/sanic-limiter/issues/6
