### ISSUE TITLE
Everyone uses uWSGI + Nginx not Gunicorn to go fast

### ISSUE THREAD

**Issue by alanhamlett** [channelcat/sanic#11]
Benchmarks should use uWSGI + Nginx.

**Comment by adlenafane** [comment]
@alanhamlet do you have any links with those benchmarks? 
Thanks!

**Comment by channelcat** [comment]
Hmm, I could switch over and update the benchmarks.  What is currently considered the best way to deploy with uwsgi+nginx?  With gunicorn I had to use the meinheld worker.

**Comment by ddorian** [comment]
Only those are needed. Uwsi intro guide explains everything

**Comment by alanhamlett** [comment]
@seemethere sticking with the slower gunicorn?
