### ISSUE TITLE
How stable is Sanic? Can we consider it as at least beta?

### ISSUE THREAD

**Issue by manisenkov** [channelcat/sanic#1103]
How stable is Sanic now? Is there serious bugs or plans to drastically change API?
Current status is [`Development Status :: 2 - Pre-Alpha`](https://github.com/channelcat/sanic/blob/9751a373439848548577203e34ca18d81e1509bb/setup.py#L46), maybe it's a time to change it to at least `Development Status :: 4 - Beta`?

**Comment by ashleysommer** [comment]
I agree, I am using Sanic at work, for a few research and development projects.
I believe it is stable enough to move to Beta.
The only thing stopping me from using Sanic in more production-ready projects is the "Development Status" declaration.

**Comment by r0fls** [comment]
Sounds good to me 👌🏼. If someone wants to update that I’ll accept the PR.

**Comment by r0fls** [comment]
Closing this since we've updated it to beta status.
