### ISSUE TITLE
Please Add me - New Cairo, Egypt

### ISSUE THREAD

**Issue by amirabehery** [channelcat/sanic#1116]
## Hi Everyone! This issue is to track the addition of 'Cairo' to the map, which can be found at :
- Longitude :  30.051382
- Latitude : 31.460982

**Comment by AndreiRegiani** [comment]
Are you lost, my friend?

**Comment by joar** [comment]
I believe you're looking for https://github.com/githubschool/open-enrollment-classes-introduction-to-github/issues

**Comment by seemethere** [comment]
Thanks @joar
