### ISSUE TITLE
Restic - a loose & flexible REST framework for Sanic. Inspired by Django REST Framework.

### ISSUE THREAD

**Issue by and3rson** [channelcat/sanic#1118]
Hi everyone,

I can't even express how cool Sanic is. I've recently started using it and it looks like an amazing replacement for somehow outdated & conservative Django framework (which I've been using for over 5 years now).

I'm currently building a well-documented and flexible REST framework for Sanic called Restic. It is somewhat inspired by Django REST Framework in terms of architecture, but actual implementation of things is going to be more verbose comparing to DRF. In fact, the only thing that is partially borrowed from DRF is the serializers/viewsets concept.

Ideally by using Restic + Sanic I'm aiming to create an explicit & fast asyncio-based REST framework with the support of serializers & viewsets, streaming endpoints, OpenAPI schema generation, authentication & permissions etc. Main goal is to provide flexible & hackable REST implementation to your Sanic apps.

Link to the repo: https://github.com/and3rson/restic

The project is currently on its alpha state.

Collaborators are warmly welcome!

I hope this is going to be interesting & useful to someone as much as it is to me.

**Comment by ashleysommer** [comment]
Thanks for your writeup, and for building a sanic plugin, and contributing to the community.

However I do want to point out that Sanic is _not _ a replacement for the Django web framework. Django is a very capable MVT web framework that comes with a _lot_ of out-of-the-box functionality including its own backend-agnostic DB ORM, its own Templating Engine, a bundled user authentication system, admin interface, and tons of built-in security features like CSRF-protection and XSS-protection. Sanic does not and will not do any of those things.

Sanic is more commonly compared to Flask, as it is more similar in features. In some cases Sanic _is_ a great modern asyncio replacement to Flask that allows you to build modern async web applications in python 3.5+, which is something Flask cannot do.

**Comment by and3rson** [comment]
@ashleysommer Thanks for the follow-up!

I see your point. In fact I've recently been developing restic a *lot* and I really see the problems now: by developing it I tried to build a very flexible and advanced REST framework that enforces cannonical REST. But I see that it became too abstract (mostly with the lack of predefined ORM interface etc.)

At this point I think I'm deprecating `restic` in favor of more lightweight pluggable things rather then building a whole new framework for another framework.

You are the voice of wisdom :)
