### ISSUE TITLE
Passing the list into route decorator's host argument

### ISSUE THREAD

**Issue by mexicarne** [channelcat/sanic#1120]
Hello,

according to the [docs](http://sanic.readthedocs.io/en/latest/sanic/routing.html#http-request-types) :
> There is also an optional host argument (which can be a list or a string)

But if I try to pass a list into host argument, I got 
```python
File "/path/lib/python3.6/site-packages/sanic/router.py", line 216, in merge_route
    uri, ','.join(list(duplicated))))
sanic.router.RouteExists: Route already registered: test.com/post/ [POST]
```

Here is the test sample:
```python
from sanic import Sanic
from sanic.response import text

app = Sanic()

@app.route('/post', methods=['POST'], host=['test.com', 'test2.com'])
async def post_handler(request):
    return text('POST request for test.com - {}'.format(request.json))

@app.route('/post', methods=['POST'])
async def post_handler(request):
    return text('POST request for default - {}'.format(request.json))

if __name__ == '__main__':
    app.run(host='127.0.0.1', port=8000)
```

I get the same exception if I'm passing the list with single value in it (`host=['test.com']`). Everything works as expected if host argument is a string though. Am I doing something wrong or it's a bug in documentation/sanic?

Sanic is installed from pip: sanic==0.7.0

**Comment by tandalf** [comment]
Hello @mexicarne it's actually a bug in sanic. I was able to reproduce your issue.
A quick hack for this would be to set strict_slashes to True when calling @app.route. I'v pushed a PR for this. Pending it's approval, you could use this quick fix.

**Comment by mexicarne** [comment]
@tandalf , that was fast! I can't reproduce the problem after applying the patch from your PR. Now both string and list working flawlessly. Thank you!

**Comment by tandalf** [comment]
My pleasure. I'm glad it helped.
