### ISSUE TITLE
Release Schedule

### ISSUE THREAD

**Issue by pyk** [channelcat/sanic#1134]
Hey guys, I want to handle `MethodNotSupported` exceptions but found out that the branch `master` is not released yet. The lastest version is 0.7.0 https://github.com/channelcat/sanic/releases, When the master branch is released to the pypi?

thanks

**Comment by seemethere** [comment]
Releases are handled when needed. A new release will probably be drafted within the next 2 weeks.

**Comment by pyk** [comment]
@seemethere okay 👍

**Comment by pyk** [comment]
It's been two weeks, any update?

**Comment by nhydock** [comment]
If you really want to use the newest stuff, pip allows for git dependencies, just don't expect it to be perfectly stable.
```
pip install git+https://github.com/channelcat/sanic.git
```

**Comment by kinware** [comment]
You can also "pin" the install at a specific Git revision. This can avoid surprises should you re-create the virtual env at a later time.

```
pip install git+https://github.com/channelcat/sanic.git@cc84005
```

**Comment by pyk** [comment]
Thanks @nhydock @kinware !
