### ISSUE TITLE
[Suggestion]: auto reload

### ISSUE THREAD

**Issue by AberSheeran** [channelcat/sanic#1158]
When the code be changed with DEBUG=True，Server will reload like flask.

Why not do that？

**Comment by hustshawn** [comment]
You can use sanic-admin

**Comment by AberSheeran** [comment]
I've already written a tool to manage it. Thank your help. 
But I think it would be better if sanic built this feature.

**Comment by Berkodev** [comment]
You can use the library [AoikLiveReload ](https://github.com/AoiKuiyuyou/AoikLiveReload) to do that.

Take a look at the demo here:
https://github.com/AoiKuiyuyou/AoikLiveReload/blob/master/src/aoiklivereload/demo/sanic_demo.py

**Comment by Yaser-Amiri** [comment]
To enable auto reloading developer must pass "auto_reload=True" to "run" method of Sanic app.

**Comment by AberSheeran** [comment]
Really? I don't know that but I will try soon after class. I'm a student😳

**Comment by AberSheeran** [comment]
@Yaser-Amiri 
Hey, I try it, but get a TypeError
```python
Traceback (most recent call last):
  File "main.py", line 55, in <module>
    main.run("0.0.0.0", 8000, debug=True, auto_reload=True)
TypeError: run() got an unexpected keyword argument 'auto_reload'
```

Is there anything I've overlooked?

**Comment by yunstanford** [comment]
it's `app.run` https://github.com/channelcat/sanic/blob/master/sanic/app.py#L652.

**Comment by AberSheeran** [comment]
Thank your help. Don't have this parameter in the version I installed with PIP. I will update Sanic from github. @yunstanford

**Comment by yunstanford** [comment]
@Yaser-Amiri can you double check the unit test here ? https://github.com/channelcat/sanic/blob/master/tests/test_auto_reload.py
it's actually failing on my side, and might also try refactor a little bit, it's not very pytest style.
