### ISSUE TITLE
Variable names overriding other routes'?

### ISSUE THREAD

**Issue by WilliamMayor** [channelcat/sanic#1174]
I think there's a strong possibility that this is a mistake on my part, but I can't find anything about it.

If I have two routes with the same path, but different methods, also with differently named path variables, then one variable name overrides the other. Causing the second method to fail because it doesn't get given the variables it was expecting. Here's an example:

```
@app.route('/foo/<public_id>/', methods=['GET'])
def get_foo(public_id):
    ...

@app.route('/foo/<id>/, methods=['DELETE'])
def delete_foo(id):
    ...
```

`delete_foo` fails because it is given an "unexpected keyword argument 'public_id'".

In my case I have a shareable URL that my users can share with friends. The delete method should remain private, and is given a different ID.

**Comment by LynnShaw** [comment]
You have missed the parameter `request`.  `def delete_foo(request, id):` and `def get_foo(reqeust, public_id):`

**Comment by r0fls** [comment]
I'm going to close this since @LynnShaw is correct

**Comment by WilliamMayor** [comment]
That was just a mistake in my example. In my actual code base I have the request parameter.

I also have a decorator that adds a DB connection to the parameters. Could that be the cause?

```
def needs_db_write(func):
    async def wrapper(request, *args, **kwargs):
        async with request.app.pool.acquire() as conn:
            async with conn.transaction():
                return await func(request, conn, *args, **kwargs)
    return wrapper

@route(...)
@needs_db_write
def delete_foo(request, db, id):
    ...
```
