### ISSUE TITLE
Installing Sanic on Windows for PyCharm?

### ISSUE THREAD

**Issue by SuperSajuuk** [channelcat/sanic#1192]
Hi there. I'm trying to install Sanic on my Python 3.6.1 installation for usage in PyCharm. But it seems that the module won't install via PyCharm natively because of uvloop/ujson not being supported on Windows.

I checked the issue tracker and saw this has been fixed, but I still keep running into the issue no matter what and it's preventing me using Sanic to develop a dashboard for my Discord Moderator Bot (it uses Flask, but that's inherently slow/not async).

Hopefully you can give some tips on how to install Sanic for PyCharm :D

**Comment by georgejdanforth** [comment]
Hi @SuperSajuuk, PyCharm will run whichever python interpreter you specify for your project, defaulting to whichever version is in your PATH.  To install Sanic (and for numerous other reasons), I would recommend that you create a python 3.6 [`virtualenv`](https://virtualenv.pypa.io/en/stable/) for your project and install Sanic in it using `pip` with the flags specified in this project's README to disable uvloop and ujson. After you've installed sanic and all your other dependencies in the virtualenv, you should be able to select the virtualenv as your project interpreter in your PyCharm settings under Project>Project Interpreter. Hope this helps!

P.S. I'm surprised that you haven't found Flask to be performant enough for your use case. Out of curiosity, could you elaborate a bit on where you're experiencing bottlenecks or performance shortcomings?

**Comment by SuperSajuuk** [comment]
Hi there @georgejdanforth thanks for responding!

I'm using a Py 3.6.1 virtualenv, I'll have a look at the readme more closely to see what i missed.

As for flask, I suspect it is due to the way I'm using it, but whenever one user access the Flask component, nobody else can use it. I'm hoping that using sanic will make it more easier to not have to try and use WSGI or other things that Flask seems to need to deploy it better (which don't work on my VPS).

**Comment by georgejdanforth** [comment]
Hi @SuperSajuuk, I can't really speak to why the installation via PyCharm is not working as I've never really used PyCharm as a dependency management tool.  Sorry if I wasn't being clear, but I would recommend that you install Sanic using:
```
SANIC_NO_UVLOOP=true SANIC_NO_UJSON=true pip install sanic
```
via the command line as specified in the docs, after you've activated your virtualenv in a shell session.  Docs on how to activate your virtualenv on windows can be found [here](https://virtualenv.pypa.io/en/stable/userguide/) if you're not already familiar.

As a final note, your performance woes with Flask are almost certainly due to your configuration and attempting to use the development server to serve production traffic. I can't say for sure without knowing all the details, but my guess would be that this problem would be solved by deploying behind a proper WSGI server such as Gunicorn.

**Comment by SuperSajuuk** [comment]
Hi there. I've looked through the documentation and managed to get Powershell to activate the virtual environment, but that command you are suggesting will not run, as it returns this error:
```(PyCharm IDE) PS D:\PyCharm IDE\Scripts> SANIC_NO_UVLOOP=true SANIC_NO_UJSON=true pip install sanic
SANIC_NO_UVLOOP=true : The term 'SANIC_NO_UVLOOP=true' is not recognized as the name of a cmdlet, function, script
file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct
and try again.
At line:1 char:1
+ SANIC_NO_UVLOOP=true SANIC_NO_UJSON=true pip install sanic
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (SANIC_NO_UVLOOP=true:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException```

Even if I go and use the `set` function and install, it will continue to try installing uvloop and ujson anyway and just ignores what I told it to. Any help would be appreciated ^_^ (This is a Windows 10 Pro pc, on the Fall CU update, for the record).

**Comment by SuperSajuuk** [comment]
A few hours later, I eventually found one solution (install from source seems to work per another thread), but I get stuck on the httptools, which fails for missing Visual C++ 14.0. I installed this, but it just complained that it wasn't there anyway, despite blatantly being installed. I'll keep trying to make this work, I guess I'm on the right track, but I really hope Sanic can provide a simple installer or script that installs Sanic into Windows directly without all this hassle.

**Comment by dujinyu** [comment]
@SuperSajuuk the same problem happened to me, i don't want to use linux since i need to develop frontend code. To my extreme curiosity, have you solved the issue? if you have, please tell me how to do it and thanks.

**Comment by SuperSajuuk** [comment]
@dujinyu Hi, I never resolved the problem and just gave up trying to use Sanic as a result. You're better off just sticking with Flask and using a web server proxy (like Apache or Nginx) to handle multiple requests.

**Comment by harshanarayana** [comment]
@SuperSajuuk @dujinyu 

```bash
$ export SANIC_NO_UVLOOP=true
$ export SANIC_NO_UJSON=true
$ pip3 install --no-binary :all: sanic
```
This should install `sanic` without uvloop/ujson. Can you try this out once ?

**Comment by jangjichang** [comment]
> @SuperSajuuk @dujinyu
> 
> ```shell
> $ export SANIC_NO_UVLOOP=true
> $ export SANIC_NO_UJSON=true
> $ pip3 install --no-binary :all: sanic
> ```
> 
> This should install `sanic` without uvloop/ujson. Can you try this out once ?

First of all, thank you for this answer.

But I tried to install it as you explained, but it failed.

The error message is as follows.

Command "c: \ users \ jcjang \ appdata \ local \ programs \ python \ python37-32 \ python.exe -u -c" import setuptools, tokenize; __ file __ = 'C: \\ Users \\ jcjang \\ AppData \\ Replace ('\ r \ n'); f = getattr (tokenize, 'open', open) install -record C: \ Users \ jcjang \ AppData \ Local \ Temp \ pip-record (code, __file__, 'exec' -cdd1cntz \ install-record.txt --single-version-externally-managed --compile "failed with error code 1 in C: \ Users \ jcjang \ AppData \ Local \ Temp \ pip-install-53zn3k2e \ httptools \

How can I fix this error when I get this error message?

**Comment by wissemnano** [comment]
the problem is relied to httptools, so first try to install it. in my case i tried : pip3 install httptools
the i have a problem : "error: Microsoft Visual C++ 14.0 is required"
so download it and you can install httptools and sanic

**Comment by mojimi** [comment]
Yup the issue is with Visual C, which is annoying so I just decided it was better to install ubuntu
