### ISSUE TITLE
Debian 9 problem

### ISSUE THREAD

**Issue by labbit** [channelcat/sanic#1204]
LXC woth Debian 9, install from git-repo :

```
ar: `u' modifier ignored since `D' is the default (see `U')
uvloop/loop.c:20:20: fatal error: Python.h: No such file or directory
 #include "Python.h"
                    ^
compilation terminated.
error: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

```

**Comment by frnkvieira** [comment]
Sanic setup is trying to build the uvloop dependency but you don't have the required C headers.

**sudo apt install python3-dev**

**Comment by TheMasterRoot** [comment]
its no worked for me

**Comment by sjsadowski** [comment]
@TheMasterRoot please open a new issue, this one has been closed for more than 2 years. When you do, please fully describe the issue you're encountering.
