### ISSUE TITLE
Invalid request should not cause server error

### ISSUE THREAD

**Issue by jasonab** [channelcat/sanic#121]
server.py, line 91:
Inability to parse the request should generate a proper 400 status code, not kill the request and log an error.

**Comment by jasonab** [comment]
To update this issue, I'm referring to this block of code:

 # Parse request chunk or close connection
        try:
            self.parser.feed_data(data)
        except HttpParserError as e:
            self.bail_out(
                "Invalid request data, connection closed ({})".format(e))

Now lines 105-110

**Comment by r0fls** [comment]
@jasonab is this issue still present?  It looks like the above snippet is now outdated. If the issue still exists, can you give an example curl request that is invalid and causing a server error?

**Comment by jasonab** [comment]
Agree that this issue was fixed by commit 75fc9f9
