### ISSUE TITLE
Support different implementation with same route but different method

### ISSUE THREAD

**Issue by chhsiao90** [channelcat/sanic#123]
Like RESTful service, that different method on same url could have different implementation.
It seems that current version of Sanic cannot define different function that had same url but with different methods.
And it cannot get method from request.

So I suggest that if Sanic could provider functionality like that would be great.
Thanks!

**Comment by pcdinh** [comment]
It makes things complicated. 

The straightforward way to get what you want is to define multiple methods for a single endpoint and check `request.method` when you need to treat it differently.

```
    @app.route('/test', methods=['GET', 'POST'])
    async def login(request):
        if request.method == 'GET':
            return text('Show login form')
        # Handle POST request
        validate(request.body)
```

**Comment by chhsiao90** [comment]
Yes, that make sense!
Is that current version of Sanic support request.method?
I didn't find it at document, I will try it later!
And thanks for your response!

**Comment by chhsiao90** [comment]
@pcdinh , thanks for your advice, it works!

**Comment by yoloseem** [comment]
Any future plan to support multiple routes on same uri but with different method in Sanic(so it can be more Flask-like)? Or was that the kinda design decision that will last? If someone don't mind if I send a patch on this idea, I would like to do though this issue was closed.

**Comment by opensorceror** [comment]
Doesn't look like this is the case anymore; I am able to create two implementations using the same uri, e.g.:

```python
@app.get("/api/v1/resource/<id>")

@app.delete("/api/v1/resource/<id>")
```
