### ISSUE TITLE
List of all routes in Sanic, like flask?

### ISSUE THREAD

**Issue by garyo** [channelcat/sanic#1236]
Is there a way to get a list of all routes and their handlers in Sanic?

**Comment by anthonyolea** [comment]
Hi @garyo 

The solution I found once is to lookup into the `app.router.routes_names` (which is a dictionary containing all the information you may need about your routes).

```
from sanic import Sanic
from sanic.response import json

app = Sanic()

@app.route('/hello/<name>')
async def hello(request, name):
    return json({'hello': name})

for handler, (rule, router) in app.router.routes_names.items():
    print(rule)

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=8000)
```

Hope, that may help.
Please notice that I got an issue when a `/` route and a `/<name>` are defined, the `/` route will not be printed.

**Comment by garyo** [comment]
Thanks, that works for me!

**Comment by pawelkoston** [comment]
For newer versions:
`        
for route in self.app.router.routes_all:
            print(f"/{route.path:60} - {route.name:70} -  {route.methods} [{route.router}]")
`

**Comment by ahopkins** [comment]
@pawelkoston `routes_all` is a `dict`. I think you want `app.router.routes`

**Comment by pawelkoston** [comment]
I am using sanic==21.3.0 and for that version it was a tuple (https://github.com/sanic-org/sanic/blob/v21.3.0/sanic/router.py#L162)
In current version it is a dict, thank you for that information.
