### ISSUE TITLE
Hope to increase the support session

### ISSUE THREAD

**Issue by mrcodehang** [channelcat/sanic#124]
I use the sanic, and found no session of this function. Hope to increase this function, thank you.

**Comment by jackfischer** [comment]
Do you mean you're looking for session support? I don't think sanic supports this natively, but you may be able to integrate beaker, or roll your own setup for sessions with Redis or Memcached.

**Comment by rednebmas** [comment]
How would one integrate beaker into sanic? I tried, but I'm confused as where to hook it into sanic.

**Comment by wojunnihou** [comment]
参照HTTPMethodView，写一个basehandle，所有接口都继承 basehandle。在basehandle里面可以实现session的处理。继承的basehadle也就具有处理session的功能

**Comment by mrcodehang** [comment]
我实现session的方法是使用JWT  :smile_cat:

**Comment by seemethere** [comment]
Translation of @wojunnihou courtesy of google translate:

> With reference to HTTPMethodView, write a basehandle, all interfaces inherit basehandle. In the basehandle which can be achieved session processing. Inherited basehadle also has the function of dealing with the session

**Comment by subyraman** [comment]
FYI I wrote an extension for sanic which provides server-backed sessions: [sanic_session](https://github.com/subyraman/sanic_session).

**Comment by mrcodehang** [comment]
@subyarman thank you very much

**Comment by rednebmas** [comment]
Awesome! I think this should be in Sanic's documentation!

**Comment by jackfischer** [comment]
Great work

**Comment by seemethere** [comment]
Closed per @subyraman's awesome extension!
