### ISSUE TITLE
Case-sensitive headers issue

### ISSUE THREAD

**Issue by aherok** [channelcat/sanic#1242]
Hello! Sanic uses plain dicts to keep headers which causes the headers to be case-sensitive. 
According to [RFC 2616](http://www.ietf.org/rfc/rfc2616.txt) headers should be case-insensitive.

This causes issues when we want to override headers' values.

Simple example to test:
```
@app.route("")
async def test(request: Request):
    return json({
        "ok": True
    }, headers={
        'CONTENT-TYPE': 'application/json'
    })
```
requesting such endpoint will return 'doubled' headers:
```
CONTENT-TYPE: application/json
Content-Length: 11
Content-Type: application/json
```

**Comment by pyx** [comment]
Might as well just use [`class Headers`](https://docs.python.org/3/library/wsgiref.html#wsgiref.headers.Headers)    from the standard library or build on top of that.

**Comment by yunstanford** [comment]
there is a simple CIDict (https://github.com/channelcat/sanic/blob/master/sanic/server.py#L42) in `server.py` module we can use, but it's a little buggy now because it doesn't handle some cases, like initializing CIDict with non-empty dict.
