### ISSUE TITLE
Headers are presented in a case-sensitive manner

### ISSUE THREAD

**Issue by jasonab** [channelcat/sanic#126]
server.py, on_header and on_headers_complete:

HTTP headers are considered case-insensitive, but Python dict keys are case sensitive. WSGI bypasses this problem by setting specific variables (e.g. HTTP_USER_AGENT) based on case-insensitive values. Sanic should do something similar for common headers (e.g. User-Agent and user-agent).

**Comment by imbolc** [comment]
I think [aiohttp.CIMultiDictProxy](https://multidict.readthedocs.io/en/stable/multidict.html#multidict.CIMultiDictProxy) should be efficient enough.

**Comment by seemethere** [comment]
closed by #162
