### ISSUE TITLE
response.file_stream of StringIO not working

### ISSUE THREAD

**Issue by raphaelauv** [channelcat/sanic#1262]
Hi , first thank for all your work on SANIC

I want a return a BIG "file" which is in reality a StringIO

but I get TypeError: expected str, bytes or os.PathLike object, not _io.StringIO

```
@app.route('/test')
async def test(request):
    strIO = StringIO()
    strIO.write('Hello from Dan Jacob and Stephane Wirtel !')
    strIO.seek(0)
    return await response.file_stream(strIO)
```

am I doing an error or StringIO is not compatible with SANIC ?

thank you

**Comment by raphaelauv** [comment]
Yes , could I propose a PR for that pls ?

**Comment by MyNameIsCosmo** [comment]
@raphaelauv - You should check out the [sanic.response.stream](https://sanic.readthedocs.io/en/latest/sanic/api_reference.html#sanic.response.stream) function.

**Comment by raphaelauv** [comment]
``
@app.route("/")
async def test(request):

    output = io.StringIO()
    output.write('First, line.\n')
    output.write('First, line.\n')
    output.write('First, line.\n')
    output.seek(0)

    async def sample_streaming_fn(response):
        while True:
            rst = output.readline()
            if not rst:
                break
            else:
                response.write(rst)

    return stream(sample_streaming_fn, content_type='text/csv')
``
Yes it work , sorry for that boring question
Thank you !

**Comment by shivammutreja** [comment]
For someone who came here after trying to return _io.BytesIO as a file response (i.e 1st argument to response.file) and getting an error saying - TypeError: expected str, bytes or os.PathLike object, not _io.BytesIO.

Just use response.raw(_io.BytesIO, headers={}) and it'll work. (Setting headers is optional, obviously)

**Comment by pmontepagano** [comment]
I can't get this working. I tried this:

```python
import io
import httpx
from sanic import Sanic
from sanic import response

app = Sanic("MyApp")

@app.get("/test")
async def myhandler(request):
    with httpx.stream("GET", "https://upload.wikimedia.org/wikipedia/en/6/68/Crescendo_example.ogg") as r:
        r.read()
        return response.raw(io.BytesIO(r.content), content_type=r.headers["content-type"])
```

I'm getting this error:

```
Traceback (most recent call last):
  File "handle_request", line 130, in handle_request
    __slots__ = (
            ^^^^^^
  File "/Users/pmontepagano/.pyenv/versions/3.11.6/envs/uber-cdn/lib/python3.11/site-packages/sanic/response/types.py", line 160, in send
    await self.stream.send(
  File "http1_response_header", line 10, in http1_response_header
    from asyncio import CancelledError, sleep
               ^^^^^^^^^
TypeError: object of type '_io.BytesIO' has no len()
```

**Comment by Tronic** [comment]
With BytesIO all your data is in RAM anyway, it is not streaming, so you might just as well use `.getbuffer()` like the the first handler below. If your data is large, you'll want to use streaming instead, an example with httpx given here. Note that with Sanic you'll want to call only async functions, and thus we use `httpx.AsyncClient`.

```python
from io import BytesIO
import httpx
import sanic

app = sanic.Sanic("bytesio")
proxy_url = "https://download.blender.org/peach/bigbuckbunny_movies/big_buck_bunny_1080p_h264.mov"

@app.get("/")
async def simple(request):
    """A simple response from data in RAM"""
    bio = BytesIO(b"Hello, world!\n")
    return sanic.raw(bio.getbuffer(), content_type="text/plain")

@app.route("/stream", methods=["HEAD", "GET"])
async def proxy_stream(request):
    """Streams a response from proxy_url"""
    async with (
        httpx.AsyncClient() as client,
        client.stream(request.method, proxy_url) as r,
    ):
        # Stream Sanic response using the headers we got from upstream
        response = await request.respond(status=r.status_code, headers=r.headers)
        # ... in small pieces so we don't use too much RAM
        async for data in r.aiter_bytes():
            await response.send(data)
```
