### ISSUE TITLE
Loop Overwritten in Server.Serve

### ISSUE THREAD

**Issue by MyNameIsCosmo** [channelcat/sanic#1271]
A loop passed to `sanic.server.serve` will be overwritten if `runasync=True`:

https://github.com/channelcat/sanic/blob/599834b0e1c41d934dce30b6393926635f72b78e/sanic/server.py#L543

The behavior for this should be:
```python
if not run_async and not loop:
    # create new event_loop after fork
    ...
```

**Comment by yunstanford** [comment]
In general, a `loop` cannot survive a fork or be shared across processes in any way. When multiple processes are being used, each process should create its own eventloop, which also implies that any objects which depend on the loop (such as aiohttp.ClientSession) must also be created in the child processes. We probably should not allow user pass in loop there.

**Comment by MyNameIsCosmo** [comment]
Ah, makes sense.

I'm looking into handling HTTP redirects, which is related to #1250 
The solution /may/ be to pass a custom loop to `serve`, but I only peeked into the rabbit hole.
Do you have any suggestions for #1250?

I'm going to close this, as it's not an issue.
