### ISSUE TITLE
Storage for shared data

### ISSUE THREAD

**Issue by imbolc** [channelcat/sanic#129]
Storing of shared data like db connection pool or jinja environment in global variables is not so good idea for well known reasons.

Aiohttp has a nice idea to make app and request as dict-like objects. That allows us to use these as containers for shared data. E.g. you can store db connection as `app['db']` during initialization and then use it in handlers as `request.app['db']`. Dict-interface makes clear distinction between framework data (witch available as attributes) and user data (as dict items). Why wouldn't we borrow this idea?

**Comment by atribecalledkwest** [comment]
This would be super useful, perhaps a simple app.shared/app.globals dict would good enough.
