### ISSUE TITLE
Sanic consider jwt token as files

### ISSUE THREAD

**Issue by Elune0syh** [channelcat/sanic#1291]
Hello, if i post a file with a jwt token , i cant get this jwt token from `request.form` but its in `request.files`. Its a bug ?

**Comment by sjsadowski** [comment]
To be expected. All files should be in request.files, as per https://sanic.readthedocs.io/en/latest/sanic/request_data.html

**Comment by Elune0syh** [comment]
Thanks for your apply
Its my fault
`jwt.encode({'some': 'payload'}, 'secret', algorithm='HS256')` get bytes not str
i put this `jwt.encode({'some': 'payload'}, 'secret', algorithm='HS256').decode()` in my post_data, it works ok
