### ISSUE TITLE
Latest PyPi version is still 0.7.0

### ISSUE THREAD

**Issue by TheGrandmother** [channelcat/sanic#1295]
The latest version on PyPi is still `0.7.0` and not `0.8.0` which is the latest tagged release here.
Is there a reason for this?

**Comment by seemethere** [comment]
Yes the upload from Travis is broken. Trying to work it out.

**Comment by vltr** [comment]
I would mark this issue as a duplicate of #1245 and continue from there, since the main reason why `0.8.0` isn't published on PyPi yet is described on that issue :wink:

**Comment by seemethere** [comment]
Closing, refer to #1245 instead
