### ISSUE TITLE
TDD support

### ISSUE THREAD

**Issue by Code-ReaQtor** [channelcat/sanic#130]
Been using TDD feature on [Flask](http://flask.pocoo.org/docs/0.11/testing/). Might be better if same thing will be added to this jewel.

**Comment by seemethere** [comment]
@Code-ReaQtor What features in particular are you looking for?

**Comment by Code-ReaQtor** [comment]
@seemethere 
More like Flask's, usable with python _unittest_ module: 
http://flask.pocoo.org/docs/0.11/testing/
https://github.com/mjhea0/flaskr-tdd

**Comment by dszmaj** [comment]
After wsgi compliant, it could be integrated with WebTest and exposing fixture for pytest and unittest

**Comment by r0fls** [comment]
This may be relevant: https://github.com/channelcat/sanic/pull/431

**Comment by seemethere** [comment]
Think I can close this with #431
