### ISSUE TITLE
Can you put 0.8.0 on pypi?

### ISSUE THREAD

**Issue by josephok** [channelcat/sanic#1306]
Since 0.7.0 has some bugs like access_logger incorrectly output request ip and port, which fixed in https://github.com/channelcat/sanic/commit/4f8633375d8a9fdcbc90f02e4204535af4cc6fd1#diff-bd84a6e523017a7f3d6bd72ee689dce2

**Comment by MyNameIsCosmo** [comment]
Please look at previous issues before posting:
#1295
#1245

**Comment by josephok** [comment]
@MyNameIsCosmo yep, I just saw it. Thanks.
But it seems no updates on this.

**Comment by MyNameIsCosmo** [comment]
Yes, there are no updates on the issue, so you can bump #1245.
You can skim through the thread to see the current issue: channelcat's pypi account is not email-verified, so the team cannot upload to pypi yet.

**Comment by josephok** [comment]
Thanks.
