### ISSUE TITLE
Design question: why is `Request` a subclass of `dict`?

### ISSUE THREAD

**Issue by vltr** [channelcat/sanic#1309]
Hello. I was just wondering: why is the `Request` class a subclass of `dict`? Would it be to enable developers do "store" information into a instance like `request["name"]`?

Thanks in advance!

**Comment by seemethere** [comment]
Yes, here is the original PR for some context: https://github.com/channelcat/sanic/pull/163

Plus the original issue to this https://github.com/channelcat/sanic/issues/129

**Comment by vltr** [comment]
Thanks, @seemethere . The "impact" of using `dict` is almost neglectable - some rudimentary benchmarks on my old AMD workstation shows a 0.13 sec diff in 1mi iterations. Implementing basic `dict` interface (`__delitem__`, `__getitem__` and `__setitem__`) seems to show a diff of 0.09sec in 1mi iterations, that's the main reason I brought this up (again, I know, it's neglectable :wink:)

**Comment by gatopeich** [comment]
This is confusing for my exception serialization code which recognizes it wrongly as an empty dict.
If it is not really a dict, then it should not be sub-classed as one.
A solution based on `__getattr__` would have lesser impact and allow for nicer-looking extension code.
