### ISSUE TITLE
high CPU usage with upload

### ISSUE THREAD

**Issue by devvit** [channelcat/sanic#143]
CPU usage in uploading:

flask + gevent: 5%-20%
nodejs: 5%-20%
sanic: 20%-90%

anybody noticed this?

**Comment by webtic** [comment]
While I haven't compared it to other frameworks I did notice a heavy CPU load on upload with sanic..

**Comment by seemethere** [comment]
Can't really say I can reproduce this, closing for now. Will reopen if necessary.
