### ISSUE TITLE
Csrf protection

### ISSUE THREAD

**Issue by anthon-alindada** [channelcat/sanic#1450]
Hi can someone please tell me how i can implement csrf token in sanic. I want to create an application using sanic and reactjs. Using sanic-wtf how can i pass the csrf token in react without passing the form in the template. And if someone can give me an example on how to do csrf token in sanic using ajax request that would be great. Thank you in advance.

**Comment by ahopkins** [comment]
It really depends how you are building your application. One thing you might want to look at is this package here: https://github.com/pyx/sanic-wtf.

For a more detailed discussion, and if you need additional help, please [post on the community forums](https://community.sanicframework.org/). ;-)
