### ISSUE TITLE
http request data may be chunked

### ISSUE THREAD

**Issue by jiajunhuang** [channelcat/sanic#164]
hi, I'm reading source code of `sanic`, but I found a bug here:

https://github.com/channelcat/sanic/blob/master/sanic/server.py#L84

In HTTP/1.1, data can be transformed in `buffer` mode or `stream` mode. so, what if the data is incomplete(it's just a chunk of user contents, I mean)? so we have to parse the header outself,
and save all the data, then feed it to `httptools.HttpRequestParser`

```python
def data_received(self, data):
```

also, this function may be called many times: https://docs.python.org/3/library/asyncio-protocol.html#asyncio.Protocol.data_received

My English is poor, please tell me if I didn't say it clearly(also I apologize for my poor English... :joy:).

**Comment by guyskk** [comment]
Do you mean:

1. `Transfer-Encoding: chunked`, eg:
```
HTTP/1.1 200 OK
Content-Type: text/plain
Transfer-Encoding: chunked

25
This is the data in the first chunk

1C
and this is the second one

3
con

8
sequence

0
```

2. multipart/form-data, eg:  `Content-Type:multipart/form-data; boundary=----WebKitFormBoundaryrGKCBY7qhFd3TrwA`
```
POST http://www.example.com HTTP/1.1
Content-Type:multipart/form-data; boundary=----WebKitFormBoundaryrGKCBY7qhFd3TrwA

------WebKitFormBoundaryrGKCBY7qhFd3TrwA
Content-Disposition: form-data; name="text"

title
------WebKitFormBoundaryrGKCBY7qhFd3TrwA
Content-Disposition: form-data; name="file"; filename="chrome.png"
Content-Type: image/png

PNG ... content of chrome.png ...
------WebKitFormBoundaryrGKCBY7qhFd3TrwA--
```

1 is client's business, 2 is https://github.com/channelcat/sanic/blob/master/sanic/request.py#L86

I didn't found any articles about `buffer` mode or `stream` mode, can you provide more details?

**Comment by jiajunhuang** [comment]
Yes,  the first case is what I mean. thanks for your reply.
