### ISSUE TITLE
Class based views not available on Pip

### ISSUE THREAD

**Issue by x10an14** [channelcat/sanic#174]
Hiya,

Used the below command to install Sanic on my machine, with version 0.1.7 as result.
`venv/bin/pip install sanic`

The `from sanic.views import HTTPMethodView` fails with the below error message:
```python
Traceback (most recent call last):
  File "webapp.py", line 3, in <module>
    from src import app
  File "/home/x10an14/Documents/git_projs/overtime_calculator/src/__init__.py", line 2, in <module>
    from sanic.views import HTTPMethodView
ImportError: No module named 'sanic.views'
```

Now, [this](https://github.com/channelcat/sanic/pull/167) update into the `master` branch did not change the version number, was that perhaps necessary for pypi to pick up the update?

**Comment by seemethere** [comment]
Yes you're right. I'll do a formal release later tonight with @channelcat's permission

**Comment by x10an14** [comment]
(y) =) 

+1 for quick response...! ~5 mins!

**Comment by seemethere** [comment]
Updated with https://github.com/channelcat/sanic/pull/177
