### ISSUE TITLE
Class Based definitions don't work

### ISSUE THREAD

**Issue by Typhon66** [channelcat/sanic#179]
In https://github.com/channelcat/sanic/blob/master/docs/class_based_views.md it describes how you would use a class based view. But doing it does not seem to work. I end up getting an "Object is not callable" exception:

Error: 'MyClass' object is not callable
Exception: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/sanic/sanic.py", line 192, in handle_request
    response = handler(request, *args, **kwargs)
TypeError: 'MyClass' object is not callable

**Comment by Typhon66** [comment]
Hold that thought, i may have been doing it wrong

**Comment by Derrreks** [comment]
Share the code?

**Comment by wojunnihou** [comment]
你多半是add_route的时候没有实例话

**Comment by wojunnihou** [comment]
bp.add_router(MyClass())

**Comment by seemethere** [comment]
@AntonDnepr care to comment?

**Comment by AntonDnepr** [comment]
@Typhon66 do you inherit from HTTPMethodView?
`Error: 'MyClass' object is not callable` could mean that your class do not have __call__ method, which is defined in HTTPMethodView.
In any case, I would like to have the whole code snippet it is hard to guess what goes wrong without it.

**Comment by Typhon66** [comment]
Was doing it wrong, missed the import.
