### ISSUE TITLE
json() method of request object fails too easily

### ISSUE THREAD

**Issue by r0fls** [channelcat/sanic#192]
A simple post request from curl doesn't appear to work. To reproduce, save this file:

```python
from sanic import Sanic
from sanic.response import text

app = Sanic()

@app.route("/")
async def test(request):
        print(request.body)
        data = request.json()
        return text("Hello, {}".format(data["name"]))

app.run(host="0.0.0.0", port=8000)
```

Then both of these fail (one spits an error and the other fails silently):

```bash
$ curl -d '{"name": "raphael"}' localhost:8000
An error occurred while generating the request 
$ curl -d "{'name': 'raphael'}" localhost:8000
An error occurred while generating the request
```

**Comment by r0fls** [comment]
Derp, didn't import text :( closing this issue. We could really have better errors though...

**Comment by r0fls** [comment]
Actually i still get the issue after importing `text`. Reopening this.

**Comment by seemethere** [comment]
Looking into right now

**Comment by r0fls** [comment]
Thank you. I think the issue is that json is a property not a method, and the error wasn't making things obvioius.

**Comment by r0fls** [comment]
So we actually can close this again :) my bad. I'm used to that being a method from some other framework.

**Comment by seemethere** [comment]
@r0fls Just realized that too once I put the `debug=True` on in the app xD

**Comment by r0fls** [comment]
@seemethere ah, I didn't realize you could set `debug=True`. This makes things easier 💥  thanks
