### ISSUE TITLE
Convert documentation to Sphinx?

### ISSUE THREAD

**Issue by sirex** [channelcat/sanic#205]
Having Sphinx documentation you will be able to upload docs to https://readthedocs.org/

**Comment by seemethere** [comment]
I'm a fan :+1:

**Comment by wsbmilk** [comment]
+10086, alternatively gitbook

**Comment by kdelwat** [comment]
I'm willing to implement this in a PR if there's a consensus 🎉

**Comment by wilcoschoneveld** [comment]
This issue is resolved and can be closed, publishing discussed in #321.
