### ISSUE TITLE
Streaming support

### ISSUE THREAD

**Issue by alexsv** [channelcat/sanic#208]
Hi,
I'm impressed by the framework, but want to check one thing:
I want to read big file and send a portions of it like 1KB by 1 second

So I expect, that HTTPResponse would accept some iterator.
Any ideas about this?

**Comment by seemethere** [comment]
You could implement a custom protocol based on the base sanic HTTPProtocol.

Closed with #209

**Comment by alexsv** [comment]
Am I right custom protocol is used for the whole application and I can't make one endpoint streaming based?

**Comment by seemethere** [comment]
@alexsv that would be correct. But I would think that there could be a better implementation out there that would not require changing the entire protocol just to enable it for one endpoint.

**Comment by alexsv** [comment]
possible on blueprint level?

**Comment by seemethere** [comment]
Possibly but it would need to be investigated.

**Comment by 38elements** [comment]
This is related #697.
