### ISSUE TITLE
Invalid request data, connection closed (the on_headers_complete callback failed)

### ISSUE THREAD

**Issue by Izacht13** [channelcat/sanic#219]
An issue I cannot solve, this happens even on the example code now, I have no clue what is causing it.

My code works one moment, and then the next, even without any changes the the script, will start persistently logging this error.

**Comment by luizfb** [comment]
Could you build a minimal example that demonstrates this issue? Or at least point to which example code this is happening on?

**Comment by Izacht13** [comment]
All of the example code, and my code. Every sanic code is doing this. I've tried restarting my PC, Chrome, Firefox, it doesn't make any sense!

It gets weirder though, because I got so fed up with trying to solve this issue, that I switched back to Bottle. After a day or so, I switched it back to sanic again, and for some reason it started working again. Only for about a day though, then it went back to the error above.

**Comment by Izacht13** [comment]
Hey whoa! I just updated sanic to 0.1.9 and its working now. I have no clue what has changed, but I hope it doesn't happen again.

If it does happen again, should I open a new issue? What kinda of information would you guys need to better solve the cause if such issue would pop up again?

**Comment by seemethere** [comment]
It must have something to do with how errors were handled before. We were ungracefully handling some errors. I'll close this issue for now and we will reopen it if the error pops back up.
