### ISSUE TITLE
Contrib apps

### ISSUE THREAD

**Issue by dszmaj** [channelcat/sanic#257]
What about making sanic more of a fully featured web framework and divide it from the server part in contrib catalogue as it definitely would affect performance?

I think about built in support for templates like Jinja2, maybe some implementation of asyncpg (this could be fast) etc

**Comment by seanpar203** [comment]
I agree with extending Sanic to support commonly used libraries, template engines etc.. But I don't think implementing something like `asyncpg` specifically for Sanic is beneficial enough. 

The database access layer isn't a bottleneck to Sanic,  SQLAlchemy is able to pump out [100,000 inserts](http://docs.sqlalchemy.org/en/latest/faq/performance.html) in less than half of a second using `core`.  Sanic can handle 33K/S meaning that SQLAlchemy can do more than 200k inserts per 33K requests.

Complex queries take longer than others but that's still 6 DB queries per request.

**Comment by seemethere** [comment]
Gonna close this, we're not really looking into integrating a template engine or a database engine into sanic core.
