### ISSUE TITLE
SIGABRT?

### ISSUE THREAD

**Issue by jackfischer** [channelcat/sanic#258]
Sanic has been intermittently crashing for me with a SIGABRT; I have not been able to pin down what is causing this and unfortunately all I have is Docker's exit code. Has this happened to anyone else? I will keep investigating and try to get more in depth information.

**Comment by gpip** [comment]
Any chance this is similar to https://github.com/channelcat/sanic/issues/307#issuecomment-273191433? I get it ~every time when running wrk against sanic + asyncpgsa.

**Comment by jackfischer** [comment]
Yes, appears related although I'll look at it more carefully. I'm using
aiomysq.

**Comment by jackfischer** [comment]
Duplicate of #307
