### ISSUE TITLE
Lack of a mutable request-context object makes extension building difficult

### ISSUE THREAD

**Issue by subyraman** [channelcat/sanic#283]
I'm currently working on extension that adds server-backed sessions to Sanic. I'm running into the issue that because the `request` object is immutable, adding convenient extensions is tricky.

For example, let's say I have a Redis connection pool and I'd like to just automatically hook it up to the request object before each request, so I don't have to instantiate it in every view. 

I'd like to do something like this:

```python
import asyncio_redis

from sanic import Sanic
from sanic.response import text
from sanic_session import RedisSessionInterface


app = Sanic()


class Redis:
    """
    A simple wrapper class that allows you to share a connection
    pool across your application.
    """
    _pool = None

    async def get_redis_pool(self):
        if not self._pool:
            self._pool = await asyncio_redis.Pool.create(
                host='localhost', port=6379, poolsize=10
            )

        return self._pool


redis = Redis()


@app.middleware('request')
async def add_redis_to_request(request):
    request.redis_connection = await redis.get_redis_pool()


@app.route("/")
async def test(request):
    foo = await request.redis_connection.get('foo')
    return foo

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=8000, debug=True)
```

Of course, I cannot, because the `request` object is immutable and won't let me add the `redis_connection` onto it. The Flask request object is immutable as well, but Flask provides the convenient `g` object for situations like this.

Are there any thoughts on adding a mutable request-context object? It'd be really helpful, especially since I'm interested in developing on this.

**Comment by subyraman** [comment]
From a code perspective, this would only require initializing an empty `g` class in `sanic.handle_request`, and passing `g` into the `middleware` and `handler` methods. I'm happy to put out a pull request but it would be a minor API change, would like any thoughts.

**Comment by seemethere** [comment]
You should be able to use the request as a dictionary object to store global things as done in #163
