### ISSUE TITLE
Logger shouldn't be initialized until run

### ISSUE THREAD

**Issue by cdunklau** [channelcat/sanic#287]
This is kind of a drive-by bug report, so if I've misunderstood something, please disregard.

I noticed this worrisome thing while perusing the code:

https://github.com/channelcat/sanic/blob/4f832ac9afdba11f276b42ccbfbf7aa83c60dc47/sanic/sanic.py#L25-L29

I would think logging really shouldn't be configured until at least `Sanic.run` is called, to provide users the ability to configure it after instantiating but before running it.

**Comment by tuukkamustonen** [comment]
Why does it even have `logger` argument? It is not used for anything except as boolean for checking whether or not to run `logging.basicConfig()`. To me it seems this block and argument should be just removed. What's the rationale?

**Comment by r0fls** [comment]
Well, for the history: logging was previously initialized in that location in the same way, but without the option to disable it, and some users were confused as to how they should customize or override it.

**Comment by r0fls** [comment]
@cdunklau regarding your concern, this is currently possible:

```
from sanic import Sanic
from sanic.response import text
import json
import logging


# Set logger to override default basicConfig
sanic = Sanic(logger=True)
@sanic.route("/")
def test(request):
    return text("hey")

logging_format = "[%(asctime)s] %(process)d-%(levelname)s "
logging_format += "%(module)s::%(funcName)s():l%(lineno)d: "
logging_format += "%(message)s"

logging.basicConfig(
    format=logging_format,
    level=logging.DEBUG
)
log = logging.getLogger()

sanic.run(host="0.0.0.0", port=8000)
```

**Comment by r0fls** [comment]
I do agree that configuring `logging` in the `run` and `serve_multiple` functions probably makes more sense though. There I don't find the need for the boolean option to disable it, which is indeed silly.

**Comment by cdunklau** [comment]
Another thing I noticed...
https://github.com/channelcat/sanic/blob/4f832ac9afdba11f276b42ccbfbf7aa83c60dc47/sanic/sanic.py#L156-L157

That should probably be `warnings.warn(thatmessage, DeprecationWarning)`

**Comment by r0fls** [comment]
Closing per #308
