### ISSUE TITLE
Allow defaults in URL params

### ISSUE THREAD

**Issue by r0fls** [channelcat/sanic#298]
Would it make sense to allow using a default for URL parameters? For example:

```python
from sanic import Sanic
from sanic.response import text

app = Sanic()

@app.route("/hello/<name>", defaults={"name": "john"})
async def hello(request, name):
    return text("Hello, {}".format(name))

app.run(host="0.0.0.0", port=8000)
```

```
$ curl localhost:8000/hello
Hello, john
```

**Comment by seemethere** [comment]
I'm not a fan. I can't really think of a use case of it. Default parameters make sense but obfuscating a route with a default route seems confusing to me.

**Comment by r0fls** [comment]
OK ya, I think making a separate route for `/hello` with the default there is probably better.
