### ISSUE TITLE
Travis CI?

### ISSUE THREAD

**Issue by seemethere** [channelcat/sanic#3]
Maybe a travis CI can be setup to automatically run tests on PR (including flake8 plz) and to also automate the submittal to PyPI.

**Comment by channelcat** [comment]
I haven't used travis/flake8/pypi before, but I'll take a look at adding them to the pipeline :D.

**Comment by jesuejunior** [comment]
@channelcat  Would you mind if I taking this issue and help the project ? I could help you to configure on Travis-CI.org, What do you think about? It's very important to have.

**Comment by channelcat** [comment]
@jesuejunior Sure!  I just hooked up the project to travis-ci on their web site, so it should be ready :).

**Comment by channelcat** [comment]
closing this now that we run flake8, py.test, and push to pypi automatically :)
