### ISSUE TITLE
Sanic 0.2.0 changes to  type of request.args['xxx'] 

### ISSUE THREAD

**Issue by avilior** [channelcat/sanic#303]
In sanic 0.2.0 type of request.args['xxx'] is now str it used to be list.  Is that the intention?

Also if I send two instances of 'xxx' i still get a str.  If more then one instance of the same query parameter are sent, how will they be accessed in 0.2.0?

**Comment by seemethere** [comment]
`request.args.getlist(<key>)`

https://github.com/channelcat/sanic/blob/master/sanic/request.py#L35
