### ISSUE TITLE
object is not callable using class based view

### ISSUE THREAD

**Issue by njordr** [channelcat/sanic#322]
Hi.

I've got the error: object is not callable using class based view.

I found this issue: https://github.com/channelcat/sanic/issues/179 but it's not my case, I imported it.

Code (main file):
```
from spyrest.blueprints import spy

spy.bp_spy.add_route(uri='{}/binders/<smartcabinet_id>'.format(urls['spy']), handler=spy.Binders(db=mongodb))

# Add spy blueprint
app.blueprint(spy.bp_spy)
```

spyrest/bluprints.py
```
from sanic.views import HTTPMethodView

bp_spy = Blueprint('spy')

class Binders(HTTPMethodView):
    def __init__(self, db:AsyncIOMotorClient):
        self._db = db

    async def put(self, request: request, smartcabinet_id: str) -> json:
        json_body = request.json

        if 'data' not in json_body:
            logger.info('No data field in json, return InvalidUsage')
            return InvalidUsage

        update_res = binders.update_binder(db=self._db, binder_doc=json_body['data'], smartcabinet_id=smartcabinet_id)

        if not update_res:
            return ServerError
        else:
            return HTTPResponse(status=204)
```

When I try it with
```
curl -X POST -H "Content-Type: application/x-www-form-urlencoded" -H "Cache-Control: no-cache" -H "Postman-Token: f7cb2523-048c-5601-c4f0-93f64a0e7876" -d '{
    "search": {
        "device_id": "smartcabinet_1403_10",
    }
}' "http://localhost:8001/api/v1/spy/logs"
```

it gives me a 500 status code and log this:
2017-01-20 10:55:22,481 ERROR spyrest.utils.sanic_errors(11) | 'Binders' object is not callable

Last version of sanic (updated this morning, with the previous, no problem
Python 3.6.0

**Comment by go2sh** [comment]
`HTTPMethodView` is not designed the way you use it. You have to call `as_view()` on the class and can't pass an instance. But you can use the new (not yet released) `CompositionView` clas, which works like your design (pass a instance).

**Comment by njordr** [comment]
How to pass the db instance as a parameter (HTTPMethodView)?

**Comment by go2sh** [comment]
It's not possible. Have a look at the `CompositionView` class. There you can create a constructor and it implements the callable you need.

**Comment by njordr** [comment]
Thanks. I'll wait to upgrade until CompositionView will be released
