### ISSUE TITLE
During handling of the above exception, another exception occurred

### ISSUE THREAD

**Issue by robintiwari** [channelcat/sanic#324]
In the examples/exception_monitoring.py, when i try to run the app and hit the default route, it prints out the exception and then it calls "return super.default(self, request, exception)", it returns with the following exception:

AttributeError: type object 'super' has no attribute 'default'

looks like in the exceptions.py, this line is the culprit (i could be wrong):

`handler = self.handlers.get(type(exception), self.default)
`
 since __init__ does not have that attribute defined.  I am running python 3.6

**Comment by seemethere** [comment]
Oh that must be a typo, I think it should actually be `super().default(self, request, exception)`

**Comment by robintiwari** [comment]
i think it should be 

`return super().default(request, exception)`

without the "self"
