### ISSUE TITLE
no handy helper functions url_for

### ISSUE THREAD

**Issue by lixxu** [channelcat/sanic#336]
is there will be `url_for` in sanic likes `flask.url_for` in the future? I think it's not a good idea to hard code the url when redirect in code and make url in template.
And, it's better if `flash` and `get_flashed_messages` provided.

**Comment by Tim-Erwin** [comment]
+1 for `url_for` or any equivalent. I need to construct a location header for a newly created resource and don't want the view function to actually know the url.

**Comment by robintiwari** [comment]
IMHO can you not create an extensions for such helpers? That way Sanic core can be lean. Some few extensions examples are listed here for reference: https://github.com/channelcat/sanic/blob/master/docs/extensions.md

**Comment by JordanP** [comment]
``url_for`` is kinda basic, it would benefit to most (all ?) if it were in Sanic core.

**Comment by subyraman** [comment]
I'll look at adding in a `url_for` method this weekend unless there's thoughts otherwise.

Flashing is out of scope, since as of now there is no templating/session system in the core.
