### ISSUE TITLE
error_handler's debug flag always set to True in run

### ISSUE THREAD

**Issue by mike-hart** [channelcat/sanic#340]
https://github.com/channelcat/sanic/blob/28396c8620839ebfe11c61916a800da4e82f27ee/sanic/sanic.py#L304

In order to not need to do something like:

```python
eh = MyErrorHandler()
app = sanic.Sanic(error_handler=eh)
eh.sanic = app
```

So that I could alter behaviour of the handler based on the debug flag I noticed that run sets the error-handler's debug flag, but only ever to True. That line should probably be:

```python
self.error_handler.debug = debug
```

So that then I could write:
```python
app = sanic.Sanic(error_handler=MyErrorHandler())
```

And that the default error handler `exceptions.Handler` wouldn't need to be passed the app instance at instantiation.

**Comment by seemethere** [comment]
Closed with #341
