### ISSUE TITLE
'secure' and 'httponly' are encoded regardless what the values are

### ISSUE THREAD

**Issue by hitigon** [channelcat/sanic#345]
As testing Sanic cookie setting with following from docs:

```
@app.route("/cookie")
async def test(request):
    response = text("There's a cookie up in this response")
    response.cookies['test'] = 'It worked!'
    response.cookies['test']['domain'] = '.gotta-go-fast.com'
    response.cookies['test']['httponly'] = True
    return response
```

I found when I set httponly value to False (by using `response.cookies['test']['httponly'] = False`)

Sanic still send a response to set the cookie with httponly flag

By looking up the source code:
https://github.com/channelcat/sanic/blob/master/sanic/cookies.py#L110

it only checks if the key (secure or httponly) exists, instead of checking the value. So, by setting the value with False, it actually still enables the flag (as opposite what we intend to do)

**Comment by r0fls** [comment]
Thanks for reporting that! Closing this per #347
