### ISSUE TITLE
RuntimeWarning: coroutine 'file' was never awaited

### ISSUE THREAD

**Issue by behrtam** [channelcat/sanic#355]
I'm trying to respond a request with a file, like this ...

```python
from sanic import Sanic
from sanic.response import file, json

app = Sanic(__name__)

@app.route("/files/<name>/")
async def file_handler(request, name):
    print(">>", name)
    return file(f'./{name}.txt')

app.run(host="0.0.0.0", port=8000)
```

A request results in the following error:
```
ERROR: Writing response failed, connection closed 'coroutine' object has no attribute 'output'
/Users/tmo/Envs/squirrel/lib/python3.6/site-packages/sanic/server.py:300: RuntimeWarning: coroutine 'file' was never awaited
  loop.run_forever()
```

Most likely this is not a Sanic issue. I've never worked with async/await, so probably I'm doing something wrong.

**Comment by amsb** [comment]
Coroutines (async functions) must be await-ed: `return await file(f'./{name}.txt')`. The file function defined in `sanic.response` is a coroutine. See https://docs.python.org/3/library/asyncio-task.html

**Comment by behrtam** [comment]
Thanks, for the quick response!!
