### ISSUE TITLE
docs about default http methods

### ISSUE THREAD

**Issue by behrtam** [channelcat/sanic#373]
https://github.com/channelcat/sanic/blob/master/docs/sanic/routing.md#http-request-types
> By default, a route defined on a URL will be used for all requests to that URL. However, the @app.route decorator accepts an optional parameter, methods, which restricts the handler function to the HTTP methods in the given list.

The documentation about request methods still reads to me as if the default is that all methods are accepted. With #316 this default was changed, so that only GET is the default.

**Comment by r0fls** [comment]
Closing this per https://github.com/channelcat/sanic/pull/377
