### ISSUE TITLE
Session/User Middleware API

### ISSUE THREAD

**Issue by jbcurtin** [channelcat/sanic#375]
I've taken the time to create a session middleware for myself. Problem is, I have to attach the 'session' object to `request.args` or `request.forms` or `request['session']` because those are mutable. I would like the freedom of adding a `session` and `user` object much like they have in django.

Would you accept a pull request that accepts a `write once` datatype[0] for the respective attributes? For example, `request.session` or `request.user` could be populated, but not overwritten for each request object.

This approach intends to make room for the problem to be solved while allowing the opinions to flow freely. 

[0] https://en.wikipedia.org/wiki/Const_(computer_programming)

**Comment by seemethere** [comment]
Have you tried out: https://github.com/subyraman/sanic_session?

**Comment by seemethere** [comment]
Closing per @subyraman's extension. Will reopen if necessary.
