### ISSUE TITLE
Exception Handler Does Account for Inheritance

### ISSUE THREAD

**Issue by bharris47** [channelcat/sanic#388]
Seems like when searching for an exception handler at https://github.com/channelcat/sanic/blob/master/sanic/exceptions.py#L173, the dictionary lookup is only for that specific exception type. 

This is contradictory to the documentation saying [You can pass SanicException to catch them all!](http://sanic.readthedocs.io/en/latest/sanic/exceptions.html#handling-exceptions).

Is there any other way to achieve the desired catch-all behavior as-is?

**Comment by seemethere** [comment]
Should be fixed by #379
