### ISSUE TITLE
Can't install on Windows

### ISSUE THREAD

**Issue by Armored-Dragon** [channelcat/sanic#392]
I can't install Sanic on Windows, because of the forced `uvloop` dependency not working on Windows. It raises `RuntimeError: uvloop does not support Windows at the moment` and aborts the installation. It should still be possible to use Sanic without the uvloop speedup.

**Comment by luizberti** [comment]
If I'm not mistaken the `httptools` dependency also doesn't work on Windows

**Comment by Armored-Dragon** [comment]
`httptools` installs and works fine for me on Windows. They have a binary wheel.

**Comment by Benozo** [comment]
Try the Windows Subsystem . It's based of Ubuntu 14 kernel . Then Google how to update it to Ubuntu 16 should be straight forward. That's how I'm using Sanic with Uvloop on Windows 10 .https://msdn.microsoft.com/en-us/commandline/wsl/install_guide

**Comment by seemethere** [comment]
Yeah we don't have any control over whether or not uvloop supports windows. 

This relates to #17. I guess we should make that clearer in the README

**Comment by espositofulvio** [comment]
There is actually a way to install sanic on windows without uvloop. I usually set my requirements.txt file to 

```
# install dependencies in setup.py
-e .
```

to get the dependencies in setup.py. I managed to get it work like this:

```
# install dependencies in setup.py
-e git+https://github.com/channelcat/sanic@0.5.4#egg=sanic
-e .
```

and doing on the command line:
```
set SANIC_NO_UVLOOP=1
pip install -r requirements.txt
```

this will clone sanic from github at tag 0.5.4 and will install without the uvloop dependency and then all the other dependencies from setup.py. Obviously you can specify your dependencies directly in requirements.txt, just write the sanic bit as above
I'm not sure you can install it from the wheel without the uvloop dependency though.

**Comment by wissemnano** [comment]
try to install Visual studio build tools  then install sanic it's work for me
