### ISSUE TITLE
Does Class-Based Views support async?

### ISSUE THREAD

**Issue by ikalnytskyi** [channelcat/sanic#414]
I took a look at snippet in the docs

```python
class NameView(HTTPMethodView):

  def get(self, request, name):
    return text('Hello {}'.format(name))

app.add_route(NameView.as_view(), '/<name>')
```

and I wonder, does it support async protocol? I tried to figure it out from the code and I came upon [these lines](https://github.com/channelcat/sanic/blob/master/sanic/sanic.py#L334-L337):

```python
response = handler(request, *args, **kwargs)
if isawaitable(response):
    response = await response
```

So please check me if I got it correctly:

* Does it mean that any Sanic handler (including Class-Based view) may return both awaitable and not awaitable objects?
* In case of awaitable object, they will be awaited.
* In case of non-awautable, they will be passed down.
* Any Sanic handler itself may be marked as `async` or not.

**Comment by seemethere** [comment]
hmmm, that is a good question. I'm assuming yes but it'd be a good question for @AntonDnepr the original writer of the `HTTPMethodView`

**Comment by AntonDnepr** [comment]
Actually, I didn't see a problem to use async syntax with Class based views. (it's my bad that I didn't include examples with async in pr, sorry)
And you're right about your statements.

I think I'd better update examples&tests with both async and not async examples just to not confuse people in future.

**Comment by seemethere** [comment]
Cool, so I'd guess the answer is a yes!
