### ISSUE TITLE
Prioritizing TODOs

### ISSUE THREAD

**Issue by abhishek7** [channelcat/sanic#42]
Noticed a fair amount of TODOs in the code, would be great to prioritize what needs to be done. Maybe ranking it in terms of difficulty as well for contributors who are at the beginner level all the way to expert?

**Comment by channelcat** [comment]
Sure :).  Should I start adding them as issues, or is there a better way to organize?

**Comment by eseglem** [comment]
I think adding them to the issues, and then having some sort of priorities tags (or even how hard they might be) within the issues, would be great. Could clear the TODOs out of the actual code. I haven't had time to look into any of them in the code yet, but it would definitely make the project more accessible.

**Comment by abhishek7** [comment]
Yes exactly what @eseglem said! How about something fairly simple like this:

1.  Beginner
2. Intermediate
3. Advanced

Maybe then we can have a separate set of labels to denote urgency such as:

- Urgent
- Necessary
- Nice to Have

Feel free to edit/modify. Not too familiar with labels yet on GitHub but will update as I find out more.

**Comment by channelcat** [comment]
Looks good to me :).   I'll start tagging current issues, and try to get to TODOs next.
