### ISSUE TITLE
Sanic logs every exception by default

### ISSUE THREAD

**Issue by jasonab** [channelcat/sanic#420]
As of PR #306, the default() method in the ErrorHandler logs all exceptions that come its way. Unfortunately, this overrides any logging or non-logging behavior a subclass of ErrorHandler might desire, since calling super.default() is generally accepted to return a message to the user.

Generally, this means that any exception that occurs in the course of a request (e.g. 405) is logged to disk, and is a source of a potential alert for a sysadmin.

If Sanic wants to log everything by default, I'd have to suggest breaking out the log statement into a different method, so it could be overridden independently. Having to set an exception handler for each possible status code is unreasonable for any system.

**Comment by r0fls** [comment]
@jasonab does it make sense to use the log handler here, in debug mode?
https://github.com/channelcat/sanic/pull/422/files#diff-bd84a6e523017a7f3d6bd72ee689dce2R352

Or, do you think that should use the overridable method as well? Also, can you just override the logging to avoid the need for using a method here?

**Comment by jasonab** [comment]
The log method looks good to me, since it allows me to test the exception, and only log it if it's a critical problem. I don't think that overriding the logging settings works, because Sanic logs all exceptions at the same level.

**Comment by r0fls** [comment]
closing per #422
