### ISSUE TITLE
What is the best way to use dbconnection across the model & api layers ?

### ISSUE THREAD

**Issue by pwalimbe** [channelcat/sanic#426]
I am using the Motor asynch library and I followed upon the examples page and created the db conn obj. This is follow up from #152 and I used the after_server_start to create the obj. However for me to have the obj available in my model classes during processing I could not use the global variable method as described in the documentation. So what I did instead is created another middleware
`@app.middleware('request')
def add_dbc(request):
    args = request.args
    args['dbc'] = app.dbc`
to have that added in the args of each request object. It has worked since in the model I pass this object from the request when I receive it. But I am not very happy with the fix. Is there a better way to have app variables available for request object?

**Comment by subyraman** [comment]
There's a PR currently open that would expose the `app` object in each request. I'd like to see it get in for this type of situation. https://github.com/channelcat/sanic/pull/244

**Comment by lixxu** [comment]
I do it like this:
```python
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import asyncio
from sanic import Sanic
from motor.motor_asyncio import AsyncIOMotorClient

app = Sanic(__name__)
# app.config.from_object(...) or something else

async def after_start(*args, **kwargs):
    client = AsyncIOMotorClient(app.config.MONGODB_URI, io_loop=asyncio.get_event_loop())
    app.motor_client = client
    app.motor_db = client.get_default_database()


async def after_stop(*args, **kwargs):
    app.motor_client.close()

run_kwargs = dict(after_stop=after_stop, after_start=after_start)

if __name__ == '__main__':
    app.run(**run_kwargs)
```

Then use `app.motor_db[collection_name]` at other place.

**Comment by pwalimbe** [comment]
The above solution does not work since when I am handling requests in other code layers, I do not have access to the app variable. But as pointed out by @subyraman the solution provided in that PR will solve the problem. I will close the issue as the solution seems to be on the way!

**Comment by Gowtham95india** [comment]
@pwalimbe I'm initialising it in before start. Working now with version 0.4.0

**Comment by seemethere** [comment]
Woop! And with the advent of #476 you are guaranteed to get the currently running app in each of the route handlers! 😄

**Comment by Gowtham95india** [comment]
Oh.. ! Awesome. 👍 

Still I feel better to do.. 

```python
app.producer.send('topic', message)
```
instead of 

```python
request.app.producer.send('topic', message)
```

It gives me the feel of doing something with app, instead of request. :-p
