### ISSUE TITLE
Route parameters with dots or other punctuation not working

### ISSUE THREAD

**Issue by wooptoo** [channelcat/sanic#44]
Hi, Thanks for the great work on Sanic!
I just started using it for a small project of mine. One bug which i ran into was its inability to parse parameters with punctuation in them, like so:

    @app.route('/entries/domain/<domain>')
    async def get_entries_for_domain(request, domain):    
    ...
    
    GET http://0.0.0.0:8000/entries/domain/kernel.org
    
    Error: Requested URL /entries/domain/kernel.org not found

But at the same time fetching the `/entries/domain/kernel_org` endpoint works.
Any way to work around this?

**Comment by channelcat** [comment]
Fix by mindflayer pushed, closing issue :)

**Comment by wooptoo** [comment]
Thanks guys, that's awesome!
