### ISSUE TITLE
Sanic have any interface to send email asynchronously?

### ISSUE THREAD

**Issue by mrhdias** [channelcat/sanic#445]
How should I use the smtplib library or other to send email's asynchronously with sanic?

**Comment by subyraman** [comment]
Looks like there's an async implementation of `smtplib` that you can use send emails asynchronously: https://github.com/cole/aiosmtplib

**Comment by neo1218** [comment]
you can use [celery](http://www.celeryproject.org/), a task queue.
something like this in flask:

```python
# a celery task: send async email
@celery.task(default_retry_delay=30)
def send_async_email(msg):
    with app.app_context():
        """send async email in application context"""
        mail.send(msg)
```

**Comment by seemethere** [comment]
@neo1218 does celery work with asyncio?

**Comment by subyraman** [comment]
You shouldn't need a separate task runner like Celery with Sanic, since the asyncio event loop intelligently handles dispatching tasks without blocking the web application. You need a task runner with Flask because email sending would block the web application from serving other requests.

Just keep everything async and you should be fine :)

**Comment by seemethere** [comment]
Awesome I think this question has been answered sufficiently. Will re-open if necessary.

**Comment by GMLudo** [comment]
aiosmtplib seems to be the easiest/best choice for that.

**Comment by jonahfang** [comment]
I have done the job of sending email asynchronously by aiosmtplib+apscheduler:

```
import asyncio
import aiosmtplib
from apscheduler.schedulers.asyncio import AsyncIOScheduler
from email.mime.text import MIMEText
from sanic.response import json

@app.post('/sendemail')
async def send_email(request):
    scheduler = AsyncIOScheduler()
    scheduler.add_job(_send_email,args=[request])
    scheduler.start()
    return ajax_ok()

async def _send_email(request):
    new_obj = request.json

    #Thanks: https://github.com/cole/aiosmtplib/issues/1
    host = get_env('MAIL_SERVER_HOST')
    port = get_env('MAIL_SERVER_PORT')
    user = get_env('MAIL_SERVER_USER')
    password = get_env('MAIL_SERVER_PASSWORD')

    loop = asyncio.get_event_loop()

    server = aiosmtplib.SMTP(host, port, loop=loop, use_tls=False)
    await server.connect()

    await server.starttls()
    await server.login(user, password)

    async def send_a_message():
        message = MIMEText(new_obj.get('body'))
        message['From'] = get_env('MAIL_SERVER_USER')
        message['To'] = ','.join(new_obj.get('email_to'))
        message['Subject'] = new_obj.get('subject')
        await server.send_message(message)

    await send_a_message()
```

You can test the code just like this:

```
#!/bin/bash
DATA='{"body":"testfrompy3","email_to":["499233138@qq.com"],"subject":"test"}'
curl http://dserver:9901/sendemail -X POST -H "Content-Type: application/json" -H "Accept: text/html,application/json" -d ${DATA}
```

**Comment by oubeichen** [comment]
> you can use [celery](http://www.celeryproject.org/), a task queue.
> something like this in flask:
> 
> ```python
> # a celery task: send async email
> @celery.task(default_retry_delay=30)
> def send_async_email(msg):
>     with app.app_context():
>         """send async email in application context"""
>         mail.send(msg)
> ```

how to get the app_context in celery?
