### ISSUE TITLE
can sanic realize a global proxy for request object ?

### ISSUE THREAD

**Issue by neo1218** [channelcat/sanic#447]
## can sanic realize a global proxy for request object ?

ex:  I want to write a decorator wrap the route handler to carry out some HTTP Basic validation, like:

```python
@require_login
async def user_index(request):
    pass
```

so, if I can get **current request context** in a **request object**, it will be very convenient:

```python
from sanic.request import request

def require_login(f):
    authorization = request.headers.get("authorization")
    # parse authorization header
    if authorized:
        f(request)
    else: return json({'msg': 403})
```

I don't know how sanic's request context actual implementation,  maybe we can simply copy the current coroutine's request context to a global request object, and just cover it when another async handler execute.

**Comment by subyraman** [comment]
You don't need a global object for your decorator. Your decorator can intercept the request and check against it.

```python
def require_login():
    def decorator(f):
        @wraps(f)
        async def decorated_function(request, *args, **kwargs):
            # you can check against request here
            authorized = False

            if authorized:
                response = await f(request, *args, **kwargs)
                return response
            else:
                return json({'status': 'not_authorized'}, 403)
        return decorated_function
    return decorator


@app.route("/")
@require_login()
async def test(request):
    return json({"hello": "world"})
```

**Comment by neo1218** [comment]
@subyraman Thanks !!!! 

![screen shot 2017-02-17 at 02 01 09](https://cloud.githubusercontent.com/assets/10671733/23033987/202025da-f4b5-11e6-8804-8af280bf0a50.png)

document is too simple 😂 ```and your can intercept the request``` can add in document 😆
