### ISSUE TITLE
ujson soft requirement

### ISSUE THREAD

**Issue by abuckenheimer** [channelcat/sanic#449]
I'm as big a fan as ujson as the next but it would be nice to have json parsing/serialization degrade gracefully if you can't fullfill the requirement. Be happy to submit a PR, would look more or less would like what [bottle does](https://github.com/bottlepy/bottle/pull/933/files)

**Comment by seemethere** [comment]
What's the issue with `ujson`?

**Comment by abuckenheimer** [comment]
it's just slightly less portable than the stdlib verison, for example I hit a
`ImportError: /lib64/libc.so.6: version 'GLIBC_2.14' not found`
on rhel6 but it works fine on rhel7. I'll probably find a way to work around that somehow but be an easy change if here if it makes sense to you.

**Comment by r0fls** [comment]
I'm fine with using that logic but let's leave it in requirements.txt imo.

**Comment by abuckenheimer** [comment]
awesome, thanks all

**Comment by gsakkis** [comment]
`ujson` is great but looks like [it has lost steam](https://github.com/esnme/ultrajson/issues/246), including open issues and PRs about segfaults and memory leaks. Rapidjson looks more healthy these days, though ideally the json codec used by Sanic should be configurable. I can work on a PR if you agree.

**Comment by SiDChik** [comment]
it would be much better to use rapidjson instead ujson.
