### ISSUE TITLE
Feedback on cache layer

### ISSUE THREAD

**Issue by argaen** [channelcat/sanic#47]
Hi! really interesting project :).

I'm developing an asynchronous cache https://github.com/argaen/aiocache. The project is quite new but I'm looking for feedback and new use cases which will help to improve the interface and its usability.

I want the project to be really easy to integrate with other frameworks so I would really appreciate opinions on it :P. 

Thanks a lot! :)

**Comment by channelcat** [comment]
This looks really useful and simple! :)

I can mostly only comment on my use-case.  I'd love for it to be able to help me cache database objects.  However, that's a pretty big task, on top of the fact that the async ORM options aren't very mature (so far peewee-async is my favorite, though the syntax could be nicer).

Apart from hooking it into an ORM, I'd want to cache responses as easily as possible.  I'd like to be able to directly cache sanic's Response object, so it would be nice if the serializer could handle custom types.  Along with that it would be super helpful if the @ cached decorator could also accept the arguments provided to the decorated function as keys (unless it already does this), and even better if you could specify which arguments + keyword arguments to use.  Example use case:

```python
@app.route('/article/<article_id>')
@cached(ttl=10, key='article_id')
async def get_article(request, article_id):
    article = await objects.get(Article, id=article_id)
    return json({"article": article.serialize()})
```
I'd also like to be able to explicitly clear the cache.

Anyways, I hope that was helpful!

**Comment by argaen** [comment]
Thanks for the feedback @channelcat.

>I'd love for it to be able to help me cache database objects

You can always decorate the calls that are retrieving from the database. For example if you have something like Django but asynchronous, you could always override the manager and decorate the functions `filter`, `get`, `all`, etc. decorating it with the `cached` decorator.

> I'd like to be able to directly cache sanic's Response object, so it would be nice if the serializer could handle custom types

Already supported :). You can use `PickleSerializer` which will work out of the box for caching any Python object to any of the backends. 

You can also write your own serializer for the object you want to serialize and pass it to the cache constructor, this adhoc serializer will give you speed over Pickle but needs more code. Also need to take into account that with a custom serializer you will be on your own when casting the types. For example, serialize "1" to bytes in order to store it in Redis, when retrieving it what type should it be? string, boolean, int?

> it would be super helpful if the @ cached decorator could also accept the arguments provided to the decorated function as keys

Really nice idea. There is a `multi_cached` decorator which will cache functions that return dictionaries inside the cache using the attribute `keys` if it exists in the function call. I will implement choosing which attribute to use as keys for both decorators.


Again, thanks for the feedback! Really appreciated :).

**Comment by seemethere** [comment]
Is this an issue? Will reopen if necessary.
