### ISSUE TITLE
[Question] blueprints and middlewares

### ISSUE THREAD

**Issue by kianxineki** [channelcat/sanic#479]
Hello!

Seeing the blueprints documentation I was trying to port some plugins that I made for bottle and I have had several doubts.

Is it possible to add extra information in @ app.route and be able to read it from a blueprint? for example:

@app.route("/example", auth="admin")

If that were possible, would it be possible to only add the middleware for the requests containing that argument?

I put an example of a bottle plugin I made, I think I could not do the same style, right?

Https://github.com/kianxineki/bottlejwt

A greeting!

**Comment by subyraman** [comment]
Decorators in Sanic are similar to Flask. You could achieve what you want simply adding another decorator instead of adding a parameter to `app.route`. Here's an authorization decorator that I wrote recently. 

```python
def require_login():
    def decorator(f):
        @wraps(f)
        async def decorated_function(request, *args, **kwargs):
            # you can check against request here
            authorized = False

            if authorized:
                response = await f(request, *args, **kwargs)
                return response
            else:
                return json({'status': 'not_authorized'}, 403)
        return decorated_function
    return decorator


@app.route("/")
@require_login()
async def test(request):
    return json({"hello": "world"})
```

**Comment by kianxineki** [comment]
If that was the other choice. Thanks :+1:

**Comment by seemethere** [comment]
Awesome! Closing, will reopen if necessary!
