### ISSUE TITLE
Cookies work on localhost, but not on 0.0.0.0

### ISSUE THREAD

**Issue by rednebmas** [channelcat/sanic#487]
The following code increments a cookie every time the page is refreshed and returns it. When I view the page on 0.0.0.0:8000 it doesn't increment the value, but when I use localhost:8000 it does.

```python
from sanic import Sanic
from sanic.response import text

app = Sanic()

@app.route("/")
async def index(request):
    test_cookie = request.cookies.get('test')
    if test_cookie is None:
        test_cookie = 0

    test_cookie = int(test_cookie)
    test_cookie += 1
    test_cookie = str(test_cookie)

    response = text(test_cookie)
    response.cookies['test'] = test_cookie

    return response

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=8000, debug=True)
```

**Comment by subyraman** [comment]
This is working for me on both the IP address and localhost in Safari/Chrome/Firefox. What browser are you using?

![increment](https://cloud.githubusercontent.com/assets/4042656/23342279/91a59ac4-fc25-11e6-8626-d77ecc5cf410.gif)

**Comment by seemethere** [comment]
🙌 for the gif!

**Comment by rednebmas** [comment]
Hmmm, ok. Must be a config issue on my end. For the record, here's mine *not* working.

![](http://i.imgur.com/C7bEFB5.gif)

**Comment by r0fls** [comment]
Very strange. I was also unable to reproduce this

**Comment by r0fls** [comment]
@rednebmas did you get this figured out?

**Comment by rednebmas** [comment]
@r0fls I didn't. Just using localhost instead. Should I close the issue and leave a comment if and when I figure it out?

**Comment by r0fls** [comment]
Ya, I guess, since it's strange and none of us can reproduce it :)
