### ISSUE TITLE
way too anonymous

### ISSUE THREAD

**Issue by Dowwie** [channelcat/sanic#49]
@channelcat  As you've left no identifying information about yourself for correspondence about sanic I have no choice but to write you here.  I authored Yosai and would like to see how it could be used to secure sanic applications.

**Comment by rzwiefel** [comment]
Forgive me as I am not the project maintainer, but I don't believe securing python applications is within the scope of the sanic project. It is something that could be used in tandem on an individual application basis, but probably has no place in the core project itself.

**Comment by Dowwie** [comment]
Ryan.  That message wasn't intended for you.

**Comment by Dowwie** [comment]
@rzwiefel I'm not proposing changes to the core of a web framework  -- why would anyone even _DO_ that?!  This is listed as an issue because I can't reach the author in private.

**Comment by rzwiefel** [comment]
Was just looking through issues seeing what could be cleaned up and what were actual issues. Understood though. :+1:

**Comment by channelcat** [comment]
Yep, sorry about the lack of information.  I've only been using GitHub for random personal projects.  Will close this if you'd like to continue via email (or we could leave the discussion public).
