### ISSUE TITLE
JSON  Decoding Error with HTML Encoding

### ISSUE THREAD

**Issue by Gowtham95india** [channelcat/sanic#490]
I am trying to use request.json, but it is raising  `sanic.exceptions.InvalidUsage: Failed when parsing body as json
`
Here is request.body:

> b'v=2&e=%5B%7B%22event_type%22%3A%22PRODUCT_VIEWED%22%2C%22timestamp%22%3A1488103552436%2C%22user_id%22%3A%22104019358%22%2C%22advertiser_id%22%3A%2215d3771f-7191-49a4-85fb-582d6e0380a1R%22%2C%22session_id%22%3A1488103492608%2C%22version_name%22%3A%222.14%22%2C%22os_name%22%3A%22android%22%2C%22os_version%22%3A%225.0%22%2C%22device_brand%22%3A%22Sony%22%2C%22device_manufacturer%22%3A%22Sony%22%2C%22device_model%22%3A%22E2363%22%2C%22carrier%22%3A%22airtel%22%2C%22language%22%3A%22en%22%2C%22platform%22%3A%22Android%22%2C%22sequence_number%22%3A127%2C%22device_id%22%3A%228118e22cdc086ff0%22%2C%22gps_enabled%22%3Atrue%2C%22email%22%3A%22srinivasalapati405%40gmail.com%22%2C%22event_properties%22%3A%7B%22Seller%22%3A%22Tonga%22%2C%22Source%22%3A%22Search%22%2C%22SellerRating%20%22%3A%220.0%22%2C%22Brand%22%3A%22Tonga%22%2C%22Category%22%3A%22Tops%20%26%20tunic%22%2C%22isCouponAvailable%22%3A%22true%22%2C%22isLiked%22%3A%22false%22%7D%2C%22event_id%22%3A127%7D%2C%7B%22event_type%22%3A%22Action%20Bar%20Event%22%2C%22timestamp%22%3A1488103552752%2C%22user_id%22%3A%22104019358%22%2C%22advertiser_id%22%3A%2215d3771f-7191-49a4-85fb-582d6e0380a1R%22%2C%22session_id%22%3A1488103492608%2C%22version_name%22%3A%222.14%22%2C%22os_name%22%3A%22android%22%2C%22os_version%22%3A%225.0%22%2C%22device_brand%22%3A%22Sony%22%2C%22device_manufacturer%22%3A%22Sony%22%2C%22device_model%22%3A%22E2363%22%2C%22carrier%22%3A%22airtel%22%2C%22language%22%3A%22en%22%2C%22platform%22%3A%22Android%22%2C%22sequence_number%22%3A128%2C%22device_id%22%3A%228118e22cdc086ff0%22%2C%22gps_enabled%22%3Atrue%2C%22email%22%3A%22srinivasalapati405%40gmail.com%22%2C%22event_properties%22%3A%7B%22type%22%3A%22Cart%20Icon%20Clicked%22%7D%2C%22event_id%22%3A128%7D%2C%7B%22event_type%22%3A%22CART_FIRSTPAGE%22%2C%22timestamp%22%3A1488103553061%2C%22user_id%22%3A%22104019358%22%2C%22advertiser_id%22%3A%2215d3771f-7191-49a4-85fb-582d6e0380a1R%22%2C%22session_id%22%3A1488103492608%2C%22version_name%22%3A%222.14%22%2C%22os_name%22%3A%22android%22%2C%22os_version%22%3A%225.0%22%2C%22device_brand%22%3A%22Sony%22%2C%22device_manufacturer%22%3A%22Sony%22%2C%22device_model%22%3A%22E2363%22%2C%22carrier%22%3A%22airtel%22%2C%22language%22%3A%22en%22%2C%22platform%22%3A%22Android%22%2C%22sequence_number%22%3A129%2C%22device_id%22%3A%228118e22cdc086ff0%22%2C%22gps_enabled%22%3Atrue%2C%22email%22%3A%22srinivasalapati405%40gmail.com%22%2C%22event_properties%22%3A%7B%22DEFAULT_PAYMENT%22%3A%22payu_redirect%22%7D%2C%22event_id%22%3A129%7D%2C%7B%22event_type%22%3A%22PDP_EVENTS%22%2C%22timestamp%22%3A1488103553128%2C%22user_id%22%3A%22104019358%22%2C%22advertiser_id%22%3A%2215d3771f-7191-49a4-85fb-582d6e0380a1R%22%2C%22session_id%22%3A1488103492608%2C%22version_name%22%3A%222.14%22%2C%22os_name%22%3A%22android%22%2C%22os_version%22%3A%225.0%22%2C%22device_brand%22%3A%22Sony%22%2C%22device_manufacturer%22%3A%22Sony%22%2C%22device_model%22%3A%22E2363%22%2C%22carrier%22%3A%22airtel%22%2C%22language%22%3A%22en%22%2C%22platform%22%3A%22Android%22%2C%22sequence_number%22%3A130%2C%22device_id%22%3A%228118e22cdc086ff0%22%2C%22gps_enabled%22%3Atrue%2C%22email%22%3A%22srinivasalapati405%40gmail.com%22%2C%22event_properties%22%3A%7B%22Source%22%3A%22Search%22%2C%22images%22%3A%225%22%2C%22Action%22%3A%22Photo%20Clicked%22%7D%2C%22event_id%22%3A130%7D%2C%7B%22event_type%22%3A%22Action%20Bar%22%2C%22timestamp%22%3A1488103553312%2C%22user_id%22%3A%22104019358%22%2C%22advertiser_id%22%3A%2215d3771f-7191-49a4-85fb-582d6e0380a1R%22%2C%22session_id%22%3A1488103492608%2C%22version_name%22%3A%222.14%22%2C%22os_name%22%3A%22android%22%2C%22os_version%22%3A%225.0%22%2C%22device_brand%22%3A%22Sony%22%2C%22device_manufacturer%22%3A%22Sony%22%2C%22device_model%22%3A%22E2363%22%2C%22carrier%22%3A%22airtel%22%2C%22language%22%3A%22en%22%2C%22platform%22%3A%22Android%22%2C%22sequence_number%22%3A131%2C%22device_id%22%3A%228118e22cdc086ff0%22%2C%22gps_enabled%22%3Atrue%2C%22email%22%3A%22srinivasalapati405%40gmail.com%22%2C%22event_properties%22%3A%7B%22type%22%3A%22Profile%20Open%22%7D%2C%22event_id%22%3A131%7D%2C%7B%22event_type%22%3A%22PDP_EVENTS%22%2C%22timestamp%22%3A1488103555504%2C%22user_id%22%3A%22104019358%22%2C%22advertiser_id%22%3A%2215d3771f-7191-49a4-85fb-582d6e0380a1R%22%2C%22session_id%22%3A1488103492608%2C%22version_name%22%3A%222.14%22%2C%22os_name%22%3A%22android%22%2C%22os_version%22%3A%225.0%22%2C%22device_brand%22%3A%22Sony%22%2C%22device_manufacturer%22%3A%22Sony%22%2C%22device_model%22%3A%22E2363%22%2C%22carrier%22%3A%22airtel%22%2C%22language%22%3A%22en%22%2C%22platform%22%3A%22Android%22%2C%22sequence_number%22%3A132%2C%22device_id%22%3A%228118e22cdc086ff0%22%2C%22gps_enabled%22%3Atrue%2C%22email%22%3A%22srinivasalapati405%40gmail.com%22%2C%22event_properties%22%3A%7B%22Source%22%3A%22Search%22%2C%22images%22%3A%225%22%2C%22Action%22%3A%22Photo%20Clicked%22%7D%2C%22event_id%22%3A132%7D%2C%7B%22event_type%22%3A%22PDP_EVENTS%22%2C%22timestamp%22%3A1488103555505%2C%22user_id%22%3A%22104019358%22%2C%22advertiser_id%22%3A%2215d3771f-7191-49a4-85fb-582d6e0380a1R%22%2C%22session_id%22%3A1488103492608%2C%22version_name%22%3A%222.14%22%2C%22os_name%22%3A%22android%22%2C%22os_version%22%3A%225.0%22%2C%22device_brand%22%3A%22Sony%22%2C%22device_manufacturer%22%3A%22Sony%22%2C%22device_model%22%3A%22E2363%22%2C%22carrier%22%3A%22airtel%22%2C%22language%22%3A%22en%22%2C%22platform%22%3A%22Android%22%2C%22sequence_number%22%3A133%2C%22device_id%22%3A%228118e22cdc086ff0%22%2C%22gps_enabled%22%3Atrue%2C%22email%22%3A%22srinivasalapati405%40gmail.com%22%2C%22event_properties%22%3A%7B%22Source%22%3A%22Search%22%2C%22images%22%3A%225%22%2C%22Action%22%3A%22Photo%20Clicked%22%7D%2C%22event_id%22%3A133%7D%5D&upload_time=1488103585687'

How can I parse this as JSON?

**Comment by subyraman** [comment]
You're not posting a valid JSON encoded string to Sanic, so it's throwing that error. It looks like you're just posting a form, since that body is url-encoded. Check your headers and re-send the data as JSON.

**Comment by Gowtham95india** [comment]
@subyraman Sorry guys. It's my mistake. I was misdirected by the headers. The header I got is content-type: application/json but got the x-www-urlencoded. Thanks...!

**Comment by seemethere** [comment]
No problem! Thanks again @subyraman!
