### ISSUE TITLE
Incorrectly trimming url for non-existent '/'

### ISSUE THREAD

**Issue by jamesstidard** [channelcat/sanic#494]
`sanic.router.Router.add` seems to be miscalculating its if the trailing slash is missing or not - which eats into the url. See last key in comment. This only seems to happen when registering multiple handlers to the same route.

```python
from sanic import Sanic

app = Sanic(__name__)

@app.get('/rest/<resource>')
def get(_):
    pass

@app.post('/rest/<resource>')
def post(_):
    pass

print(app.router.routes_all.keys())
# dict_keys(['/rest/<resource>', '/rest/<resource>/', '/rest/<resource'])
```

**Comment by seemethere** [comment]
Closed with #495
