### ISSUE TITLE
Consider allowing a string response to be inferred as `text(..)`

### ISSUE THREAD

**Issue by blakev** [channelcat/sanic#50]
Instead of saying `return text(..)` in a route, allow `return 'my text'` by inferring the response type in `write_response`.

**sanic/server.py**:

``` python
class HttpProtocol
    ...
    ...
    def write_response(self, response):
        try:
            keep_alive = self.parser.should_keep_alive() and not self.signal.stopped

            try:
                self.transport.write(response.output(self.request.version, keep_alive, self.request_timeout))

            except AttributeError:
                # attempt to send the response as a text response
                if isinstance(response, str):
                    response = text(response)
                    self.transport.write(response.output(self.request.version, keep_alive, self.request_timeout))
                else:
                    raise

            if not keep_alive:
                self.transport.close()
            else:
                self.cleanup()
        except Exception as e:
            self.bail_out("Writing request failed, connection closed {}".format(e))
```

**Comment by seemethere** [comment]
I like this, on another note we should also be allowed to return a dict and it automatically converts to json

**Comment by eseglem** [comment]
I think explicit is probably better the implicit. Does this change any of the benchmarks? If it slows things at all, may not be worth it.

**Comment by rzwiefel** [comment]
@eseglem From an outside opinion, I would say that you are still allowed to do it by explicitly using a HTTPResponse. And the terseness of not having to put redundant information about the response is a huge usability feature.

Also while I don't believe the two isinstance checks will slow performance, if it is a concern there could be an initial isinstance check for HTTPResponse to short circuit the other checks 
(regarding https://github.com/channelcat/sanic/pull/52)
```if isinstance(response, HTTPResponse):
    pass```

**Comment by eseglem** [comment]
Personally I think it should only be explicit. It should be on the user to know what they are returning. They should know if you are returning text() or json(), and put it on the return. I do not thing it detracts from the usability at all. Even putting in the `isinstance(response, HTTPResponse)` first adds an additional call to isinstance which should not be needed at all. It gets added to every single return, meaning (based on the benchmarks) 30,000 calls to isinstance / second, which just seems like unnecessary overhead for something that should already be known by the user. And if they do not know what type it is, they can do an if before the return. Just personally it seems like an unnecessary feature when the number one purpose of the system (to me at least) is to go fast. Anything that slows the system down, even by a tiny fraction, isn't worth it to me.

I may be a bit overly concerned. Based on a bit of timeit, it may only take a 0.2% hit in performance. Which isn't really that much, but I am afraid of 100 little 0.2% hits adding up to a massive hit.

**Comment by rzwiefel** [comment]
@eseglem Good points. I certainly can't argue with explicit over implicit. Especially with the main goal of `goin' fast`, anything that user can declare that the code doesn't have to compute is a definite win.

**Comment by imbolc** [comment]
How often are you using raw text or html response vs json or template in real projects? I don't think we need any sugar foo so rare cases.

**Comment by NickolasBoyer** [comment]
Maybe a bit more descriptive error message could be added to make Sanic a bit more beginner friendly? If you're coming from flask with only the current error it's kinda hard to figure out.

**Comment by r0fls** [comment]
@channelcat @seemethere are we still considering this? It seems like it would be a great usability enhancement. Related, since performance seems to be delaying this: how exactly should we run benchmarks? I'll add it to the readme somewhere if you can point me to the instructions...

**Comment by seemethere** [comment]
I think this one is done. Will re-open if there's a more performant way to do it.
