### ISSUE TITLE
Worker Questions & Documentation

### ISSUE THREAD

**Issue by jamesstidard** [channelcat/sanic#514]
I've been trying to wrap my head around the worker pool and was wondering if there is a plan to document this. Maybe that's a redundant question because the answer is probably: 'yes, the plan is to document all the things'.

I have read through the code but still unsure. My understanding is that when handing `run` more than >1 workers X number of processes are created which will be used to handle requests. Each one of these processes with their own event loop?

With the event loops however, even though I assumed each worker would be running its own event loop they all seem to share an id. If I print `id(loop)` in a 'before_server_start' listener, for example. Though they behave as though they are separate as using `loop.create_task` seems to always call back on the same process. I think I'm missing something here.

One of the other assumptions I have is that a lifetime of a request is handled on the same thread. I just want to confirm that's correct. This is so I know I can use non-threadsafe things like database sessions through the request lifetime. Here's an example of what I mean:

```python
@app.route('/')
async def home(_):
    print(f'pid: {os.getpid()}')  # pid: 12345
    await something()
    print(f'pid: {os.getpid()}')  # pid: 12345 (guaranteed?)
```

Finally, inspecting the app on multiple workers `id(app)` will return the same app id for each process. I believe these are actually the same app instances in memory as I have used a `multiprocessing.Manager` attached to an attribute on the app to share some state between workers - in what I believe to be a safe way. Other then that I asume app should be treated as immutable when working with multiple workers. Does that ring any alarm bells?

Understand this might be a bit of an undertaking to answer these questions if I'm well off-base on anything. So feel free to close this if I'm asking a bit much.

**Comment by seemethere** [comment]
Due to the way keep alive has been implemented I do believe that connections are guaranteed to be handled by the same process so using things that are non thread safe should be okay.

**Comment by r0fls** [comment]
@jamesstidard the app id thing that you're noticing is an illusion. You are logging the id of the app, which is the location of the app pointer in the *python virtual machine*. Each process has its own address space. So, the ids are the same but do not refer to the same objects.

**Comment by r0fls** [comment]
To witness this you can use the following example:

```python
from sanic import Sanic
from sanic.response import json, text
from sanic.log import log 
from multiprocessing import Event
import os

stop_event = Event()

app = Sanic(__name__)
app.pids = []

@app.route("/")
async def test(request):
    request.app.pids.append(os.getpid())
    log.info(request.app.pids)
    return text('ok')

app.run(host="0.0.0.0", port=8000, debug=True, workers=4)
```
Then run a small wrk profile: `wrk -t 10 -c 100 -d 1 http://localhost:8000`. Note that the lists all each contain only the PID of the process for that worker.

**Comment by r0fls** [comment]
Also in your example, yes that request would definitely continue to be handled by the same process.

**Comment by jamesstidard** [comment]
@seemethere @r0fls Ah great, that helps a lot. I had thought that could have been the case (with the ids just being a product of the cloning memory to each process). So everything is cloned for each process (including the app) and from there each process has its own memory space with no shared memory... unless I explicitly create some before calling `run`. I'm pretty happy with that mental model now.

Thank you both for taking the time to answer and also for making me aware of `wrk`
