### ISSUE TITLE
importing TestClient raises pytest warning

### ISSUE THREAD

**Issue by youknowone** [channelcat/sanic#518]
```
====================================== pytest-warning summary =======================================
WC1 ./test_api/utils.py cannot collect test class 'TestClient' because it has a __init__ constructor
======================================= 156 tests deselected ========================================
```

**Comment by seemethere** [comment]
Can you post what you're attempting to do as well?

**Comment by youknowone** [comment]
I imported TestClient to my test code, like:

```
from sanic.testing import TestClient
```

Because `TestClient` exists in the namespace of test file, pytest tries to run it as a class-based test. (though I am using it to create test client object)

**Comment by seemethere** [comment]
I see, maybe a name change would be necessary?

**Comment by youknowone** [comment]
I think so. But I have no idea about good naming not to conflict to pytest searching :s

**Comment by r0fls** [comment]
Closing this as it's tested to work with: https://github.com/channelcat/sanic/pull/525
