### ISSUE TITLE
Sanic as API 

### ISSUE THREAD

**Issue by pwalimbe** [channelcat/sanic#522]
I am evaluating using Sanic as an API layer only. It is working fine so far, however I have a very peculiar problem. Whenever I receive the response as JSON (instead of text) it gives formatting error especially when I am sending back errors(Error: <errmsg>). I want to know how to modify error handler to return a json object instead of the string. I can write custom handler too, just need some pointers.

**Comment by r0fls** [comment]
While you can do this, it might make more sense to use the exception handling and catch each of the exception that are being returned. For example:

```python
from sanic.response import json
from sanic.exceptions import NotFound

@app.exception(NotFound)
def json_404s(request, exception):
    return json({'error': 'notFound'})
```

**Comment by pwalimbe** [comment]
Tried it and works. Thanks for the suggestion !
