### ISSUE TITLE
Deployment - running via command line with SSL

### ISSUE THREAD

**Issue by mikmatko** [channelcat/sanic#523]
Is it possible to run the server via command line with SSL?

Running `python -m sanic` doesn't give any information on this.
```
usage: sanic [-h] [--host HOST] [--port PORT] [--workers WORKERS] [--debug]
             module
```
Thanks!

**Comment by r0fls** [comment]
@mikmatko This was not supported, no. However, do you want to test the branch I created above? :) You should be able to with

```bash
git checkout -b r0fls-523 master
git pull https://github.com/r0fls/sanic.git 523
```

**Comment by r0fls** [comment]
Or we can just merge it, there is no reason it wouldn't work...

**Comment by r0fls** [comment]
Closing this since I merged the above. Let me know if you have issues.
