### ISSUE TITLE
'Sanic' object has no attribute 'url_for'

### ISSUE THREAD

**Issue by aohan237** [channelcat/sanic#526]
when  use extension displayed by doc,  like  session  etc.

it will show this error message.

and  when i dir the Sanic instance,  there is no  url_for attribute ,showed in the doc.

why it  happens? Is the doc kind of out of date?
thanks

**Comment by r0fls** [comment]
You're probably using an old version of Sanic. Can you print the sanic version?

```python
import sanic
>>> sanic.__version__
'0.4.1'
```

**Comment by aohan237** [comment]
'0.3.0'
yeah  it's the version problem
but pip source is the 0.3.*  version  

should i build from source?

**Comment by r0fls** [comment]
You can also pip from source until it's updated:

```
pip install git+git://github.com/channelcat/sanic.git@0.4.1
```

**Comment by aohan237** [comment]
thanks a lot.

pip source did update in time.

i changed one mirror.
