### ISSUE TITLE
will there be any authenticating function supported?

### ISSUE THREAD

**Issue by aohan237** [channelcat/sanic#529]
will there be any authenticating function supported?
in the future?

**Comment by r0fls** [comment]
We don't plan to put it into the core but i'm working on an extension and there is currently https://github.com/subyraman/sanic_session which could be used as the building blocks.

**Comment by aohan237** [comment]
is the 'sanic_session '  ,which you are working on?
or   you are working on someother extension, which not realsed, but currently i can refer to the 'sanic_session'
