### ISSUE TITLE
 Sanic with aiomysql  did not close the connections

### ISSUE THREAD

**Issue by ihjmh** [channelcat/sanic#531]
I use the aiomysql and sanic for my pro,but i got things i don't understand.
   It's very intresting that i run ab test(ab -n 10000 -c 1000 http://localhost).
   I create a test database , use the sql `'select count(*) from information_schema.processlist where db like '%test%';'`,every time I run the ab , check the numbers of connections,first it is 2, the 4,6,8......cause i use 2 worker, until it increase to the 40(max of pool is 20), it stop, never increase and close

I am not very much sure the management of connections belongs to who,aiomysql or sanic? so i asked both topic
   here is my pseudocode
```

`
`#coding:utf8
from sanic import Sanic
from aiomysql.sa import create_engine
import traceback
from sqlalchemy import text as sa_text

engine_glo=''

async def get_engine(p1='',p2=''):
        sqlReader()
        global engine_glo
        engine = await create_engine(user=MySQL_Account, db=MySQL_db,
                            host=MySQL_Host, password=MySQL_pswd, 
                            port=int(MySQL_Port),loop=loop,autocommit=True) 
        engine_glo=engine

async def test_get(request):
        sql="show tables"
        stmt=sa_text(sql)
        global engine_glo
        try:
            if not engine_glo: 
                await get_engine()
            engine=engine_glo
            async with engine.acquire() as conn:
                async for row in conn.execute(stmt):
                        print(row)
         except:
                pass
            
def main():
    app = Sanic(__name__)
    app.add_route(test_get, '/test',methods=['GET']) 
    app.run(host=Host, workers=int(Worker), port=int(Port),before_start=get_engine)

if __name__ == "__main__":
    main()`
`

```

**Comment by nszceta** [comment]
I suggest you give my approach a shot and please give me feedback.

My method **does not allow for multiprocessing** but this is no problem for production purposes as you will want to start multiple independent Python interpreter instances using a supervisor such as supervisord anyway

https://gist.github.com/nszceta/087a14d8896e47bc6e7e441fd60b6ff4

**Comment by ihjmh** [comment]
thx bro, i will try it in monday,then i will let you know the result

**Comment by r0fls** [comment]
there is no aiomysql example but there is a working PR for one here: https://github.com/channelcat/sanic/pull/558

**Comment by ihjmh** [comment]
@r0fls thxs a lot  bro,huge help

**Comment by r0fls** [comment]
Also in general your problem sounds like for some reason it's not closing the aiomysql connection. Since you are already using `async with global_engine.acquire() as conn:` you would think it would be closing them though.. so that is, weird.

**Comment by ihjmh** [comment]
@r0fls I check your example and found that ,it's very much like my demo,so if you're doing it right ,that is so weird.
What's more ,I'm all the connections didn't close ,it keep on connecting until I shut the server down

**Comment by ihjmh** [comment]
please take a look at this,maybe that happend cause i use the sqlalchemy of the aiomysql

`#coding:utf8
from sanic import Sanic
from aiomysql.sa import create_engine
import traceback
from sqlalchemy import text as sa_text

engine_glo=''

async def get_engine(p1='',p2=''):
        sqlReader()
        global engine_glo
        engine = await create_engine(user=MySQL_Account, db=MySQL_db,
                            host=MySQL_Host, password=MySQL_pswd, 
                            port=int(MySQL_Port),loop=loop,autocommit=True) 
        engine_glo=engine

async def test_get(request):
        sql="show tables"
        stmt=sa_text(sql)
        global engine_glo
        try:
            if not engine_glo: 
                await get_engine()
            engine=engine_glo
            async with engine.acquire() as conn:
                async for row in conn.execute(stmt):
                        print(row)
            
def main():
    app = Sanic(__name__)
    app.add_route(test_get, '/test',methods=['GET']) 
    app.run(host=Host, workers=int(Worker), port=int(Port),before_start=get_engine)

if __name__ == "__main__":
    test()`

**Comment by r0fls** [comment]
I don't think SQL alchemy is responsible for holding open the mysql connection in this case, and or closing it. I think it just prepares the statement. Maybe we can open an issue here and link to this one? https://github.com/aio-libs/aiomysql

I feel like aiomysql should be closing the connection when the context manager (i.e. the `with engine.acquire() as conn:...` statement) finishes.

**Comment by r0fls** [comment]
Also how are you verifying that the number of connections is increasing? Just for posterity.

**Comment by r0fls** [comment]
BTW I assume you mean the number of connections to aiomysql.. do you mean to sanic? As in the sanic connections are not closing? Just making sure we're on the same page.

**Comment by Zheaoli** [comment]
@ihjmh I'm the [PR 558's](https://github.com/channelcat/sanic/pull/558) author.Seriously global variable can't make the connection pool effective in Sanic , I don't know why ,Maybe we can ask @r0fls 
To solute this problem , you can set an attribute in app variable to be a connection pool, to avoid the problem that mysql crash by too many connection.

**Comment by ihjmh** [comment]
1. I create a test database , use the sql 'select count(*) from information_schema.processlist where db like '%test%';',every time I run the ab , check the numbers of connections,first it is 2, the 4,6,8......cause i use 2 worker, until it increase to the 40(max of pool is 20), it stop, never increase and close

2. I am not very much sure the management of connections  belongs to who,aiomysql or sanic? so i asked both topic

**Comment by ihjmh** [comment]
@Zheaoli your example is very much like mine,in my ali linux computer 2 core ,4G RAM，single select from the local mysql ,QPS about 1400 ,which I think sucks

**Comment by Zheaoli** [comment]
@ihjmh 
That's wired , When I set global connection pool as an attribute in `app` ，the `Problem too many for mysql` problem has been done.
In my test , the Sanic with aiomysql can handle 2121.4 requests per seconds with count action in mysql with 1 million data.
My service's hardware is just like you.

**Comment by ihjmh** [comment]
@Zheaoli 
 My service is not private runs a lot of other programs, how many workers do u deploy? I check it again : 1200 qps with half of million data and 2 worker

**Comment by Zheaoli** [comment]
@ihjmh 4 works , I will test the situation with 2.

**Comment by Zheaoli** [comment]
@ihjmh 
First test ,result is 375.9 requests per seconds
Second ,result is 2503.79 requests per seconds

Both the tests is counting 1 million data in mysql .

**Comment by ihjmh** [comment]
@Zheaoli  
  I use the aiomysql.sa create_engines , already heard about the sqlalchemy can slow down the qps,maybe it is true,I will try your demo and see what's going on

**Comment by r0fls** [comment]
@ihjmh the 30,000 requests per second is _not_ queries per second. I would persue aiomysql/mysql itself as the primary bottleneck there.

**Comment by r0fls** [comment]
sanic cannot increase sql performance. Also look at the results from postresql here https://github.com/channelcat/sanic/issues/531#issuecomment-285728079 for a more performant sql solution.

**Comment by ihjmh** [comment]
@r0fls I know, I just wanna use single sanic server to do more query works ,1K seems too little for a server

**Comment by ihjmh** [comment]
@r0fls  my problem is ,why the connections didn't close normal, if u like i can show u more codes

**Comment by Zheaoli** [comment]
@r0fls 
Maybe I can make PR for update benchmark with query by using MySQL and MongoDB

**Comment by seemethere** [comment]
I'd suggest using @nszceta's solution revision 3.

Will reopen if necessary.
