### ISSUE TITLE
What is the status of aiopeewee

### ISSUE THREAD

**Issue by kszucs** [channelcat/sanic#534]
Issues are not enabled for aiopeewee. I'd like to try it.

**Comment by qwexvf** [comment]
I think its dead. maybe not ? but i suggest you to use peewee-async
https://github.com/05bit/peewee-async

a few useful samples:
https://github.com/05bit/peewee-async/blob/master/examples/tornado_sample.py
https://github.com/rudyryk/python-samples/blob/master/hello_tornado/hello_asyncio.py

Thanks!

**Comment by seemethere** [comment]
Closing due to it being not a sanic related question.
