### ISSUE TITLE
Testing not support binary

### ISSUE THREAD

**Issue by skytoup** [channelcat/sanic#547]
sanic: 0.4.1

When I write some tests, then will always failure. such as:
```python
app.test_client.get('/xxx.png')
```

I found the problem in snaic/testing.py:23
```python
response.text = await response.text()  # binary decode error
```

**Comment by r0fls** [comment]
Well they don't _always_ fail (see the unit tests). Can you please provide an example where this occurs?

**Comment by skytoup** [comment]
eh...

```python
from sanic import Sanic
app = Sanic(__name__)

app.static('/1.png', '1.png')

def test_static_png():
    _, response = app.test_client.get('/1.png')
    assert response.status == 200
```
1. save to test.py
2. pytest -q test.py

Thank~

**Comment by skytoup** [comment]
eh...
You need a directory name is `1. png` png file

**Comment by nszceta** [comment]
@r0fls can we close this issue?

**Comment by r0fls** [comment]
@nszceta I haven't had time to attempt to reproduce. Are you unable to? @skytoup are you still having problems?

**Comment by skytoup** [comment]
@r0fls I fix it and create a pull requests.<https://github.com/channelcat/sanic/pull/580>
