### ISSUE TITLE
Request to add extension to Extensions Doc page (Sanic-Dispatcher)

### ISSUE THREAD

**Issue by ashleysommer** [channelcat/sanic#548]
I made a Dispatcher extension based on the `DispatcherMiddleware` functionality in Werkzeug. I want to share it with all Sanic users.

It allows you to dispatch requests to other Sanic or WSGI applications if the URL matches a registered Prefix.

It also acts as a Sanic-to-WSGI converter for passing Sanic requests to WSGI applications like Flask or Django, as well as processing the response from WSIG applications as a Sanic response.

See the [README.md ](https://github.com/ashleysommer/sanic-dispatcher/blob/master/README.md) file in the Repo for more information.
[Sanic-Dispatcher](https://github.com/ashleysommer/sanic-dispatcher)

*Note, this is not a router, and is not intended to be a replacement to the Sanic router.*

**Comment by messense** [comment]
You can open a PR to add it to `Extensions` section of documentation.

**Comment by r0fls** [comment]
Yes, please open a PR.
