### ISSUE TITLE
Msgpack as an alternative to ujson

### ISSUE THREAD

**Issue by vromanov** [channelcat/sanic#55]
What do you think about msgpack as json lib? As I know it is faster than ujson.

https://gist.github.com/cactus/4073643
https://blog.ionelmc.ro/2015/11/22/memory-use-and-speed-of-json-parsers/
https://gist.github.com/msiedlarek/4985748#file-ujson_vs_msgpack-py

(my results:
json: 32.72526153300714
ujson: 33.44454480899731
msgpack: 9.162779016012792)

I think it will be great to replace ujson to msgpack or just move ujson to another level of abstraction to have ability to choose between msgpack or ujson or smth else.

**Comment by seemethere** [comment]
What's the advantage? 

You still have to load and dump from json since msgpack is not compatible with straight json.

How does this help with the serialization and deserialization of json?

**Comment by eseglem** [comment]
It would completely replace json. And for pure speed msgpack would be interesting, though I think technically application/msgpack is not actually a valid registered mime type, is it? Not sure if its something that should actually be served out, as most things are probably going to have issues handling it.

**Comment by vromanov** [comment]
@eseglem, completely agree with you.
Ok, it is no way to do it now. Thanks for your thoughts.
