### ISSUE TITLE
allow configurable strict_slashes in router

### ISSUE THREAD

**Issue by phongphan** [channelcat/sanic#557]
Looks like sanic automatically add both with and without trailing slash routes to every route declaration since 0.4.0 207ec1e0322776cd795739a8ce1acf390e8b6888.

I think it would be configurable, maybe by adding `strict_slashes` parameter to `Route` constructor. And let the user to pass it manually to the `app`.

Or maybe also allow adding to any individual route just like Flask does.

**Comment by r0fls** [comment]
I could see adding this knob, but I'm curious _why_? When would you want `http://route.com/get` but not `http://route.com/get/`, or vice-versa?

**Comment by phongphan** [comment]
They could have difference meaning sometimes.
Eg. distinction between file and directory while serving file/directory resource metadata.

**Comment by r0fls** [comment]
Closing with: https://github.com/channelcat/sanic/pull/559
