### ISSUE TITLE
something pushed to the master broke latency

### ISSUE THREAD

**Issue by sm5art** [channelcat/sanic#56]
the speed dropped significantly to roughly 3k on my machine compared to 33k

**Comment by sm5art** [comment]
the blueprint feature merge broke latency, tried a benchmark on this commit f2757bc0743f83ea9c12bd936644c936ca61090f, i got Requests/sec:  38994.25

compared to Requests/sec:   3225.62 with the most recent commit

**Comment by sm5art** [comment]
procedure:
git reset --hard origin/master
**run server/ run benchmark**

git reset --hard f2757bc0743f83ea9c12bd936644c936ca61090f
**run server/ run benchmark**


benchmark command
```
wrk -c 100 -t 1 http://127.0.0.1:8000/ 
```

**Comment by channelcat** [comment]
ack, looking into it

**Comment by channelcat** [comment]
@sm5art Looks like it was this line https://github.com/channelcat/sanic/commit/031a95e4d9d0e2462d47ffd831824db9814a2b7e#diff-bd84a6e523017a7f3d6bd72ee689dce2R125.  Fix pushed to master.
