### ISSUE TITLE
Edit on GitHub link is broken for Markdown files

### ISSUE THREAD

**Issue by lixxu** [channelcat/sanic#563]
When you point to `Edit on Github` link, it will show `404` due to it's pointing to `xx.rst` not `xx.md`.
You can try it on page http://sanic.readthedocs.io/en/latest/sanic/getting_started.html
The issue was talked here https://github.com/rtfd/readthedocs.org/issues/1483, and should be fixed by new version sphinx https://github.com/sphinx-doc/sphinx/issues/2278

**Comment by r0fls** [comment]
Could be related to https://github.com/rtfd/readthedocs.org/issues/1483

**Comment by lixxu** [comment]
yes, I comment it in the issue.

**Comment by r0fls** [comment]
The getting started page edit on github link is now working. If this still an issue in other places, please reopen.
