### ISSUE TITLE
Nginx+docker-compose example

### ISSUE THREAD

**Issue by itielshwartz** [channelcat/sanic#566]
Hi,

I'm in the middle of a Sanic based project.
I wanted to use docker and Nginx but couldn't find a simple **HOW-TO**,
So I ended up creating a simple skeleton app for using sanic behind Nginx (using docker-compose).

Would love getting some feedback (as I'm new to Sanic), And also wanted to ask if it's OK adding some link for it in the docs - as I think nginx+Sanic would be a common combination.

**Comment by itielshwartz** [comment]
Oops forgot to give a link - [nginx+docker-compose example](https://github.com/itielshwartz/sanic-nginx-docker-example) :)

**Comment by r0fls** [comment]
Awesome! However, this might make more sense as part of our examples (in a directory within examples) then as a separate repo. There isn't really a place for this in the docs right now, since it's not really an extension.

**Comment by r0fls** [comment]
Or, if you prefer to add it as an extension that's fine too...

**Comment by itielshwartz** [comment]
Hi, @r0fls sorry for the late response, thanks for the feedback.
I would prefer to put it as an extension (at least for now), as I plan to rapidly improve the repo and add some more basic docs on starting a sanic project, would be easier as a separate project.

**Comment by seemethere** [comment]
This is awesome 😄 

@r0fls maybe it would be good to include something like [these lines](https://github.com/itielshwartz/sanic-nginx-docker-example/blob/master/app/server.py#L20) in the base configuration that automatically check if there's an environment variable for thing and override if they exist.
