### ISSUE TITLE
Testing with pytest-xdist lib

### ISSUE THREAD

**Issue by xinke2411** [channelcat/sanic#574]
I want use pytest-xdist run tests as 
`pytest -n 4 tests`
but SanicTestClient bind 42101 port, and get OSError: [Errno 48] Address already in use, 
i hope  SanicTestClient bind unused port when app server start.

**Comment by seemethere** [comment]
The sanic test client will always try to bind port `42101` by default.

**Comment by seemethere** [comment]
I'm not entirely sure that the unittests would be good to run in parallel.
