### ISSUE TITLE
Testing without response.text()

### ISSUE THREAD

**Issue by qwIvan** [channelcat/sanic#582]
The testing will paser response body as text, but in my project, the response body is a large video. So the operation will raise `UnicodeDecodeError`.
https://github.com/channelcat/sanic/blob/master/sanic/testing.py#L25

**Comment by qwIvan** [comment]
Is there any idea to resolve the problem?

**Comment by r0fls** [comment]
@qwIvan this should fix it: https://github.com/channelcat/sanic/pull/580. Feel free to reopen this if you're still having issues.
