### ISSUE TITLE
latest document is not latest

### ISSUE THREAD

**Issue by lixxu** [channelcat/sanic#591]
The latest document is not latest according to the source code. Does it just work like this or something is wrong?

**Comment by r0fls** [comment]
@lixxu I think it might correlate with pypy releases. Note that it says 0.4.1 in the tab header, which I believe is the latest _published_ version.

**Comment by lixxu** [comment]
imo stable version should be 0.4.1

**Comment by r0fls** [comment]
@lixxu which is what the docs are, no?

**Comment by lixxu** [comment]
currently the latest doc and the stable doc points the same document, I think latest doc should be synced with the latest commit version, while the stable doc synced with published version. Anyway, it's not big issue as it's only the document, you may close it or I'll close it. This issue is sounds like a suggestion.

**Comment by r0fls** [comment]
@lixxu I was wondering that too. @kdelwat may have an idea, he's the one who setup the sphinx/readthedocs integration for us.

**Comment by r0fls** [comment]
This is working now so I'm going to close this for the time being.
