### ISSUE TITLE
CSRF protection in sanic

### ISSUE THREAD

**Issue by Superman132** [channelcat/sanic#609]
I was wondering how to implement CSRF protection in sanic. I know that I would need to create a token in users sessions, but is there anything else that I am missing?

**Comment by r0fls** [comment]
This would be a good extension to have.

**Comment by y7usuf** [comment]
@Superman132 I'm working on this problem.
https://github.com/y7usuf/sanic-csrf
Follow my repo and check in a few days.

**Comment by Superman132** [comment]
Thanks I am closing this

**Comment by vlad1777d** [comment]
@y7usuf , thanks =)

**Comment by siddz05** [comment]
Any Update On this? -- Ur Git Repo Seams to be empty @y7usuf   [[](https://github.com/y7usuf/sanic-csrf)]
