### ISSUE TITLE
A strange problem

### ISSUE THREAD

**Issue by 1067511899** [channelcat/sanic#628]
![strange](https://cloud.githubusercontent.com/assets/21253207/24945379/a3d3e5a4-1f91-11e7-926c-7bee2e41ab30.png)
When I use jmeter to test a sanic app(10000 threads ,run 10000 times),and it print a lot of things like :2017-04-12 15:05:32,146: ERROR: NoneType: None

what's the problem?

Thanks.

btw:

and the sanic app code is just the example code with 16 workers:

from sanic import Sanic
from sanic.response import json

app = Sanic()

@app.route("/")
async def test(request):
    return json({"hello": "world"})

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=8000,workers=16)

**Comment by 1067511899** [comment]
well ,after add a lot of log.error() in server.py,I finally find out that after more than 60 seconds ,some requests get connection_timeout,and the "ERROR: NoneType: None" appears.
but I still don't know why show such a strange Error.
and another problem is ,when use jmeter or apache ab,the request per second is very low than when use wrk.

**Comment by messense** [comment]
It's really annoying for me too.

**Comment by r0fls** [comment]
Is that the output with debug true?

**Comment by messense** [comment]
It shows up regardless of debug is true or not as long as the request timed out.

**Comment by r0fls** [comment]
But there is no more info, right? E.g. the line it occured in.

**Comment by messense** [comment]
```
2017-04-11 13:37:05,068: ERROR: NoneType: None
2017-04-11 13:37:05,068 ERROR sanic.log:90    NoneType: None
2017-04-11 13:37:05,082 INFO websockets.protocol.fail_connection:618   Failing the WebSocket connection: 1006
2017-04-11 13:37:05,084 WARNING prerender.app.handle_request:161   Got 504 for https://www.riskstorm.com/company/620102200129283 in 60005ms
```

(I catched `asyncio.TimeoutError` and log it as `504` for my application.)

Due to the current logging design, the line it occurred wouldn't be in logs. That's why I opened #482  before.

**Comment by messense** [comment]
https://github.com/bosondata/chrome-prerender/blob/master/prerender/app.py#L176

Here is my logging configuration.

**Comment by 1067511899** [comment]
@r0fls no,I do not open debug.
@messense yes,It's really annoying for me ,because I have no clue what the really error is.

**Comment by messense** [comment]
Also if you configure logging with `disable_existing_loggers` set to `false`, you may end up with duplicated logs as shown above.

```
2017-04-11 13:37:05,068: ERROR: NoneType: None
2017-04-11 13:37:05,068 ERROR sanic.log:90    NoneType: None
```

Because Sanic added it's own logger in https://github.com/channelcat/sanic/blob/master/sanic/app.py#L32

**Comment by 1067511899** [comment]
The "NoneType: None" come from handlers.py line 90:
getattr(log, level)(message)
I will see why this happens.

**Comment by 1067511899** [comment]
well,this should happen at:
handlers.py line 92
def default(self, request, exception):
        self.log(format_exc())

and the format_exc() output as NoneType:None.

when timeout(connection_timeout in server.py),the server calls write_error(in server.py),the write_error calls response(in handlers.py),
response(self, request, exception)

and,request is None,exception is "Request Timeout"
handler = self.lookup(exception) and handler is None,(the ErrorHandler maybe not correctly initialized,because self.handler is null)
so 
response = self.default(request=request, exception=exception)

and default output the NoneType：None

I am totally confused.because as I think,when the request time out,server just log an error message as "Request Timeout",that's enough.but after all these things,the "Request Timeout" dispeared,and "NoneType :None" appears.

Is this a bug or something else?

Thanks.

**Comment by 38elements** [comment]
I think this is related #511.

**Comment by 1067511899** [comment]
@38elements yes,you are right,it's the same problem.but I don't think we should use a custome handler to solve it,neither the @app.exception.
first,an @app.exception is good,because we can handle exact exception we want to handle.
some code like :
@app.exception(RequestTimeout)
def timeout(request, exception):
    return text('RequestTimeout from error_handler.', 408)

It works fine,but too complex.most of the time,the developer will never care something about timeout.so,I think,the solution should that there are default handlers to handle those Exceptions.

with your comment,I finally understand the docs at http://sanic.readthedocs.io/en/latest/sanic/exceptions.html,I read them,but never think I should handle 408.

Thanks for your comment,it really helps me.

**Comment by 38elements** [comment]
I think that  `Request Timeout` raised by `keepalive` is noise.
As the code below, If there is no second or subsequent request, it may be better just to disconnect.

```
from time import time
from sanic import Sanic
from sanic.response import json
from sanic.config import Config
from sanic.server import HttpProtocol
from sanic.exceptions import RequestTimeout

Config.REQUEST_TIMEOUT = 3 

class CustomHttpProtocol(HttpProtocol):

    def __init__(self, *, loop, request_handler, error_handler,
            signal, connections, request_timeout,
            request_max_size, request_class):
        super().__init__(
                loop=loop, request_handler=request_handler,
                error_handler=error_handler, signal=signal,
                connections=connections, request_timeout=request_timeout,
                request_max_size=request_max_size, request_class=request_class)
        self.is_first_request = True

    def write_response(self, response):
        super().write_response(response)
        self.is_first_request = False

    def connection_timeout(self):
        current_time = time()
        time_elapsed = current_time - self._last_request_time
        if time_elapsed < self.request_timeout:
            time_left = self.request_timeout - time_elapsed
            self._timeout_handler = ( 
                self.loop.call_later(time_left, self.connection_timeout))
        else:
            if self._request_handler_task:
                self._request_handler_task.cancel()
            if self._total_request_size == 0 and not self.is_first_request:
                self.transport.close()
            else:
                exception = RequestTimeout('Request Timeout')
                self.write_error(exception)


app = Sanic()


@app.route("/")
async def test(request):
        return json({"hello": "world"})

if __name__ == "__main__":
    app.run(host="127.0.0.1", port=8000, protocol=CustomHttpProtocol)
```

**Comment by 1067511899** [comment]
@38elements you are right.since there is a solution,I think we can close this issue now.
btw:I suggest add something to the document,because this "NoneType：None" issue appeared several times.
Thanks.

**Comment by 38elements** [comment]
IMHO,
Regardless of the `keepalive`, when `self._total_request_size` is 0, I think it is better just to disconnect.
I think that it is better to change the behavior of `Sanic`.

**Comment by mbatchkarov** [comment]
It appears that closing the connection at the end of a request can be achieved like this

```
from sanic.config import Config
Config.KEEP_ALIVE = False
```

This setting propagates to here: https://github.com/channelcat/sanic/blob/master/sanic/server.py#L273

**Comment by fqucuo** [comment]
app.REQUEST_TIMEOUT will solve your problem.

**Comment by RifeWang** [comment]
@fqucuo  
I have updated to latest version 19.6.2 and set REQUEST_TIMEOUT to 120 seconds .
```
app.config.REQUEST_TIMEOUT = 120
```
but still get 504 . How do you set configuration ?
