### ISSUE TITLE
Multiprocessing pool kills sanic server

### ISSUE THREAD

**Issue by Deepblue129** [channelcat/sanic#634]
Multiprocessing module stops the sanic server. 

The multiprocessing module is extremely important to running an efficient and fast web server. It gives the user the ability to parallelize computation. It is important that the multiprocessing module is supported.

Reproduce:

1. Start the server `python3 index.py`
2. Load http://localhost:8001/ (Sometimes this step needs to be repeated many times. One time it did not die till 5 loads.)
3. Server stopped

Log:
```
2017-04-13 11:15:23,555: INFO: Goin' Fast @ http://127.0.0.1:8001
2017-04-13 11:15:23,560: INFO: Starting worker [3560]
Health Check
Health Check Done
2017-04-13 11:15:27,713: INFO: Stopping worker [3560]
2017-04-13 11:15:27,817: INFO: Server Stopped
```

index.py
```
import os

from sanic import Sanic
from sanic.response import text, file

from multiprocessing import Pool

app = Sanic(__name__)

@app.route("/")
async def health_check(_):
    print('Health Check')
    pool = Pool()
    pool.close()
    print('Health Check Done')
    return text('OK')

@app.get("/favicon.ico")
async def health_favicon(_):
    return await file(os.path.join(os.getcwd(), 'favicon.ico'))

if __name__ == '__main__':
    app.run(port=8001)
```

**Comment by Deepblue129** [comment]
Tried `pool.terminate`. The server never finishes the health check and stop responding. 

Log:
```
2017-04-13 11:29:47,229: INFO: Goin' Fast @ http://127.0.0.1:8001
2017-04-13 11:29:47,232: INFO: Starting worker [4060]
Health Check
```

index.py w/ terminate
```
@app.route("/")
async def health_check(_):
    print('Health Check')
    pool = Pool()
    pool.terminate()
    print('Health Check Done')
    return text('OK')
```

**Comment by r0fls** [comment]
@Deepblue129 that is actually there in your first example as well (`pool.terminate`) so you might want to remove it from there.

**Comment by Deepblue129** [comment]
@r0fls Good catch!

**Comment by r0fls** [comment]
I was able to reproduce this but it looks like an issue with how you're closing the pool.

```python
import os

from sanic import Sanic
from sanic.response import text, file

from multiprocessing import Pool

app = Sanic(__name__)

@app.route("/")
async def health_check(_):
    print('Health Check')
    pool = Pool()
    pool.close()
    pool.join()
    pool.terminate()
    print('Health Check Done')
    return text('OK')

@app.get("/favicon.ico")
async def health_favicon(_):
    return await file(os.path.join(os.getcwd(), 'favicon.ico'))

if __name__ == '__main__':
    app.run(port=8001)
```

Note the operations here:

```python
pool.close()
pool.join()
pool.terminate()
```

**Comment by Deepblue129** [comment]
@r0fls Can you provide from intuition why those operations in that order do not kill the server?

On a more fundamental note, a handler should not be able to kill the server.

**Comment by r0fls** [comment]
This is more of an issue with multiprocessing itself, in my opinion. Calling `terminate` directly doesn't give the process time to clean up after itself, hence leading to too many open files (on my comp at least, the result will differ per OS I imagine since `terminate` does something different on windows than *nix). Is it working for you now?

**Comment by Deepblue129** [comment]
@r0fls It is working for me now. 

Looks like we are deciding this issue should be handled by the multiprocessing module. So I am closing it.
