### ISSUE TITLE
Is there any extension like flask-wtf?

### ISSUE THREAD

**Issue by geekpy** [channelcat/sanic#640]
Is there any extension like flask-wtf? If not, how do you deal with forms?

**Comment by r0fls** [comment]
All of the known existing extensions are here: https://github.com/channelcat/sanic/blob/master/docs/sanic/extensions.md

I don't see any related to forms. Would be great if you or someone else wanted to contribute this.

**Comment by stopspazzing** [comment]
I generate a form and pull data from it:
https://github.com/stopspazzing/Sanic-Server-with-MDL-Blog-Template/blob/master/main.py#L62-L85

I'm sure there are other ways of doing it... and is a work in progress

**Comment by pyx** [comment]
I cooked up this, [Sanic-WTF](http://sanic-wtf.readthedocs.io/en/latest/) , it is pip-installable. If it works, it's pure miracle 😋

**Comment by seemethere** [comment]
Awesome work @pyx! Closing this now.
