### ISSUE TITLE
sanic works like a charm on Windows 10 with "Bash on Ubuntu on Windows"

### ISSUE THREAD

**Issue by hexcola** [channelcat/sanic#650]
I think  "No wheels for uvloop and httptools on Windows :("  is not a limitation.
I like `uvloop` and this framework. But I have to work on Windows since UE4 is not handy on other system, It's painful to have a linux virtual machine or dual system,  I thought I can try "[Bash on Ubuntu on Windows](https://msdn.microsoft.com/en-us/commandline/wsl/install_guide)", it just works! :)

![Sanic on windows 10 using uvloop](https://raw.githubusercontent.com/hexcola/Notebook/master/Sanic/_images/Image%20052.png)

**Comment by skynyrd** [comment]
I have also run Sanic on Windows 10 Anniversary Edition by following these steps:

1. Activate developer mode
2. Install ubuntu bash support from add/remove Windows features
3. Upgrade Ubuntu to 16.04 (you should run `apt-get remove screen` first
4. Run my app.

It works :)
