### ISSUE TITLE
Can't test endpoint which raise NotFound.

### ISSUE THREAD

**Issue by lk-geimfari** [channelcat/sanic#658]
I want to test endpoint which raise `NotFound` exception, but `py.test` does not catch it:

```
def test_not_found_error():
    with pytest.raises(NotFound):
        app.test_client.get("/api/food/wrongresource")
```

What am I doing wrong?

Screenshot [here](https://cloud.githubusercontent.com/assets/15812620/25315451/a134956c-285d-11e7-9173-a44bde148b12.png).

**Comment by 38elements** [comment]
`app.test_client.get()` returns request and response, as below.

https://github.com/channelcat/sanic/blob/ff17fc95e67e984e7c84c40d786ccdf1aad9b0a2/tests/test_routes.py#L40-L41

**Comment by r0fls** [comment]
To elaborate, for example:

```python

from sanic import Sanic
from sanic import response

app = Sanic(__name__)

@app.route("/")
async def test(request):
    return response.json({"test": True})

def test_not_found_error():
    req, res = app.test_client.get("/api/food/wrongresource")
    assert res.status == 404 
```

**Comment by r0fls** [comment]
I'm closing this for now but let us know if you need further clarification.

**Comment by lk-geimfari** [comment]
@38elements @r0fls Thanks for answers. This is what I needed.
