### ISSUE TITLE
Allow handler in "app.add_route" to be a string

### ISSUE THREAD

**Issue by abhishek-ram** [channelcat/sanic#660]
I was wondering if it would be a good idea to allow strings(module path) for the `handler` argument in `app.add_route`. This would help in moving view functions to a separate file/module easily. If I do this in the existing code I have to deal with circular imports as most of the time we need the `app` in the view function.

Let me know what are your thoughts on this?

**Comment by r0fls** [comment]
Can you show an example of the proposed situation, as well as the current workaround?

**Comment by abhishek-ram** [comment]
I can send a solution but I realized that I was mistaken here. 
Since the app object is exposed in the request. we will never need to import the app in say a `views.py` and thus avoiding circular import issue.
