### ISSUE TITLE
 asyncio call to the mysql client is totally unusable.

### ISSUE THREAD

**Issue by 1067511899** [channelcat/sanic#664]
as example in 370:
https://github.com/channelcat/sanic/issues/370

I modified the code ,so that it can perform a very simple insert.
even if with wrk -t2 -c500,I still get somethings like "pymysql.err.OperationalError: (2003, "Can't connect to MySQL server",blocked by server.......etc.
The aiomysql has very poor performance,and a lot strange errors.I really wonder if someone has tested the code with wrk?

I can use sqlalchemy with pymysql or MySQLdb(mysqlclient),it works,not very good,but works.and there is no strange error(except ERROR: NoneType: None).
btw:with my benchmark,the MySQLdb(mysqlclient) is about 10%~20% faster than pymysql.

As a high performance web server,the route\template\orm are the most import things,no matter what kind of web applications,the database access is always important.
**so ,is there any high performance orm solutions?or high performance database access solutons?**espically with mysql?(like it or not,mysql is far more commonly used than PostgreSQL。) 

Thanks.

here is my sqlalchemy code:

```python
from sanic import Sanic
from sanic import response
from sqlalchemy import MetaData 
from sqlalchemy import create_engine
from sqlalchemy import Table, Column, Integer,  String

engine = create_engine('mysql+mysqldb://root:1qazxsw2!@'
'@192.168.1.72/mydb',  pool_size=200,pool_recycle=3600,echo=True)

metadata = MetaData()

cookies = Table('testtmp1', metadata,
Column('cookie_id', Integer , primary_key=True),
Column('cookie_name', String(50))
)

#metadata.create_all(engine)
 
app = Sanic()
 

@app.route("/testin")
async def testin(request):
    connection = engine.connect()
    ins = cookies.insert().values(
        cookie_name="chocolate chip",

)
    result = connection.execute(ins)
    connection.close()
    return response.text("hello")
 

 
if __name__ == "__main__":
    app.run(host="0.0.0.0", port=8000, workers=8)

```

**Comment by 38elements** [comment]
As below, it is easy to read if you put your code between \`\`\`.

\`\`\`
your code
\`\`\`

↓

```
your code
```

**Comment by seemethere** [comment]
I'm pretty sure the stock SQLAlchemy library does not work asynchronously.

**Comment by peralmq** [comment]
@1067511899 if you want to use SQLAlchemy in an asyncio world you should probably use something like https://github.com/RazerM/sqlalchemy_aio too
