### ISSUE TITLE
Is there anyway to share uvloop with Motor MongoDB driver with asyncio ?

### ISSUE THREAD

**Issue by greentornado** [channelcat/sanic#689]

**Comment by seemethere** [comment]
https://github.com/channelcat/sanic/issues/684

https://github.com/channelcat/sanic/blob/master/examples/sanic_motor.py

**Comment by greentornado** [comment]
Thanks

**Comment by RoTorEx** [comment]
Hey guys, page not found? Can you share how to create pools using motor please?

**Comment by sjsadowski** [comment]
Hi @RoTorEx , this is from 6 1/2 years ago. I suggest asking the motor folks.
