### ISSUE TITLE
How to upload a image in sanic

### ISSUE THREAD

**Issue by yunfengsay** [channelcat/sanic#692]
I send a image use postman 
 
![image](https://cloud.githubusercontent.com/assets/15527378/25707883/781cfd5a-3117-11e7-9f03-1cbcefdc548e.png)

but I get nothing in request.files
![image](https://cloud.githubusercontent.com/assets/15527378/25708244/86357d4e-3118-11e7-9798-42043a8d41dc.png)

this is my code

```
@location.route('/image',methods=['OPTIONS','GET','POST'])
async def image(request):
    print(request.files)
    return json({'code ':200,"id":id})
```

**Comment by 1067511899** [comment]
If you debug into the server,and you will find that ,sanic only support two type of Content-Type:
application/x-www-form-urlencoded
multipart/form-data
I am not familiar with postman，so I write a simple form to post,and it works.
<pre><code>
from sanic import Sanic
from sanic.response import  json

app = Sanic(__name__)
# a static html file,just a form to post image.
app.static('/st/images.html', './client/images.html')

@app.route('/image',methods=['OPTIONS','GET','POST'])
async def image(request):
    print(request.files)
    return json({'code ':200})

app.run(host="0.0.0.0", port=8000,debug=True)
</code></pre>

**Comment by yunfengsay** [comment]
Can i see you html?

**Comment by yunfengsay** [comment]
Thanks~  I get it .

**Comment by Arun10d** [comment]
async def post(self, request, id=None):

        image=request.files.get('image')
        userid = request.form.get('user_id')
       
        profileImage = await ProfileImage.get(request.app,ProfileImage.user_id == userid)

        if profileImage is None:
            try:
                data = {"user_id":userid,"image":image.read()}
                resp = await ProfileImage.insert(request.app,**data)
            except IntegrityError as e:
                raise ServerError(str(e.args[1]),status_code=400)
            return json(resp.json())
        else:
            print("uu---------------",profileImage.user_id)
            print("sdsd----",profileImage.image)
            profileImage.image.from_file(image)
            # profileImage.from_file = data['image']
            # profileImage.image(data.append('image'))
            try:
                await profileImage.save(request.app)
            except IntegrityError as e:
                raise ServerError("Image upload fail",status_code=400)
            return json(profileImage.json())
        

AttributeError: 'NoneType' object has no attribute 'from_file'
