### ISSUE TITLE
Is there a deployment guide for heroku? or docker?

### ISSUE THREAD

**Issue by mrkaspa** [channelcat/sanic#693]

**Comment by sm5art** [comment]
its pretty straight forward to deploy. the web worker will be the main file in which you run the sanic monolith

**Comment by Sniedes722** [comment]
@mrkaspa i've deployed Sanic apps to Heroku numerous times. It's as standard as a flask deployment, Procfile, runtime.txt containing 3.5+, and change the port to os.environ['$PORT'].

**Comment by r0fls** [comment]
We open sourced this from a project I'm working on: https://github.com/DesignTbl/designtbl-proxy

**Comment by r0fls** [comment]
@seemethere maybe we should make a deployment section? cc https://github.com/channelcat/sanic/issues/688

**Comment by Sniedes722** [comment]
@r0fls @seemethere what about a specific example section containing different deployments?

**Comment by r0fls** [comment]
oh derp we already have that: http://sanic.readthedocs.io/en/latest/sanic/deploying.html

well it could help to link to some examples of potential prod deployments (e.g. docker, etc...) from there

**Comment by r0fls** [comment]
@Sniedes722 looks we had the exact same thought at the same time. i think that would be awesome. I personally would like to see:
- a docker swarm with multiple nodes example
- a docker example (even though i agree that one is quite trivial)
- a kubernetes example

I'm probably also forgetting some other good options.

**Comment by r0fls** [comment]
oh lambda too, i haven't gotten that to work with or without zappa

**Comment by Sniedes722** [comment]
@r0fls I opened up #699 for further discussion on this.

**Comment by r0fls** [comment]
let's switch there then :) @mrkaspa feel free to reopen if you're still having issues deploying to docker or heroku and we can give you more help
