### ISSUE TITLE
Using a domain socket?

### ISSUE THREAD

**Issue by rcarmo** [channelcat/sanic#700]
I'm trying to put sanic behind nginx using a domain socket. Is this possible at all?

**Comment by r0fls** [comment]
So you need to expose sanic via a domain socket, right? I don't think that's supported but shouldn't be very hard to add.

**Comment by seemethere** [comment]
You can utilize domain sockets through gunicorn and nginx as shown in gunicorn's documentation:

http://docs.gunicorn.org/en/stable/deploy.html

Refer to [our docs](http://sanic.readthedocs.io/en/latest/sanic/deploying.html#running-via-gunicorn) for how to run a sanic application through gunicorn

**Comment by rcarmo** [comment]
Gunicorn loads the class and creates a TCP listener as well. I need to use an existing setup that relies on domain sockets alone...

**Comment by rcarmo** [comment]
Right. Am willing to test and provide reference configs, of course.

**Comment by r0fls** [comment]
ya, i think unix socket support should be separate from wsgi compatibility.

**Comment by r0fls** [comment]
@rcarmo WIP here: https://github.com/channelcat/sanic/pull/742

**Comment by rcarmo** [comment]
nice, will check ASAP.

**Comment by r0fls** [comment]
@rcarmo I'm merging that as-is for now since I've tested it to work locally. However I may add more to it to make it more user friendly so the usage could break/change.

**Comment by messense** [comment]
How about use [`create_unix_server`](https://docs.python.org/3/library/asyncio-eventloop.html?highlight=create_unix#asyncio.AbstractEventLoop.create_unix_server) when `host` or `port` passed as `unix:///xxx.sock`?
