### ISSUE TITLE
Document logging

### ISSUE THREAD

**Issue by santagada** [channelcat/sanic#72]
Sanic doesn't have a logger like flask, so how to use logging in it

**Comment by wsbmilk** [comment]
+10086

**Comment by r0fls** [comment]
Currently you would just use logging like you would normally in a python app. There is an example here: https://github.com/channelcat/sanic/blob/master/examples/override_logging.py


What kind of documentation would be helpful here?

**Comment by santagada** [comment]
In the future would be nice to have a full manual like flask with a section on logging. But for now just pointing on the readme after the hello world example to a "comprehensive example" with logging and other things a real service need (db access, cookies, post/get requests, maybe ssl, maybe cron tasks)

**Comment by seemethere** [comment]
@santagada I do agree that a full example is really needed that is on the TO-DO list!

**Comment by SakuraSound** [comment]
Does #601 satisfy this issue?

**Comment by seemethere** [comment]
Closing with #601
