### ISSUE TITLE
How to know the websocket client is closed

### ISSUE THREAD

**Issue by atlantis414** [channelcat/sanic#720]
I need to know which client closed the connection , how to do it?

**Comment by qwexvf** [comment]
did you figured out how to handle connection close?

**Comment by atlantis414** [comment]
from sanic.websocket import ConnectionClosed    
try:
     while True:
     rece_data = await ws.recv()
except ConnectionClosed as ex:
    # connectionclosed

**Comment by atlantis414** [comment]
from sanic.websocket import ConnectionClosed
try:
       while True:
              rece_data = await ws.recv()
except ConnectionClosed as ex:
       # connectionclosed

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Marcelo<mailto:notifications@github.com>
发送时间: 2017年7月8日 0:23
收件人: channelcat/sanic<mailto:sanic@noreply.github.com>
抄送: atlantis414<mailto:a.t.l777@hotmail.com>; State change<mailto:state_change@noreply.github.com>
主题: Re: [channelcat/sanic] How to know the websocket client is closed (#720)


did you figured out how to handle connection close?

―

**Comment by qwexvf** [comment]
Nice! Thanks mate :)

**Comment by koshikraj** [comment]
```
from websockets.exceptions import ConnectionClosed
@app.websocket('/feed')
async def feed(request, ws):
    while True:
        try:
            data = await ws.recv()
            print('Received: ' + data)
        except (ConnectionClosed):
            print('closed')
            break
```

**Comment by auyer** [comment]
Will this work if the client is not sending any data, buy receiving instead ?

**Comment by ahopkins** [comment]
@auyer Yes.
