### ISSUE TITLE
Config file issues (not escaping characters, no save ability)

### ISSUE THREAD

**Issue by stopspazzing** [channelcat/sanic#726]
1. If you can load from config, should be able to write/save to config.
2. When loading config, doesn't escape characters ```'```  (See Below).
```
with open("config.py", "wt") as o:
     for key, val in dict.items(app.config):
           o.write(f'{key} = \'\'\'{val}\'\'\'\n')
```
3. Default config includes logo for some odd reason? Contrary to http://sanic.readthedocs.io/en/latest/sanic/config.html#builtin-configuration-values ; You also cant change the Logo, which defeats the point of saving it to app.config
```
LOGO = '''
                 ▄▄▄▄▄
        ▀▀▀██████▄▄▄       _______________
      ▄▄▄▄▄  █████████▄  /                 \
     ▀▀▀▀█████▌ ▀▐▄ ▀▐█ |   Gotta go fast!  |
   ▀▀█████▄▄ ▀██████▄██ | _________________/
   ▀▄▄▄▄▄  ▀▀█▄▀█════█▀ |/
        ▀▀▀▄  ▀▀███ ▀       ▄▄
     ▄███▀▀██▄████████▄ ▄▀▀▀▀▀▀█▌
   ██▀▄▄▄██▀▄███▀ ▀▀████      ▄██
▄▀▀▀▄██▄▀▀▌████▒▒▒▒▒▒███     ▌▄▄▀
▌    ▐▀████▐███▒▒▒▒▒▐██▌
▀▄▄▄▄▀   ▀▀████▒▒▒▒▄██▀
          ▀▀█████████▀
        ▄▄██▀██████▀█
      ▄██▀     ▀▀▀  █
     ▄█             ▐▌
 ▄▄▄▄█▌              ▀█▄▄▄▄▀▀▄
▌     ▐                ▀▀▄▄▄▀
 ▀▀▄▄▀
'''
REQUEST_MAX_SIZE = '''100000000'''
REQUEST_TIMEOUT = '''60'''
KEEP_ALIVE = '''True'''
```

**Comment by pyx** [comment]
1. TBH, I don't see the need to save configuration of current application into file. Not only that we should already have configuration files which can be shared, recorded, replayed, reloaded easily, but some of the values are not supposed to be saved unconditionally, such as secret_key.
2. I will suggest using the builtin function `repr` to serialize values instead of quoting all values as string yourself.  `repr` should work with any type that have a properly defined `__repr__`, that is, `assert obj == eval(repr(obj)) is True`.  So, in your case:
    ```python
    o.write(f'{key} = {repr(val)}\n')
    ```
3. It's cute :)

**Comment by stopspazzing** [comment]
Why have built in loading of a config file if there is no way to save to config file?

**Comment by pyx** [comment]
Configuration-file-loading at runtime helps to have customizable, predictable and reproducible deployment, while avoid hard-coding anything that should be kept secret, such as secret keys, database user names and passwords, etc.  You are not forced to check in these credentials into your source code repository, for example.

Would you show me in what situation that you need to save configurations of current application into files when running your application? 

If you have access to the backend, and be able to change the backend code (like, adding the save config routine), you should have access to configuration files already.  If not, it's probably not a good idea to do so, for security's sake.

As for the logo, try this in your config 🎉 (*Sonic the Hedgehog, ascii-art courtesy of ascii-code.com*) :
```python
LOGO = '''
                             ...,?77??!~~~~!???77?<~....
                        ..?7`                           `7!..
                    .,=`          ..~7^`   I                  ?1.
       ........  ..^            ?`  ..?7!1 .               ...??7
      .        .7`        .,777.. .I.    . .!          .,7!
      ..     .?         .^      .l   ?i. . .`       .,^
       b    .!        .= .?7???7~.     .>r .      .=
       .,.?4         , .^         1        `     4...
        J   ^         ,            5       `         ?<.
       .%.7;         .`     .,     .;                   .=.
       .+^ .,       .%      MML     F       .,             ?,
        P   ,,      J      .MMN     F        6               4.
        l    d,    ,       .MMM!   .t        ..               ,,
        ,    JMa..`         MMM`   .         .!                .;
         r   .M#            .M#   .%  .      .~                 .,
       dMMMNJ..!                 .P7!  .>    .         .         ,,
       .WMMMMMm  ?^..       ..,?! ..    ..   ,  Z7`        `?^..  ,,
          ?THB3       ?77?!        .Yr  .   .!   ?,              ?^C
            ?,                   .,^.` .%  .^      5.
              7,          .....?7     .^  ,`        ?.
                `<.                 .= .`'           1
                ....dn... ... ...,7..J=!7,           .,
             ..=     G.,7  ..,o..  .?    J.           F
           .J.  .^ ,,,t  ,^        ?^.  .^  `?~.      F
          r %J. $    5r J             ,r.1      .=.  .%
          r .77=?4.    ``,     l ., 1  .. <.       4.,
          .$..    .X..   .n..  ., J. r .`  J.       `'
        .?`  .5        `` .%   .% .' L.'    t
        ,. ..1JL          .,   J .$.?`      .
                1.          .=` ` .J7??7<.. .;
                 JS..    ..^      L        7.:
                   `> ..       J.  4.
                    +   r `t   r ~=..G.
                    =   $  ,.  J
                    2   r   t  .;
              .,7!  r   t`7~..  j..
              j   7~L...$=.?7r   r ;?1.
               8.      .=    j ..,^   ..
              r        G              .
            .,7,        j,           .>=.
         .J??,  `T....... %             ..
      ..^     <.  ~.    ,.             .D
    .?`        1   L     .7.........?Ti..l
   ,`           L  .    .%    .`!       `j,
 .^             .  ..   .`   .^  .?7!?7+. 1
.`              .  .`..`7.  .^  ,`      .i.;
.7<..........~<<3?7!`    4. r  `          G%
                          J.` .!           %
                            JiJ           .`
                              .1.         J
                                 ?1.     .'
                                     7<..%
'''
```

**Comment by stopspazzing** [comment]
Logo doesn't change, as was stated, doesn't mater what you change it to, but thanks for the ascii. No point in config, user can just change the app. Therefore code for reading from a config file are unnecessary bloat.

**Comment by pyx** [comment]
I am using sanic 0.5.4, I can change the logo from configuration file.

Loading from configuration file is **necessary**, let's say you are writing a web application with database backend, on deployment, how do you specify those database user name and password, in your application's source code?  What if you want to change the credentials later, changing your application's source code again?  You should be using SCM such as git and mercurial to manage your source code, then your credentials are written-in-stone with your source code, do you really want that to be recorded in the source code repository?  What if you want to share the source code with somebody else?  What if you want to open-source your application?

Separating source code and configuration is a well established practice, not only in web development.

Hope that helps. ✌️

**Comment by stopspazzing** [comment]
guess my questions don't make sense, Ill just submit a PR.

**Comment by r0fls** [comment]
@stopspazzing well i have to agree there isn't much reason to update config from within the app, or rather that would be bad practice and potentially introduce vulnerabilities. Why do you think that's a good idea? Regarding the other points, I haven't had the time to verify. For example, I thought the logo did update when changed in the config but haven't tested.

**Comment by r0fls** [comment]
@stopspazzing here is an example changing the logo:

```
$ cat simple_server.py 
from sanic import Sanic
from sanic import response

app = Sanic(__name__)

app.config.LOGO = "whaddup?\n"


@app.route("/")
async def test(request):
    return response.json({"test": True})


if __name__ == '__main__':
    app.run(host="0.0.0.0", port=8000)

$ python3 simple_server.py 
2017-05-15 18:23:31 - (sanic)[DEBUG]: whaddup?

2017-05-15 18:23:31 - (sanic)[INFO]: Goin' Fast @ http://0.0.0.0:8000
2017-05-15 18:23:31 - (sanic)[INFO]: Starting worker [5772]
^C2017-05-15 18:23:31 - (sanic)[INFO]: Stopping worker [5772]
2017-05-15 18:23:31 - (sanic)[INFO]: Server Stopped
```

Can you show one that doesn't work?
