### ISSUE TITLE
Why not just wait() for the stop event to happen?

### ISSUE THREAD

**Issue by santagada** [channelcat/sanic#73]
in: https://github.com/channelcat/sanic/blob/master/sanic/sanic.py#L257 you spin every 0.3 seconds checking if the event has been set, why not just wait on the event?

**Comment by channelcat** [comment]
I uh... I have no excuse <<;;.  I'll patch it :P

**Comment by channelcat** [comment]
Very strange, when I use wait() it registers the SIGTERM, but doesn't unblock after stop_event.set() is called.

**Comment by santagada** [comment]
I can give it a try.

**Comment by r0fls** [comment]
@channelcat in case you're curious:
>Unix: wait(object_list, timeout) almost equivalent select.select(object_list, [], [], timeout). The difference is that, if select.select() is interrupted by a signal, it can raise OSError with an error number of EINTR, whereas wait() will not.

From here: https://docs.python.org/3/library/multiprocessing.html

**Comment by r0fls** [comment]
@seemethere this is probably good to close I think.

**Comment by seemethere** [comment]
Would agree, closed per #238

**Comment by r0fls** [comment]
Actually this is still an issue but it's been very elusive.

**Comment by seemethere** [comment]
Is this still an issue? Will reopen if necessary.
