### ISSUE TITLE
Refactoring register_middleware

### ISSUE THREAD

**Issue by jrocketfingers** [channelcat/sanic#730]
Is there a particular reason that we're nesting register_middleware within the middleware decorator? https://github.com/channelcat/sanic/blob/master/sanic/app.py#L280

The usecase I have is that I'm doing an `init_auth(app)` which should register all the necessary middlewares, and I have to write things like `app.middleware('request')(middleware)`.

I'd prefer being able to write `app.register_middleware(middleware, attach_to='request')`.

I can make a quick PR if factoring it out makes sense.

**Comment by 38elements** [comment]
It is changing the expression method for registering middleware.
Would you tell me other advantages?
Sanic uses many decorator for registering.
I think using the decorator is more consistent.

**Comment by jrocketfingers** [comment]
Can you point out any particular disadvantages? All I'm seeing is gaining a cleaner way to explicitly register middleware.

On the other hand, if we're going to invoke consistency here, I'd like to call upon the ability to explicitly register routes using `app.router.add`, besides the `app.route` decorator.

**Comment by 38elements** [comment]
Does `Refactoring register_middleware` mean `replacing app.middleware() to app.register_middleware()`?

**Comment by jrocketfingers** [comment]
No, it means keeping both, just extracting `register_middleware` out one level, to make it available as `app.register_middleware` (currently it's nested within the decorator).

I'll make a quick PR in a couple of minutes so we can discuss on some cold hard code.

**Comment by 38elements** [comment]
Thank you for responding.
I thought this means replacing.
But, I think there is not sufficient benefit for adding lines.
I think this is not necessary.
But, others may think there is sufficient benefit.
If you think this is necessary with confident, you send pull request.

**Comment by jrocketfingers** [comment]
I didn't get around to doing it, I've had some issues with making a partial out of the method. I'm hoping to get around to it later this evening.

In any case, I don't think we're even changing the number of lines. It's purely extracting the nested function into a method. Literally everything stays the same. (I guess there's an extra newline to keep it pep8 conforming, if we're to nitpick).

**Comment by jrocketfingers** [comment]
@38elements, could you take a look at #732?

**Comment by r0fls** [comment]
closed with #732
