### ISSUE TITLE
NoneType error in request.token

### ISSUE THREAD

**Issue by h-wei** [channelcat/sanic#735]
```
# request.py

    @property
    def token(self):
        """Attempt to return the auth header token.

        :return: token related to request
        """
        auth_header = self.headers.get('Authorization')
        if 'Token ' in auth_header:  
            return auth_header.partition('Token ')[-1]
        else:
            return auth_header
```
In the code, if 'Authorization' is not in request headers, it will raise TypeError: 'argument of type 'NoneType' is not iterable'.  Returns `auth_header` directly and deletes `if-statement` is better. 

```
@property
def token(self):
      """ ...."""
      return self.headers.get('Authorization')
```

**Comment by jrocketfingers** [comment]
Got ya covered in #731.

**Comment by r0fls** [comment]
Closing with https://github.com/channelcat/sanic/pull/731

Please use the current master to include this fix. The next release will contain it.
