### ISSUE TITLE
Any plan to include 401?

### ISSUE THREAD

**Issue by pyx** [channelcat/sanic#739]
I am working on a simple authentication extension, I need to throw an exception of `401 unauthorized`, what is the proper way to do that?

Should I subclass `sanic.exceptions.SanicException` as:
```python
class Unauthorized(SanicException):
    status_code = 401
```
in my package, or is it a good idea to include that seemingly common HTTP status code in Sanic?

Further, to the best of my knowledge, there is no `abort` function like in Flask and bottle in Sanic, should Sanic pre-define all possible common status codes?  Maybe an `abort` function is better than this.

Thanks.

**Comment by pyx** [comment]
I can draft a PR to either implement those status code as individual exceptions, or a generic `abort` function which raises specified status code with an `SanicException`.

In latter case, we will need a pre-define mapping for existing exceptions, to speed up the look up[1] time,  It is actually not going every well with the current implementation.

[1]: we don't want `abort(404)` to raise `SanicException(status_code=404)` instead of `NotFound`.

**Comment by pyx** [comment]
Thinking more about that, concrete exception for each HTTP error code is not as flexible as the way Flask and bottle using, they both can work on the error code as plain old int, especially the error handling part [1] [2],  which allows user to use and catch any (im)possbie codes without restriction.

[1]: Flask's `app.errorhandler`, works on an interger, http://flask.pocoo.org/docs/dev/quickstart/#redirects-and-errors
[2]: Bottle's decorator `error`, also needs only an integer, https://bottlepy.org/docs/dev/tutorial.html#error-pages

**Comment by r0fls** [comment]
@pyx does this seem like an apt solution to you? https://github.com/channelcat/sanic/pull/740/files

Then you can do:

```python
from sanic import Sanic
from sanic import response
from sanic.exceptions import SanicException

app = Sanic(__name__)

@app.route("/")
async def test(request):
    raise SanicException(status_code=401)
    return response.json({"test": True}, status=304, headers=headers)


if __name__ == '__main__':
    app.run(host="0.0.0.0", port=8000)
```

**Comment by pyx** [comment]
@r0fls Thanks for the quick PR.

Raising a `SanicException` with status code is what I am going to use as of right now.

But the part that worries me is style and consistency between Sanic, extensions and end user code.

Let's say that, right now, I am using `SanicException` with 401 in my extension, to catch that, users of my extension will have to use a generic error handler, and tests status code inside that.  To make it more elegant, I can provide an `Unauthorized` exception, so that my users can use:
```python
@app.exception(my_extension.Unauthorized)
...
```
instead.
Which if I understand correctly, is the purpose of using concrete exceptions for each individual error code.
All seems good except, my implementation is not canonical, what If the user is using another extension with their implementation of the same error code? If later on, Sanic decide to have it's `Unautherized` exception, then there will be a mess within all three parties (Sanic, the extension, the end user) because they were using different implementations for the same thing.

**Comment by pyx** [comment]
BTW, I personally prefer using plaint old integer:

1. the HTTP error codes are standardized, there should be one on one mapping between the code and the error, so an integer is enough to identify a specific error.
2. testing against integer is faster than matching on specific Exception type, and uses less memory, but I am only guessing here.
3. it's future-proof without much code addition in Sanic's code base.

But there is a hugh drawback, this change will break existing code. :(

**Comment by r0fls** [comment]
I agree, we should consider changing the order of the parameters in SanicException, and assuming the message will be inferred from the code. However that would be a breaking change. I did add an `abort` function to the PR, which I think would be nice to have.

**Comment by pyx** [comment]
@r0fls thanks, I commented on that change.

**Comment by r0fls** [comment]
Closing this with https://github.com/channelcat/sanic/pull/740
