### ISSUE TITLE
Cookie Support

### ISSUE THREAD

**Issue by channelcat** [channelcat/sanic#74]
Cookie support is needed for both requests and responses.

Request:
 * Provide a cookie property with caching to self.parsed_cookies
 * optimally, it should just be a dictionary of cookie keys to cookie values, to be used like: 
```python
cookie_value = request.cookies['cookie_name']
```

Response:
 * Interface could look like:
```python
response.cookies['cookie_name'] = 'cookie_value'
response.cookies.set(name='cookie_name', value='cookie_value', secure=True,\
                     http_only=True, domain='.my-domain.com', path='/my-path', \
                     expires=datetime.now(), max_age=timedelta(days=1))
```
* Ideally, this should update the Set-Cookies header of the response when cookies are set.

**Comment by blakev** [comment]
This is a little harder than I anticipated, is there an external cookie library you'd consider or should it be re-implemented for this project?

**Comment by imbolc** [comment]
Why just don't use aiohttp realization? Do you found some performance problem with this? 
[get](https://github.com/KeepSafe/aiohttp/blob/master/aiohttp/web_reqrep.py#L287)
[set](https://github.com/KeepSafe/aiohttp/blob/master/aiohttp/web_reqrep.py#L530)

**Comment by channelcat** [comment]
Ah, nice.  I had no idea there was a cookie parser bundled with Python.  I put in basic cookie handling using http.cookies.SimpleCookie.  Thanks both of you for working on this!
