### ISSUE TITLE
Allow Websocket max_size limit

### ISSUE THREAD

**Issue by InvaderGir1** [channelcat/sanic#746]
I saw that sanic uses the websockets package meaning this protocol:
[https://github.com/aaugustin/webso)ckets/blob/master/websockets/protocol.py](url)
Will it be possible to expose the max_size limit, queue etc, to sanic's WebSocketCommonProtocol? (I currently did a change allowing arguments to be passed from sanic's to the WebsocketCommonPortocol created in line 65. (adding the max_size I want for my sockets)

I would be more then glad to add it and create a pull request if required.

Thanks!

**Comment by messense** [comment]
I guess you can make some config items like `WEBSOCKET_MAX_SIZE`, `WEBSOCKET_MAX_QUEUES` etc. and pass it into `WebSocketCommonProtocol`, so people can change it by [configuration](http://sanic.readthedocs.io/en/latest/sanic/config.html).

**Comment by messense** [comment]
I created a pull request for this #748

**Comment by seemethere** [comment]
Closed with #748
