### ISSUE TITLE
fragmented headers

### ISSUE THREAD

**Issue by qwesda** [channelcat/sanic#755]
I stumbled upon an error where long header values (OAuth2 tokens in my case) may lead to fragmentation of the header names. This error was only reproducible with a remote server, not with a local dev server.

The error happens here: [server.py#L167](https://github.com/channelcat/sanic/blob/master/sanic/server.py#L167). The `value` param seems to be `None` if the header is not fully parsed. An empty header value is represented by `b''`.

Adding a debug log statement `log.debug('on_header: %s %s', name, value)` to the `on_header` function yield the following:

```
on_header: b'Conn' None
on_header: b'ection' b'close'
```

or 

```
on_header: b'Connection' None
on_header: b'' b'close'
```

I fixed this by adding the header only if the `value` is not `None` and saving the `name` values to a new class variable (`_header_fragment`) on the `HttpProtocol` instance.

I will open a pull request.

**Comment by csharpsharper** [comment]
same question! thanks!!

**Comment by youknowone** [comment]
Experiencing same error. It causes unhandled 400 error.

**Comment by youknowone** [comment]
Is it bug of sanic or httptools?

**Comment by messense** [comment]
https://github.com/channelcat/sanic/pull/756

**Comment by qwesda** [comment]
@youknowone I would suggest handling it as a bug in sanic. Httptools doesn't have extensive documentation so it's hard to say if this is the intended behavior or not. Also the last commit in the httptools repo was a year ago, so even if it's a bug there there is little to no chance it will get fixed in any reasonable time.
