### ISSUE TITLE
Upgrade Aiohttp 2.1.0

### ISSUE THREAD

**Issue by stopspazzing** [channelcat/sanic#768]
Upgrading to Aiohttp 2.1.0 anytime soon? https://pypi.python.org/pypi/aiohttp
adds speed increases...

> Finally uvloop gives performance improvement. Overall performance improvement should be around 70-90% compared to 1.x version.

http://aiohttp.readthedocs.io/en/latest/migration.html

**Comment by seemethere** [comment]
I'm not really worried about it. It's for a test suite that doesn't really care about performance.

If you can find a way to do this without breaking the tests I'm down for it.
