### ISSUE TITLE
Examples - Peewee Async

### ISSUE THREAD

**Issue by channelcat** [channelcat/sanic#77]
Create a new example of how to use peewee-async with Sanic. It can be a simple python file or an organized project in its own folder, whichever is easiest to understand and gets someone started on the right track.

Peewee-async docs: 
https://peewee-async.readthedocs.io/en/latest/

**Comment by narzeja** [comment]
PR is ready, check it out.

**Comment by channelcat** [comment]
Merged, closing :)
