### ISSUE TITLE
Test client does not support synchronous response.json

### ISSUE THREAD

**Issue by jrocketfingers** [channelcat/sanic#771]
As per https://github.com/channelcat/sanic/blob/master/sanic/testing.py#L28 we can only go for `response.text`. For the sake of consistency, should we await json as well/convert to json on the spot?

Since Sanic errs whenever the test client runs in a coroutine, having this awaited for us is only possible within the test client. Of course, we can always do something along the lines of `json.loads(response.text)`, but, as I already said, for the sake of consistency, we might want to expose both.

As far as I've understood, the consensus is that the speed is not crucial for the testing utilities as well.

Can anyone weigh in on this?

**Comment by yunstanford** [comment]
yeah, exactly.

**Comment by jrocketfingers** [comment]
Resolved in #773
