### ISSUE TITLE
Running sanic api endpoints in different processes/workers

### ISSUE THREAD

**Issue by ottopoika** [channelcat/sanic#772]
I have machine learning agents with own api endpoints. They need to keep state so just increasing workers does not work. Also sharing memory between different processes decreased performance. Is there a way to one worker process per blueprint?

Example:
I have 3 agents /api/a, /api/b, /api/c. All apis have own state so I can't have 3 workers that serve all of them. Instead I would like to have worker 1 for /api/1, worker 2 for /api/b and worker 3 for /api/c

I could use nginx or other but would this be doable purely in Sanic? Currently we have just 1 process and support for creating agents with api call.

**Comment by seemethere** [comment]
Unfortunately I don't think there's a way to currently do this with pure Sanic.

Maybe this is the area for an extension?

**Comment by sust4in** [comment]
Blueprints doesnt work when gunicorn has more than one worker. 

Example : i have just one blueprint with prefix /api/ its @bp and also i have @app. when there is 1 worker it works correctly. but when you increase the worker count its failed. is there any workaround for this? 

or we can try to make extension for this because its important when you want to use blueprints with multiple gunicorn workers.

**Comment by messense** [comment]
> when you increase the worker count its failed

What do you mean by that? Any details on how it failed?

**Comment by sust4in** [comment]
`blueprint_v1 = Blueprint('v1', url_prefix='api/v1')` -- it works with sanic's built-in server. 
...
...
```
if __name__ == '__main__':
    app.blueprint(blueprint_v1)
    app.run(host='0.0.0.0', port=5000, debug=True)
```

firstly i am using **sanic.worker.GunicornWorker**. sanic's built in server works well. 
`gunicorn --bind 0.0.0.0:5000 --worker-class sanic.worker.GunicornWorker myweb:app
`

```
root      33715  8.0  0.7 119052 28940 pts/4    S+   14:33   0:00 /usr/bin/python /usr/bin/gunicorn --bind 0.0.0.0:5000 --worker-class sanic.worker.GunicornWorker myweb:app
root      33718  5.3  0.8 152792 35884 pts/4    S+   14:33   0:00 /usr/bin/python /usr/bin/gunicorn --bind 0.0.0.0:5000 --worker-class sanic.worker.GunicornWorker myweb:app

```
app output when using gunicorn
```
2017-06-14 14:39:46 - (sanic)[ERROR]: Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/sanic/app.py", line 461, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/usr/lib/python3.6/site-packages/sanic/router.py", line 290, in get
    return self._get(request.path, request.method, '')
  File "/usr/lib/python3.6/site-packages/sanic/router.py", line 339, in _get
    raise NotFound('Requested URL {} not found'.format(url))
sanic.exceptions.NotFound: Requested URL /api/v1 not found

```
gunicorn error.log output 
```
[2017-06-14 14:48:22 +0300] [34000] [INFO] Starting gunicorn 19.7.1
[2017-06-14 14:48:22 +0300] [34000] [INFO] Listening at: http://0.0.0.0:5000(34000)
[2017-06-14 14:48:22 +0300] [34000] [INFO] Using worker: sanic.worker.GunicornWorker
[2017-06-14 14:48:22 +0300] [34004] [INFO] Booting worker with pid: 34004
[2017-06-14 14:49:03 +0300] [34000] [INFO] Handling signal: winch
[2017-06-14 14:49:15 +0300] [34000] [INFO] Handling signal: int

```


this is built-in server output with no errors. @messense why it works when i run with built-in server. 

````
2017-06-14 14:40:49 - (sanic)[INFO]: Goin' Fast @ http://0.0.0.0:5000
2017-06-14 14:40:49 - (sanic)[INFO]: Starting worker [33848]
2017-06-14 14:41:09 - (network)[INFO][127.0.0.1:43964]: GET http://localhost:5000/api/v1  200 43

```

**Comment by messense** [comment]
@sust4in I can't reproduce the 404 error with the blueprints example here https://github.com/channelcat/sanic/blob/master/examples/blueprints.py

**Comment by sust4in** [comment]
`if __name__ == '__main__': ` 
i just solved by removing main if entry because gunicorn just imports our script.
it works now. thank you @messense

**Comment by ottopoika** [comment]
I solved this with asiozmq. Sanic and api was left as it was but the heavy lifting is now done in own processes. Communication is done with zeromq ipc.
