### ISSUE TITLE
ClientSession

### ISSUE THREAD

**Issue by yunstanford** [channelcat/sanic#777]
It's better to have a ClientSession inside Sanic, which could maintain a connection pool under the hood, just like aiohttp does.

**Comment by seemethere** [comment]
Can you elaborate?

**Comment by stopspazzing** [comment]
https://aiohttp.readthedocs.io/en/stable/client_reference.html#client-session

> Client Session
Client session is the recommended interface for making HTTP requests.
Session encapsulates a connection pool (connector instance) and supports keepalives by default. Unless you are connecting to a large, unknown number of different servers over the lifetime of your application, it is suggested you use a single session for the lifetime of your application to benefit from connection pooling.

Does Sanic have connection pools?

**Comment by seemethere** [comment]
I'm not entirely sure how that would benefit Sanic? If you want to have a ClientSession just use aiohttp with Sanic.
