### ISSUE TITLE
Sanic could be MutableMapping ?

### ISSUE THREAD

**Issue by yunstanford** [channelcat/sanic#779]
The sanic class could be MutableMapping. it's very easy to add any application specific stuffs there.

app["session"] = ClientSession()
app["db"] = MongoDb()

**Comment by seemethere** [comment]
I'm not opposed to it.

People are already doing something similar to this though with attributes:

```python
app.session = ClientSession()
```

**Comment by yunstanford** [comment]
yes, it works with attributes, but it may overwrite default/builtin attributes by mistake.
