### ISSUE TITLE
No of requests getting throttled

### ISSUE THREAD

**Issue by niteeshm** [channelcat/sanic#794]
I am load testing my service in production using our in-house tool and also using wrk on multiple machines. Monitoring the no of requests and response time using statsd pushed to grafana. 

What i observed is that the number of requests are getting throttled to ~220K RPM. There is no throttling enabled on my server and nor on HAP either ( service is running on 7 servers load balanced behind HAProxy ). 

Any idea why would this happen ? I thought sanic could easily support huge number of calls per second. But it is not even able to handle this minuscule scale. Any help would be appreciated because we really want to use Sanic on our production but this scale might be a deal breaker. 

Happy to share any server config if you need. I am using sanic version 0.5.1 . Haven't moved to new version yet due to removal of `after_start` argument , need to change to annotation based listener for the new versions.
Attaching a graph from grafana depicting the same behavior.
<img width="1653" alt="screen shot 2017-06-15 at 7 58 25 pm" src="https://user-images.githubusercontent.com/1962790/27186397-dcb3eed6-5205-11e7-8224-0668433b963b.png">

**Comment by yunstanford** [comment]
Does your service handle lots of IO, or just handle very lightweight request ? how many processes do you have on each machine ? it's very hard to say anything without your context. Do you have any other metrics to share as well ? 

You may wanna share more context/server settings.

**Comment by niteeshm** [comment]
Service only reads data from redis (extensive calls) . I have 32 workers per machine . Total 7 machines are there. Each machine has 12cores/24GB ram.  It turned out that our cloud provider was capping the bandwidth at 1GBps. So actually the Redis Cluster was a bottleneck. No issues with Sanic. Scales perfectly for our needs. Serving ~7K requests per second without any issues now.

**Comment by yunstanford** [comment]
Maybe a little aggressive to have 32 workers running on 12 cores machine.

**Comment by niteeshm** [comment]
Yeah but the CPU usage and load average remains minimal even with lots of
requests coming in
