### ISSUE TITLE
Unconsumed Exceptions

### ISSUE THREAD

**Issue by InvaderGir1** [channelcat/sanic#796]
Hi, 
I am kinda new to asyncio, and sanic in general, and I am not entirely sure, If I did something wrong, or maybe there might be an issue in sanic, or something that I am doing wrong.

Basically, when I do asyncio.ensure_future(some_future) in before_server_start function that I added, if an exception is raised and is not consumed..  I don't get any indication from asyncio's logger that Task Exception wasn't consumed. I tried everything from setting everything to debug..

Any Ideas why my exceptions are consumed for some reason?

Thanks!

UPDATE:
okay I found out why, the loop's default exception handler is the default one, which for some reason doesn't print the error..

**Comment by r0fls** [comment]
Hi, are you still having an issue? It would be helpful to post a complete, minimal example that demonstrates this. You can also see the `app.add_task` method, e.g.:

```python
app = Sanic()

async def notify_server_started_after_five_seconds():
    await asyncio.sleep(5)
    print('Server successfully started!')

app.add_task(notify_server_started_after_five_seconds())
```

**Comment by seemethere** [comment]
Closing, will reopen if necessary
