### ISSUE TITLE
about extensions.md in doc 

### ISSUE THREAD

**Issue by boylegu** [channelcat/sanic#806]
Hi Hero:
    Firstly, in this very thank yours project  to bring their own power. It's very cool. So I have example demo project base Sanic with vueJS + webpack and hope update to  extensions.md in doc.

~~~
    - [SanicCRUD-vue](https://github.com/boylegu/SanicCRUD-vue): A example demo base Sanic with vueJS + webpack

~~~

I hope pass thought this example demo project for Sanic to be a better promotion. 
So may i can take it merge your extensions.md ?  Thanks.

**Comment by stopspazzing** [comment]
I just added this to the wiki, soon the extensions.md file will be removed. Only Sanic core related info will be in docs.
https://github.com/channelcat/sanic/wiki/Extensions

😄

**Comment by seemethere** [comment]
Awesome! Closing this for now
