### ISSUE TITLE
Asynchronous File upload

### ISSUE THREAD

**Issue by gsvijayraajaa** [channelcat/sanic#807]
Hi,

Is there a Sanic way to do asynchronous file upload?

Regards,
Vijay Raajaa GS

**Comment by hqy** [comment]
aiofiles

**Comment by r0fls** [comment]
This should already be available in sanic via https://github.com/channelcat/sanic/pull/697. See https://github.com/channelcat/sanic/issues/546 for a similar discussion. Closing this since for now for that reason, please feel free to reopen if this is still a concern or bring the discussion to #546.
