### ISSUE TITLE
How to give alias name as DNS url to the ip and port configured in main.py

### ISSUE THREAD

**Issue by sunbarve** [channelcat/sanic#825]
Hello All,
How to give alias name as DNS url to the ip and port configured in main.py
 if __name__ == "__main__":
    app.run(host="0.0.0.0", port=8000)
so we can access it from alias DNS url.

In nginx server we can give alias name like www.example.com for access the application. 

Thank you,

**Comment by yunstanford** [comment]
Sanic is application server, nginx is more like proxy server. 

In reality, the common pattern is Nginx+ Sanic(gunicorn) etc.

**Comment by sunbarve** [comment]
Hello @yunstanford , Can you give me details information about how to use Nginx+Sanic.

**Comment by yunstanford** [comment]
Basically, just running Nginx as reverse proxy in front of your Sanic application. I'd also suggest use gunicorn to run your Sanic application as well.

request => Nginx => Gunicorn(Sanic)

**Comment by sunbarve** [comment]
Solved my problem,thanks.

**Comment by sunbarve** [comment]
so close this ticket.
