### ISSUE TITLE
How to use Aiocassandra with Sanic using multiple workers?

### ISSUE THREAD

**Issue by vnnw** [channelcat/sanic#827]
I would like to use Sanic with Aiocassandra (https://github.com/wikibusiness/aiocassandra). But I cannot figure out how to successfully deploy it with multiple workers.

Here is a part of my code:

```python
cluster = Cluster()
cassandra_session = cluster.connect()

# http://sanic.readthedocs.io/en/latest/sanic/middleware.html?highlight=listener#listeners
@app.listener('before_server_start')
def init_cassandra_session(app, loop):
    aiosession(cassandra_session, loop=loop)

cql = "SELECT * FROM db WHERE id=?"
prepared = cassandra_session.prepare(cql)

@app.route('/')
def my_route(request):
    # Cassandra query and return result

if __name__ == "__main__":
  app.run(host="0.0.0.0", port=8000, debug=True, workers=4)
```
When I set more than one workers, the query seems got stuck and won't return any results. 
But when I change the number of workers to 1, the server works fine.

Is there anything I did wrong here?

**Comment by yunstanford** [comment]
Where do you `import Cluster` ?

Can you try to move `cluster = Cluster()` to init_cassandra_session inside ?

**Comment by vnnw** [comment]
Thanks to @yunstanford .
I did try to move **cluster = Cluster()** to **init_cassandra_session**. 
But when I start the web server, the program will complain a NameError: name 'cassandra_session' is not defined in line "prepared = cassandra_session.prepare(cql) ".

**Comment by yunstanford** [comment]
Yeah, you should move that as well if you moved`cluster = Cluster()`

**Comment by vnnw** [comment]
I did move all Cluster() related codes into init_cassandra_session  function.
But when I make a request, the server complain that name 'cassandra_session' is not defined.

```python
@app.listener('before_server_start')
def init_cassandra_session(app, loop):
    cluster = Cluster()
    cassandra_session = cluster.connect()
    aiosession(cassandra_session, loop=loop)
    cql = "SELECT * FROM db WHERE id=?"
    prepared = cassandra_session.prepare(cql)

@app.route('/')
def my_route(request):
    # Cassandra query and return result
```

Using below codes, I can make the server work, but cannot start it up with multiple workers.

```python
cluster = Cluster()
cassandra_session = cluster.connect()

@app.listener('before_server_start')
def init_cassandra_session(app, loop):
    aiosession(cassandra_session, loop=loop)

cql = "SELECT * FROM db WHERE id=?"
prepared = cassandra_session.prepare(cql)

@app.route('/')
def my_route(request):
    # Cassandra query and return result
```
Any thoughts?

**Comment by vnnw** [comment]
I try to run Sanic with Aiocassandra via Gunicorn in multiple workers mode. 
It seems working fine so far.
Thank you @yunstanford anyway.

**Comment by yunstanford** [comment]
You may wanna make your Cluser/Connection pool as app attribute, then you can use that for querying in your handler. I don't see you set any attribute in your init listener, i don't know how you can perform query in your handler either..

Back to your question, I was guessing that you were sharing same event loop reference in multiple processes(or same epoll instance under the hood).

**Comment by vnnw** [comment]
Thank you @yunstanford .
It is my bad that I did not make Connection as app attribute,  I thought it is some kind of global variables.
I rewrote my code and it seems working now!
I hope I wrote it right this time. Below is my currently working code snippet:

```python
@app.listener('before_server_start')
async def init_cassandra_session(app, loop):
    app.cluster = Cluster()
    app.cassandra_session = app.cluster.connect()
    aiosession(app.cassandra_session, loop=loop)
    cql = "SELECT * FROM db WHERE id=?"
    app.prepared = app.cassandra_session.prepare(cql)

@app.listener('after_server_stop')
def init_cassandra_session(app, loop):
    app.cluster.shutdown()

@app.route('/')
def my_route(request):
    # Cassandra query and return result
```

**Comment by AyWa** [comment]
Not sure if it is the correct place to ask that, but if the code is in `before_server_start` it will be call `X times` with X the numbers of workers right ? 

So if the code need to create thread for example, any better way to create only one thread and share it in `@app.listener('before_server_start')` for all the workers ?

**Comment by Tronic** [comment]
@AyWa No, this is not the right place. But still, `before_server_start` and `after_server_stop` are executed separately in each worker process, and thus you can use them for making (multiple) database connections. If you need something initialised only once, in the main process, put it in your main function, after `multiprocessing.freeze_support()`.
