### ISSUE TITLE
When will be the next release ?

### ISSUE THREAD

**Issue by lcDotcom** [channelcat/sanic#830]
When will be the next release ?

**Comment by yunstanford** [comment]
also curious, master branch fixed a bunch of issues and added some features. any update for next release ?

**Comment by lcDotcom** [comment]
Any update ?

**Comment by webwurst** [comment]
All issues for milestone [`0.6.0`](https://github.com/channelcat/sanic/milestone/10) seem to be done..

**Comment by seemethere** [comment]
The next release will be sometime this week. Sorry have been busy with work and just haven't had the free time to do a release.

**Comment by webwurst** [comment]
Done ✅ https://github.com/channelcat/sanic/releases
Thx @seemethere \o/
