### ISSUE TITLE
about performance benchmarks

### ISSUE THREAD

**Issue by kolapapa** [channelcat/sanic#835]
```
$ wrk -t4 -c1000 -d60s http://localhost:1337/
Running 1m test @ http://localhost:1337/
  4 threads and 1000 connections
  Thread Stats  Avg      Stdev     Max   +/- Stdev
    Latency   178.75ms   24.52ms   1.09s    83.85%
    Req/Sec     1.50k   609.06     2.53k    68.07%
  334665 requests in 1.00m, 40.85MB read
Requests/sec:   5569.94
Transfer/sec:    696.24KB
```
**how to get yours answer, like** 

Server | Implementation  | Requests/sec | Avg Latency
----- | -------------| --------|--------
Sanic   | Python 3.5 + uvloop | 33,342   | 2.96ms

**Comment by kolapapa** [comment]
this is about my code
```
from sanic import Sanic
from sanic.response import json


app = Sanic(__name__)

@app.route("/")
async def test(request):
    return json({"hello":"world"})


app.run(host="0.0.0.0", port=1337)
```

**Comment by yunstanford** [comment]
Two gotchas:
1. Handling 1000 connections simultaneously is really expensive... especially, those connections are on the application server(1 process) directly... In reality, it should never happen.
2. It may be the bottleneck from your test client side... 4 threads ? 

I am not familiar with wrk. @r0fls @seemethere may have more context.

**Comment by r0fls** [comment]
Uh oh, 😢  @messense @seemethere it looks like logging gives us a big hit. It looks like the way to achieve faster speeds right now is to disable it:

```python
from sanic import Sanic
from sanic.response import json


app = Sanic(__name__)

@app.route("/")
async def test(request):
    return json({"hello":"world"})

app.run(log_config=None)
```

There may be a middle ground but I'm not aware of it.


Also that results in this:

```
$ wrk -t50 -c200 -d10s http://localhost:8000
Running 10s test @ http://localhost:8000
  50 threads and 200 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     7.67ms    2.29ms  18.01ms   63.95%
    Req/Sec   523.66     86.99     1.49k    81.08%
  261346 requests in 10.04s, 31.90MB read
  Socket errors: connect 0, read 27, write 0, timeout 0
Requests/sec:  26028.42
Transfer/sec:      3.18MB
```

So still less than advertised. We've seen some slow down as we've fixed bugs and added features since the initial release, which is when those benchmarks were taken.

**Comment by yunstanford** [comment]
hmm.. i'd like to see why logging hurts so much.

**Comment by seemethere** [comment]
File IO is always an expensive operation.

**Comment by yunstanford** [comment]
Yeah, that's ture. Do you have the number for benchmark with logging.

**Comment by yunstanford** [comment]
anyway, i'd like sending logs to a broker instead of local disk logging.

**Comment by r0fls** [comment]
I vote we close this issue with https://github.com/channelcat/sanic/pull/839. We should open a new issue to discuss disabling the access log by default and rerunning the updated benchmarks.

**Comment by seemethere** [comment]
I'm for that, @r0fls would you mind opening up the issue?

**Comment by aohan237** [comment]
@r0fls  i use  your code to run test .
but the result as follows:
wrk -t50 -c200 -d10s http://localhost:8000
Running 10s test @ http://localhost:8000
  50 threads and 200 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   145.08ms  181.44ms 880.47ms   82.28%
    Req/Sec    89.21     59.54   699.00     52.07%
  27047 requests in 10.09s, 3.30MB read
Requests/sec:   2680.74
Transfer/sec:    335.09KB

still disappointing.
so  why is the problem, use the latest sanic edition.

**Comment by Epsilon10** [comment]
50 threads??!! I feel  thats kinda overdoing it
