### ISSUE TITLE
Better to have changelog in the document

### ISSUE THREAD

**Issue by lixxu** [channelcat/sanic#836]
I think it's a better idea to have the changelog in the document, then we can know the changes between released versions.

**Comment by seemethere** [comment]
The changelog is currently maintained in the release section of GitHub. Maybe a link to the release page would be applicable in the docs?

**Comment by lixxu** [comment]
aiohttp seems good ([http://aiohttp.readthedocs.io/en/stable/changes.html](http://aiohttp.readthedocs.io/en/stable/changes.html)

**Comment by lixxu** [comment]
I'm working on adding the release notes section to the document, and will make a PR.

**Comment by lixxu** [comment]
PR was pulled, please review.
