### ISSUE TITLE
Sanic header checks are case-sensitive when uploading files

### ISSUE THREAD

**Issue by chanind** [channelcat/sanic#841]
Sanic determines if a request has a file upload by doing a case-sensitive comparison of form header fields using the following code in `request.py`:
```
if form_header_field == 'Content-Disposition':
  if 'filename' in form_parameters:
    file_name = form_parameters['filename']
    field_name = form_parameters.get('name')
  elif form_header_field == 'Content-Type':
    file_type = form_header_value
```
Headers are supposed to be case-insensitive, so this is currently breaking when a file is uploaded using React Native which lowercases these header names.

In case it's useful to anyone else, in the meantime I'm running the following in a middleware to fix the casing:
```
request.body = request.body.replace(b'content-type', b'Content-Type')
request.body = request.body.replace(b'content-disposition', b'Content-Disposition')
```

Related to https://github.com/channelcat/sanic/issues/126

**Comment by yunstanford** [comment]
yes, it's a bug, it should be case-insenstive check.
