### ISSUE TITLE
How to pass loop to test request?

### ISSUE THREAD

**Issue by tonal** [channelcat/sanic#842]
``` python
sanic.test_client.get(url, loop=loop) # Do not work
```

**Comment by yunstanford** [comment]
try pass in `server_kwargs = { 'loop': MyEventLoop}`

are you wanna use your own event loop for testing ? if so, make sure that your event loop is consistent everywhere.

If you're using pytest, you can take a look https://github.com/yunstanford/pytest-sanic for easy testing.

**Comment by r0fls** [comment]
@tonal please reopen this if you're still having issues and need more help.

**Comment by pacefalm** [comment]
@r0fls is this still the correct way to pass a loop to my test_client requests? I believe passing a loop to app.run() was removed here https://github.com/channelcat/sanic/pull/335.
