### ISSUE TITLE
Is it possible to define handler_name for route/add_route

### ISSUE THREAD

**Issue by lixxu** [channelcat/sanic#857]
Current handler_name comes from `handler.__name__`. Is it possible to be set by user if handler_name passed to `add_route`?

I'm working on a project that use one blueprint for one sub-app. If handler_name can not be defined,
the codes have to be like:
```
# views/users.py
from subapp import bp

async def users_index(request):
    # codes here

# views/projects.py
from subapp import bp
async def projects_index(request):
    # codes here

# subapp/__init__.py
import views.users as users
import views.projects as projects

bp.add_route(users.users_index, '/users')
bp.add_route(projects.projects_index, '/projects')
```
If handler_name can be user defined, I can use `index` in all views:
```
# /views/users.py
from subapp import bp

async def index(request):
    # codes here

# views/projects.py
from subapp import bp
async def index(request):
    # codes here

# subapp/__init__.py
import views.users as users
import views.projects as projects

bp.add_route(users.index, '/users', hanlder_name='subapp.users.index')
bp.add_route(projects.index, '/projects', handler_name='subapp.projects.index')
```
Not sure is `subapp.users.index` is valid or not.

**Comment by lixxu** [comment]
@r0fls is this possible? I can help make a PR. or I'll close it.

**Comment by r0fls** [comment]
@lixxu this looks possible, but why not just set `users.index.__name__ = 'subapp.users.index'`

**Comment by lixxu** [comment]
thx, I'll try.

**Comment by r0fls** [comment]
However @lixxu I do think it would be a useful feature, and encourage you to create a PR with it and an addition to the docs on how to use it. It looks like it would be easier this way. I only knew to do that because I dug into the source code :) So, if it's at all common or leads to cleaner code, better to support it directly i think.

**Comment by r0fls** [comment]
I'm sure you've already found it, but you'd need to modify https://github.com/channelcat/sanic/blob/master/sanic/router.py#L238-L245

To respect a parameter passed by the `add_route` functions, shorthands, and BP versions (or maybe it would only make sense for blueprints?)

**Comment by lixxu** [comment]
ok, will do it later.

**Comment by lixxu** [comment]
yes, but also need to modify other functions too (to pass `handler_name`).

**Comment by lixxu** [comment]
already merged.
