### ISSUE TITLE
Running tasks in background

### ISSUE THREAD

**Issue by amitripshtos** [channelcat/sanic#86]
Hey, awesome job!
I would like to know if it`s possible to run tasks in the background (the tasks of course must be async).

For examples:
1. I want a task that runs every 1 minute and do a REST request and save the results in global variables (so my REST endpoints will use that "cached" data)

2. I want to read from kafka topic and save the latest result in a global variable (so my REST endpoints will use that "cached" data)

Is that possible and how do you recommend me to do that?
Thanks!

**Comment by imbolc** [comment]
It seems like you're looking for [asycnio.Task](https://docs.python.org/3.6/library/asyncio-task.html#task)

**Comment by amitripshtos** [comment]
I can use Task, but the question if where I attach the task into the event loop / uvloop.
I want the task to run in the background - no related to requests

**Comment by imbolc** [comment]
Ah, I understand now. You can explicitly pass `loop` into server. It isn't possible with current pip release, so you need github version of sanic.
```
loop = uvloop.new_event_loop()
asyncio.set_event_loop(loop)

asyncio.Task(your_task())
app.run(..., loop=loop)
```

**Comment by amitripshtos** [comment]
Awesome, thanks! Hope to see this change in pypi
