### ISSUE TITLE
console has print log is :(network)[INFO]:

### ISSUE THREAD

**Issue by moonerTT** [channelcat/sanic#865]
where I send a resquest,always print that's log in console,Who can tell me that's why?

**Comment by yunstanford** [comment]
it has default log handler. you can disable that by
```python
app = Sanic(log_config=None)
```
But i'm thinking we should do some refactoring around logging in general. I feel like the logging design is not very good.

**Comment by moonerTT** [comment]
@yunstanford I am  using the Logging config of mine.Can I remove this:
```text
    'network': {
            'handlers': ['console'],
            'level': 'DEBUG',
            "encoding": "utf8"
```
in the 'loggers'?

**Comment by yunstanford** [comment]
simply removing `logger` may not work, because it defines loggers in `log.py` anyway as long as the `log_config is not None` and `network logger` will be used anyway.

You could utilize `logging.disable` as a workaround.

The logging pattern is not very good anyway. NEEDS some refactoring work.

**Comment by moonerTT** [comment]
OK,thanks for u answer
