### ISSUE TITLE
Running async server no longer triggers events

### ISSUE THREAD

**Issue by furious-luke** [channelcat/sanic#884]
Hi there, I've noticed that there has been a change somewhat recently whereby a server created via `app.create_server` now no longer triggers events. The source of the difference is here, in `server.py`:

```python
    if run_async:
        return server_coroutine

    trigger_events(before_start, loop)
```

The `serve` function returns prior to triggering any events. Just wondering whether this was intended or not? And if so, why? I have some testing code I use that depended on running a server in the background and having the events triggered. I'm sure I can update it, but just wanted to confirm this is the intended behaviour.

Thanks!

Edit: If this is intended, would you be able to recommend the correct way to launch events for a background server?

**Comment by yunstanford** [comment]
It was bug before, it would trigger events twice when starting gunicorn worker. That's the reason we move the code. 

Also, `trigger_events(before_start, loop)` is sort of `sync` way for triggering events. I am thinking when we start server asynchronously, we should also trigger events asynchronously.

I will push a quick fix.

**Comment by furious-luke** [comment]
@yunstanford Thanks for the quick response! Please don't feel rushed, I've got a workaround that is easy enough for my case, so there's no rush.

I'm not using `app.create_server` for production usage, just for testing purposes. I've combined it with `asynctest`, seems to be working reasonably well at the moment.

Thanks again!
