### ISSUE TITLE
Maybe we can let users choose whether `merge_route` or not?

### ISSUE THREAD

**Issue by zhustec** [channelcat/sanic#895]
I use Ruby on Rails before, I like the resourcesful router in Rails, so I try to do the same thing in Sanic.

```python
bp = sanic.Blueprint('posts', url_prefix='posts')

@bp.get('/<post_id>')
async def show(request, post_id):
    pass

@bp.patch('/<post_id>')
async def update(request, post_id):
    pass

@bp.delete('/<post_id>')
async def delete(request, post_id):
    pass
```
But when I use `url_for('posts.update', post_id=post.id)`, It shows `Error: Endpoint with name posts.update was not found`.

Then I found it will `merge_route` into `CompositionView` as it change router name to `posts.show`, it is exactlly not what I want. Maybe we can disable `merge route` by given an options to user?

https://github.com/channelcat/sanic/blob/master/sanic/router.py#L194-L214

**Comment by r0fls** [comment]
I don't think it's necessary to disable merge routes, we just need to refer to the same routes in overlapping cases like this.

**Comment by r0fls** [comment]
So, since the URL was the same for either, it should have just returned the `post.show` route when requesting the `post.update` route.

**Comment by zhustec** [comment]
It is not overlapping, it has different request method, what is important is that it has very different meanings.

```text
GET             /posts/<post_id>                            # It means show a post, so we use `posts.show`
PATCH              /posts/<post_id>                          # It means update a post, so we use `posts.update` instead of use `posts.show` since it will be confuse
DELETE           /posts/<post_id>                            # Same above
```

**Comment by r0fls** [comment]
Yes, of course they're different methods with different meanings. However they are the same url, which is what `url_for` needs to return, right? 🤔

**Comment by r0fls** [comment]
My point is that as long as `url_for` returns the correct url for those parameters (`'posts.update', post_id=post.id)`, then it shouldn't matter what the router is doing under the hood.

**Comment by r0fls** [comment]
Then again, url_for is using `find_route_by_view_name` which just relies on the routes... so maybe have to disable merging :/

**Comment by zhustec** [comment]
In HTML5, we use `aside`, `main`, `article`, `header`, `footer`, etc. rather than simply `div`.

True, the return values are the same. 

```html
<form method="post" action="{{ url_for('posts.update', post_id=post.id) }}">
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
```

In the code above, it can be simply realized that we are updating a post at first glance, bu if we change it to `posts.show`, I suppose maybe we need more time to realize it.

**Comment by r0fls** [comment]
Yep, I'm not saying you should just use `posts.show`.  I'm just saying in sanic `url_for`, as long as it returns the correct route with `posts.update` that should be fine.

Anyway, `merge_route` doesn't seem to be used anywhere 😑 

```
$ grep merge_route ./
sanic/router.py
194:        def merge_route(route, methods, handler):
233:            route = merge_route(route, methods, handler)
```

**Comment by r0fls** [comment]
@subyraman since you added `url_for`, maybe you have some ideas here?

**Comment by zhustec** [comment]
It does use `merge_route`.

https://github.com/channelcat/sanic/blob/master/sanic/router.py#L233
