### ISSUE TITLE
default strict_slashes

### ISSUE THREAD

**Issue by kianxineki** [channelcat/sanic#897]
I have seen that all strict_slashes are False, is it possible to change the default to True? Maybe it could be an argument from app.config

**Comment by zhustec** [comment]
+1. Same needed.

**Comment by yunstanford** [comment]
Changing the default value may break current Sanic application, you can easily pass `strict_slashes=True` when you define your routes.

**Comment by r0fls** [comment]
I think they just want to be able to _set_ the default value, so to avoid passing it to each route. This seems reasonable to me.

**Comment by yunstanford** [comment]
yeah, i see its value, maybe allow to pass a keyword `strict_slashes` when initializing app or blueprints.
i can push a quick fix.

**Comment by zhustec** [comment]
@yunstanford Maybe set in 'app.config' instead of keywords arguments is better?

**Comment by zhustec** [comment]
@yunstanford Maybe set in 'app.config' instead of keywords arguments is better?

**Comment by yunstanford** [comment]
I am thinking this feature should also apply to `blueprints`, `app.config` doesn't work for that. I can think of a use case, like, different bp could have different default `strict_slashes`  values
```python3
app = Sanic()
bp1 = Blueprint('bp1', strict_slashes=False)
bp2 = Blueprint('bp1', strict_slashes=True)
```
