### ISSUE TITLE
Sanic exceptions

### ISSUE THREAD

**Issue by NikosVlagoidis** [channelcat/sanic#914]
How does sanic exceptions are supposed to work? The docs states that 

> Exceptions can be thrown from within request handlers and will automatically be handled by Sanic. Exceptions take a message as their first argument, and can also take a status code to be passed back in the HTTP response.

This is my route
```python
@app.route("/")
async def test(request):
    abort(401)
```

When I make a request on the path I get a response of : 

>Internal Server Error
The server encountered an internal error and cannot complete your request.

`2017-08-24 10:18:43 - (sanic)[ERROR]: Traceback (most recent call last):
  File "/home/nikos/.virtualenvs/3.6/lib/python3.6/site-packages/sanic/app.py", line 503, in handle_request
    response = await response
  File "/home/nikos/Desktop/Side Projects/micro/test2.py", line 15, in test
    abort(401)
  File "/home/nikos/.virtualenvs/3.6/lib/python3.6/site-packages/sanic/exceptions.py", line 262, in abort
    raise sanic_exception(message=message, status_code=status_code)
TypeError: __init__() missing 1 required positional argument: 'scheme'`

Also after a bit the connection times out and the log trace is 

`2017-08-24 10:18:43 - (network)[INFO][127.0.0.1:34734]: GET http://0.0.0.0:8001/  500 144
2017-08-24 10:19:43 - (sanic)[ERROR]: Traceback (most recent call last):
  File "/home/nikos/.virtualenvs/3.6/lib/python3.6/site-packages/sanic/server.py", line 143, in connection_timeout
    raise RequestTimeout('Request Timeout')
sanic.exceptions.RequestTimeout: Request Timeout`

**Comment by CharAct3** [comment]
There might be a bug with `abort(401)`.

The `Unauthorized` exception requires an argument `scheme`, but `SanicException` doesn't.

You can try:
```
@app.route("/")
async def test(request):
     raise Unauthorized("Unauthorized", "Basic")
```

or 

```
@app.route("/")
async def test(request):
    abort(400)
```

**Comment by NikosVlagoidis** [comment]
Actually, I was just testing it. Yes, the Unauthorized exception needs a scheme argument .From source code: 

```python 
    def __init__(self, message, scheme, **kwargs):
        super().__init__(message)

        values = ["{!s}={!r}".format(k, v) for k, v in kwargs.items()]
        challenge = ', '.join(values)

        self.headers = {
            "WWW-Authenticate": "{} {}".format(scheme, challenge).rstrip()
        }
```
This might be a solution?

```python 
    def __init__(self, message, scheme=None, **kwargs):
```
