### ISSUE TITLE
Windows doesn't have `syslog` module

### ISSUE THREAD

**Issue by zhustec** [channelcat/sanic#915]
This doesn't make sense, since there is no `syslog` module in Windows, why import it directly, maybe try to import is better.

https://github.com/channelcat/sanic/blob/fee9de96dec787ff5b5ca474adc38ea8bbe6a62d/sanic/config.py#L3

https://github.com/channelcat/sanic/blob/fee9de96dec787ff5b5ca474adc38ea8bbe6a62d/sanic/config.py#L65-L81

https://github.com/channelcat/sanic/blob/fee9de96dec787ff5b5ca474adc38ea8bbe6a62d/sanic/config.py#L94-L99

**Comment by jrocketfingers** [comment]
This has been resolved in https://github.com/channelcat/sanic/pull/947
