### ISSUE TITLE
Delete `ujson` and `uvloop` from requirements.txt

### ISSUE THREAD

**Issue by zhustec** [channelcat/sanic#916]
`ujson` and `uvloop` are not nessesary for sanic, so maybe we can delete them from requirements.txt, and give a message to user to manually install them for faster running?

https://github.com/channelcat/sanic/blob/7b66a56cad9820b3172850fde9a61f0cb865dcf5/sanic/response.py#L4-L7

https://github.com/channelcat/sanic/blob/eb06e6ba51b493f871d71dbddd9c7b4271e799b4/sanic/server.py#L22-L25

**Comment by zhustec** [comment]
#855

**Comment by yunstanford** [comment]
httptools may still not work on Windows. But I don't have a windows machine, so can't test it out.

**Comment by zhustec** [comment]
True, currently it sill not work on Windows, but why not try to make it work on Windows step by step.

**Comment by abuckenheimer** [comment]
I'm a fan of the batteries included but swap-able design. People who come to sanic for the purported speed may be dissuaded when it doesn't work as advertised out of the box.

**Comment by rdehouss** [comment]
I understand your point, but for example, `ujson` is not a drop-in replacement for `json` and it might lead to issues, so, at least, when it's not 100% compatible, it shouldn't be forced.
So far, I'm obliged to `pip install sanic && sanic -y uninstall ujson` which is kind of stupid :)

**Comment by abuckenheimer** [comment]
my intuition is that something like ujson and uvloop in general should be [extras](http://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies). That way you could ```pip install sanic``` or ```pip install sanic[uvloop]``` or ```pip install sanic[all]``` which has the opt in your looking for. But the project has a stated "[main goal](http://sanic.readthedocs.io/en/latest/sanic/contributing.html#warning)" of speed so I think its probably more in line with the project to be an opt-out feature a la ```SANIC_NO_UJSON=true pip install sanic```.

**Comment by rdehouss** [comment]
The sad thing is that SANIC_NO_UJSON=true is not taken into account because in requirements.txt
And there are no solution in pip right now to be able to avoid that.

**Comment by abuckenheimer** [comment]
yea that's annoying :disappointed:, in some senses this is a pip ergonomics problem, it's possible this could be alleviated with [conda features](https://conda.io/docs/user-guide/tasks/build-packages/features.html). I think someone started the process of making a conda package here #848

**Comment by messense** [comment]
We might be able to take advantage of [PEP 508 -- Dependency specification for Python Software Packages](https://www.python.org/dev/peps/pep-0508/).

*requirements.txt*:

```
ujson; sys_platform != 'win32'
uvloop; sys_platform != 'win32'
```

But upgrading to newer pip version might be required.

**Comment by Atagait** [comment]
Making uvloop and ujson optional would be appreciated. Even though I plan to run my app on a linux machine, being able to work on windows would be a great boon.

**Comment by danpalmer** [comment]
👍

My app has just started segfaulting due to `ujson`, so the ability to easily not use it would be appreciated.

**Comment by skewty** [comment]
We develop on **Windows** and deploy on **Linux**.  I too would like to see `ujson` and `uvloop` moved to **opt**.

Simply include some logger.warning() calls if `uvloop` and or `ujson` are not available at startup mentioning that Sanic will not performing at its potential speed until they are installed.

**Comment by akrylysov** [comment]
I would love to get `uvloop` and `ujson` removed from requirements.txt, these libraries are not compatible with PyPy3.

**Comment by abuckenheimer** [comment]
He folks, wanted to give a gentle prod to some of the folks on this thread to see if anyone else could try `pip install`-ing or providing feedback on #1117 .

**Comment by marcstreeter** [comment]
I thought ujson *was* compatible with python 3 — at least that’s what http://py3readiness.org <http://py3readiness.org/> says.  Maybe this is a bad resource for determining python 3 compatibility.  Now that’s not to say that ujson should remain in the requirements.txt file.

**Comment by abuckenheimer** [comment]
@marcstreeter I think py3readiness is specific to cpython, when @akrylysov mentions pypy3 I think he's talking about https://pypy.org/ which is going to have completely different compatibility from cpython

**Comment by marcstreeter** [comment]
lol- I can't read it seems.  I had in fact just deleted my comment because I noticed he put "PyPy3" and not Python 3.

**Comment by zhustec** [comment]
Glad to see that, thanks.
