### ISSUE TITLE
how to can get current_app ？

### ISSUE THREAD

**Issue by Feeeenng** [channelcat/sanic#921]
Flask get current app is 
from flask import current_app

How to can get 'current_app'  in Sanic ?

**Comment by CharAct3** [comment]
ref #913

You can use `request.app` in a handler function to access it.

**Comment by Feeeenng** [comment]
@CharAct3  
from sanic import request

current_app = request.app

AttributeError: module 'sanic.request' has no attribute 'app'

**Comment by CharAct3** [comment]
```python
@app.route("/")
async def test(request):
    current_app = request.app
    return json({"hello": "world"})
```

**Comment by Feeeenng** [comment]
@CharAct3 but some function is outside use. not only is inside request . l hope is :
``` python
from sanic import request
def test():
     current_app = request.app
     return current_app.id

@app.route('/)
async def index(request):
        id = test()
        return json({"id",id})
```

**Comment by yunstanford** [comment]
You can always pass `app` as function param. 

maybe helpful, https://github.com/channelcat/sanic/issues/845

**Comment by Feeeenng** [comment]
@yunstanford  thx. next question !
from flask import session .
In sanic . how to  use  the ?

**Comment by yunstanford** [comment]
Sanic doesn't have builtin session support, but you can use extension, https://github.com/subyraman/sanic_session, similar to https://pythonhosted.org/Flask-Session/

**Comment by Feeeenng** [comment]
@yunstanford  how to use @wrapp ？
```
def func_app(reuqest):
    def func(f):
        @waprs(f):
         def wrapper(*a,**b):
                  current_app = request.app
                  return current_app.id
        reuturn warapper
   def func

@func_app(request)
@app.route('/):
async def indx(request):
           return 'test'           
```
use func_app function , 'reqeust' is not use !

**Comment by jrocketfingers** [comment]
@r0fls, @seemethere, @messense, @yunstanford, can we close the Q&A types of issues? This is becoming a lot like an IRC log and it's getting harder to track real issues. Hell, if it was gitter/IRC/slack I might even be so inclined to answer those as well.

@yunstanford please don't think I don't appreciate your perseverance in answering all of the questions, though. I'm just thinking you could get paid in SO reputation :)

**Comment by r0fls** [comment]
Since the question has diverged, I agree we should close this. Please keep questions within issues restricted to Sanic specifics in general.

**Comment by jrocketfingers** [comment]
I'm not sure that closing questions one by one upon divergence would cut it. Maybe we should redirect them to `sanic` tag on SO and start watching that? We could end up getting free moderation and editing from the ever present mods there - and just wrapping people's code/output in code segments would be enough.

In the meantime, I'll try to answer some of those so we can start closing them here.

**Comment by Feeeenng** [comment]
please close question. the question has been resolved .

**Comment by r0fls** [comment]
@jrocketfingers I think it's ok to ask Sanic related questions in the issues, we have the questions tag for it. However the issues are definitely ballooning, which is a problem.

**Comment by jrocketfingers** [comment]
Open an issue about issues balooning! :) Jokes aside, yeah, a question
label would help tremendously, as I'm just looking for a way not to drown
things like `found a memory leak` in a bunch of questions. Other than that,
yeah, I agree that Sanic's is still too small a community to necessitate
the split between but tracking and questions.

**Comment by OuIChien** [comment]
When you instantiate a Sanic instance, that can be retrieved at a later time from the Sanic app registry. This can be useful, for example, if you need to access your Sanic instance from a location where it is not otherwise accessible.

Here you go:
`# ./path/to/server.py
from sanic import Sanic

app = Sanic("my_awesome_server")

# ./path/to/somewhere_else.py
from sanic import Sanic

app = Sanic.get_app("my_awesome_server")
`
