### ISSUE TITLE
response.stream doesn't do what it says on the tin.

### ISSUE THREAD

**Issue by savvopoulos** [channelcat/sanic#934]
The following example doesn't work as expected, in Chrome. I would have expected it to first return "foo" and then return "bar" to the client, some time later, but in my tests, it doesn't. Instead, in Chrome, it just returns the whole response at once.
On the other hand, `curl -N localhost:8000` does do the right thing...

```
from sanic import Sanic
from sanic.response import stream
import asyncio


app = Sanic(__name__)

@app.route("/")
async def test(request):
    async def sample_streaming_fn(response):
        response.write('foo\n')
        await asyncio.sleep(1)
        response.write('bar')
    return stream(sample_streaming_fn)

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=8000)
```

**Comment by savvopoulos** [comment]
Other things I tried:
* disable keep alive: `from sanic.config import Config; Config.KEEP_ALIVE = False`
* `headers={'Transfer-Encoding':'chunked'}`

**Comment by jrocketfingers** [comment]
Chrome is apparently capable of remote code optimization/JITing. So that's how they have load times that fast 🤔

**Comment by ashleysommer** [comment]
@savvopoulos 
Does chrome show both `'foo'` and `'bar'` instantaneously, or both after one second?

I believe you are seeing the behaviour described in this StackOverflow question:
https://stackoverflow.com/questions/35073009/disabling-chrome-buffering-when-streaming-text-data

Chrome has a 1024 byte response buffer. It tries to fill this buffer from the stream, before displaying the content. From the answer on that site, it appears that if you change your response type from `text/plain` to `application/octet-stream`, it will cause chrome to bypass the buffer and will stream the response directly to the page.

**Comment by ashleysommer** [comment]
>  things I tried:
>
>    * disable keep alive: from sanic.config import Config; Config.KEEP_ALIVE = False
>    * headers={'Transfer-Encoding':'chunked'}

A streaming response should already set the `"Transfer-Encoding":"chunked"` header automatically for you.

**Comment by savvopoulos** [comment]
> Does chrome show both 'foo' and 'bar' instantaneously, or both after one second?
Both after one second.

> https://stackoverflow.com/questions/35073009/disabling-chrome-buffering-when-streaming-text-data
I did try to find out why Chrome does this but couldn't. So thank you for posting this!
