### ISSUE TITLE
Request is immutable but provides no way to use middleware to do the equivalent of set a thread local.

### ISSUE THREAD

**Issue by dpnova** [channelcat/sanic#937]
Obviously thread locals are useless (and dangerous in general). But it would be nice to be able to add some extra context to a request with middleware. It's hard to do now because of the slots restriction. Surely we could have the performance AND flexibility by adding some sort of context attribute to a request?

**Comment by dpnova** [comment]
Ah I just noticed request is a dict. It's not clear that that's used for.. I guess I could use it like that?

**Comment by jrocketfingers** [comment]
Been using it like that for a while. The way I see it, that's the only way to enrich requests through middleware. Lets keep doing that unless we shoot ourselves in the foot, and then come back here to lick our wounds?

In any case, let's close this for now?

**Comment by dpnova** [comment]
Agreed
