### ISSUE TITLE
Support blueprint static files per vhost

### ISSUE THREAD

**Issue by omerbn** [channelcat/sanic#949]
Right now, static files/folders (using app.static or bp.static) are served for all vhost.
I'd like Sanic to support static assets per vhost.

**Comment by r0fls** [comment]
thanks for reporting it, feel free to open another issue if you see any problems

**Comment by r0fls** [comment]
ah, darn i missed bp.static 🤕

**Comment by r0fls** [comment]
Actually the previous PR works for blueprints too. Feel free to reopen this if you see any issues.
