### ISSUE TITLE
Example of using async requests

### ISSUE THREAD

**Issue by peterbe** [channelcat/sanic#96]
I actually don't know if it requires a custom requests library or if it's something that can be done "natively" with sanic, but being able to do requests queries async would be awesome. Then you don't have to worry about blocking when doing a sloooow `requests.post(...)`.
Also, something I'm personally interested in, is the ability to use elasticsearch in an async matter.

**Comment by argaen** [comment]
For elasticsearch you can use https://github.com/aio-libs/aioes.

For async http requests, `aiohttp` support this, until sanic supports it maybe you can use its http client (I'm not aware if there is another library doing this).

**Comment by jackfischer** [comment]
Just sent a pull request! #119

**Comment by EFF** [comment]
Seems like this issue should be closed now.

* async request question is answered
* es related question is answered
* example has been provided and merged

**Comment by seemethere** [comment]
closed with #119
