### ISSUE TITLE
is there a 2.7 python version?

### ISSUE THREAD

**Issue by rlam3** [channelcat/sanic#963]
is there a 2.7 python version?

**Comment by davidtgq** [comment]
No. Don't think there ever will be unless python 2.7 magically grows async support.

> Sanic is a Flask-like Python ** 3.5+** web server

**Comment by yunstanford** [comment]
You can try `tornado` if you wanna an async framework in python2.

**Comment by r0fls** [comment]
Not only is sanic not supported for 2.7, it's also not supported on Python versions older than 3.5. This is intentional and will not change.
