### ISSUE TITLE
Websockets connections receiving "Response Timeout"

### ISSUE THREAD

**Issue by furious-luke** [channelcat/sanic#969]
Hi there, I'm finding that websockets connections are getting cancelled from the server as a result of a 60 second timeout. The error looks like this:

```bash
[2017-10-11 14:43:54 +1100] [11644] [ERROR] Traceback (most recent call last):
  File ".../sanic/sanic/server.py", line 178, in response_timeout_callback
    raise ServiceUnavailable('Response Timeout')
sanic.exceptions.ServiceUnavailable: Response Timeout
```

This issue can be reproduced with a simple server like this:

```python
import time
from sanic import Sanic
from sanic.response import json

app = Sanic()

@app.websocket('/')
async def test(request, ws):
    time.sleep(120)
    ws.send('hello')

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=8000)
```

And a client like this:

```python
import asyncio
import websockets

async def go():
    async with websockets.connect('ws://localhost:8000') as ws:
        await ws.recv()

loop = asyncio.get_event_loop()
loop.run_until_complete(go())
```

Is there something obvious I'm doing wrong?

Thanks for your help!

**Comment by CharAct3** [comment]
`time.sleep(120)` blocks the server, use:
```python
import asyncio


@app.websocket('/')
async def test(request, ws):
    await asyncio.sleep(120)
    ws.send('hello')
```

**Comment by furious-luke** [comment]
Hey @CharAct3, that's a fair point about blocking the server, however I don't think it's related to the websockets getting clobbered. I've altered the server code to use `await asyncio.sleep(120)` and the websockets are still getting killed by a timeout with the same error.

**Comment by CharAct3** [comment]
Hey @furious-luke , you're right.
I was using sanic with version 0.6.0, so I did't meet this problem.
It's caused by `HttpProtocol.response_timeout`.

**Comment by furious-luke** [comment]
It looks like it shouldn't be affecting websockets, at least by the code in `sanic/websocket.py`:

```python
    def connection_timeout(self):
        # timeouts make no sense for websocket routes
        if self.websocket is None:
            super().connection_timeout()
```

Is it possible this method is being ignored for some reason?

**Comment by CharAct3** [comment]
@furious-luke Yes, this method is being ignored.

`WebsocketProtocol` inherits `HttpProtocol`.

And `HttpProtocol.connection_timeout` has been splited into three methods now: 
`request_timeout_callback`
`response_timeout_callback`
`keep_alive_timeout_callback`

ref #939

**Comment by furious-luke** [comment]
Ah, good to know.

It looks like I can just rename that method from `connection_timeout` to `response_timeout_callback` to resolve this issue on my end, does that sound right?

**Comment by CharAct3** [comment]
@furious-luke Yes, here is a monkey patch.
```python
from sanic.websocket import WebSocketProtocol

...

class CustomWebSocketProtocol(WebSocketProtocol):

    def request_timeout_callback(self):
        if self.websocket is None:
            super().request_timeout_callback()

    def response_timeout_callback(self):
        if self.websocket is None:
            super().response_timeout_callback()

app.run(protocol=CustomWebSocketProtocol)
```

**Comment by furious-luke** [comment]
Cool, thanks for your help!

**Comment by ashleysommer** [comment]
As the author of #939, I apologise. I did not test the changes on a websocket connection, and I didn't realize the Websocket protocol inherits from the HTTP Protocol.

I have created a PR with the fix here: https://github.com/channelcat/sanic/pull/976

**Comment by furious-luke** [comment]
No need for apologies! Thanks for responding and making a PR!
