### ISSUE TITLE
Error: Overlong 2 byte UTF-8 sequence detected when encoding string

### ISSUE THREAD

**Issue by rainyear** [channelcat/sanic#97]
while `return json(doc)`,  `doc` is fetched from mongodb.

**Comment by channelcat** [comment]
Hmm, it's possible the encoding of the contents of doc are not utf-8.  Do you have some example code I could see?

**Comment by rainyear** [comment]
Finally I found out that this was caused by the problem of `json(mongodb.ObjectID)`, `mongodb.ObjectID` cannot be serialized by the `json` method.

**Comment by kingname** [comment]
@rainyear in pandas the same problem and the same solution. just remove _id and everything fine.
