### ISSUE TITLE
Where is right place for save/update the context of request?

### ISSUE THREAD

**Issue by AndrewBurdyug** [channelcat/sanic#978]
Hi! 

In my app I want to use a `login_required` decorator, as on manner in docs (see authorized decorator 
 http://sanic.readthedocs.io/en/latest/sanic/decorators.html), but when I tried to set custom attrribute of request, e.g. `request.user = user` I got that error: 

```python
AttributeError: 'Request' object has no attribute 'user'
```
So, how I can add some extra context to request and pass it further?

**Comment by lixxu** [comment]
`request` is a dict, you need use `request['user'] = user` instead.

**Comment by AndrewBurdyug** [comment]
It works, thanks!
