### ISSUE TITLE
How to add UNIX socket to event loop?

### ISSUE THREAD

**Issue by dwelch91** [channelcat/sanic#999]
Hi, I am trying to write a small Sanic server that has both an HTTP interface and can service a plain UNIX socket in the same event loop. It seems like this should be possible, but after a lot of searching, I have yet to understand how you might do this. 

I'm assuming that any solution would be based on [Transports and Protocols](https://docs.python.org/3/library/asyncio-protocol.html#tcp-echo-server-protocol), but it isn't obvious how to integrate that into the Sanic event loop.

Here's a brief sketch of what I'd like to be able to do (pseudo-code + Python):

```
from socket import socket

from sanic import Sanic, response as Response

app = Sanic(__name__)

sock = socket(...)

@app.websocket('/ws')
async def remote_access(request, ws):
    while True:
        # ...

async def socket_read_handler():
    # ... sock.read()

async def socket_write_handler():
    # sock.write(...)

@app.post('/echo')
async def echo_test(request):
    return Response.text(request.body)


if __name__ == '__main__':
    app.??? # add socket to event loop somehow...
    app.run(host="0.0.0.0", port=8000, debug=True)
```
Thanks for any assistance!

Python 3.6
Sanic 0.6.0

**Comment by ashleysommer** [comment]
I believe there are two ways that Sanic 0.6.0 can allow you to do that, however I haven't tried them, so I don't know for sure they will work.

**1. With a listener:**
``` python
@app.listener('before_server_start')
async def init_socket(app, loop):
    await sock.open(..., loop=loop)
    # ...
```
This might not work, because at `'before_server_start'` while the loop is already created, and assigned to the current default loop on asyncio, the loop is actually not yet running.

**2. With a Task**
``` python
async def my_socket_task():
    loop = asyncio.get_event_loop()
    await socket.open(..., loop=loop)
    # ...

app.add_task(my_socket_task)
```
The registered tasks on the Sanic app get run when the loop actually starts. This might work better if option 1 doesn't work for you.

**Comment by dwelch91** [comment]
Thank you very much, I will give #2 a try.

**Comment by ashleysommer** [comment]
Just curious, did you try this out? How did it go for you?

**Comment by dwelch91** [comment]
@ashleysommer  Hi, thanks... I am away from my development system until later this week, so I haven't had time to follow through with this. Hope to get back to it in the next few days and will report back. Thanks again for the help.

**Comment by r0fls** [comment]
@dwelch91 any update?

**Comment by dwelch91** [comment]
Yes, I ended up using `asyncio.create_connection()` to create the socket connection to the backend UNIX socket, passing in the websocket as a parameter so that I could connection the websocket frontend to the UNIX socket backend. The frontend uses the `protocol` of the backend to do reads/writes (the server is basically a proxy).  
It is all working very well (and fast!) in production.

**Comment by idxn** [comment]
@dwelch91 Could you please give us a code example? I'm interested in how you implement it. Probably, it may be useful for us in the future
